---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 'what"s new' 
summary: In questo argomento sono elencate le modifiche apportate alle release più recenti di Gestione di sistema di SANtricity relative ai comandi CLI e script. 
---
= Novità
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In questo argomento sono elencate le modifiche apportate alle release più recenti di Gestione di sistema di SANtricity relative ai comandi CLI e script.

[NOTE]
====
Quando si emettono comandi SMcli al prompt dei comandi, è necessario immettere una barra rovesciata aggiuntiva (`\`) Come carattere di escape nel nome del percorso di un file di input o output quando si utilizza il sistema operativo Windows. La barra rovesciata aggiuntiva (`\`) Deve essere incluso quando si utilizza SMcli in modalità https sicura, fornendo l'opzione -u per specificare un utente di gestione degli accessi basato sui ruoli. Esempio: `C:\\dir\\subdir\\filename`

====
[NOTE]
====
Se si utilizza SANtricity 11.52 o una versione precedente, non è possibile eseguire l'aggiornamento alla versione più recente di SANtricity tramite la CLI legacy. Gli aggiornamenti da SANtricity 11.52 alle versioni successive possono essere eseguiti solo tramite SMcli.

====


== SANtricity 11,90

Nella tabella seguente sono elencate le modifiche ai comandi CLI e script per la versione 11,90.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-dispatch-limit.html["Imposta limite dimensioni spedizione AutoSupport"]
 a| 
Aggiunto comando



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/save-controller-arraymanagementcsr.html["Salvare l'arrayManagementCSR del controller"]
 a| 
Parametro aggiunto `KeySize`.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-email-smtp-delivery-method.html["Impostare il metodo di recapito della posta elettronica (SMTP)"]
 a| 
Parametro aggiunto `destinationAddress`.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storagearray-autosupport.html#examples["Mostra impostazioni AutoSupport"]
 a| 
Sono stati aggiunti i limiti delle dimensioni di spedizione e gli indirizzi e-mail di destinazione all'output di esempio per il comando.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/download-storagearray-keymanagementcertificate.html["Scarica StorageArray keyManagementCertificate"]
 a| 
Parametro aggiunto `privateKeyFile`.

|===


== SANtricity 11,81

Nella tabella seguente sono elencate le modifiche ai comandi CLI e script per la versione 11,81.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-devices["Identificare i dispositivi"]
 a| 
Aggiunto `identifyDevices` parametro.

|===


== SANtricity 11.80

Nella tabella seguente sono elencate le modifiche apportate ai comandi CLI e script per la release 11.80.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
xref:./commands-a-z/save-check-vol-parity-job-errors.adoc[Salva gli errori di parità del job di controllo del volume]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/start-check-vol-parity-job.adoc[Avviare il processo di verifica della parità del volume]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/show-check-vol-parity-jobs.adoc[Mostra job di controllo parità volume]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/show-check-vol-parity-job.adoc[Mostra job di verifica parità volume]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/stop-check-vol-parity-job.adoc[Interrompere il processo di verifica della parità del volume]
 a| 
Aggiunto comando



 a| 
xref:./get-started/command-line-parameters.adoc[Parametri della riga di comando legacy]
 a| 
Aggiunto `-useLegacyTransferPort` parametro.



 a| 
xref:./commands-a-z/autoconfigure-storagearray.adoc[Configurazione automatica dello storage array]
 a| 
Aggiunto `blockSize` parametro.



 a| 
xref:./commands-a-z/check-volume-parity.adoc[Controllare la parità del volume]
 a| 
Comando obsoleto.

|===


== SANtricity 11.70.5

Non sono state apportate modifiche a CLI e script Command per la versione 11.70.5.



== SANtricity 11.70.4

Nella tabella seguente sono elencate le modifiche apportate ai comandi CLI e script per la release 11.70.4.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
xref:./get-started/downloadable-smcli-parameters.adoc[Scaricare i parametri della riga di comando SMcli]
 a| 
Aggiunto `-t` e. `-T` descrizioni dei parametri del token di accesso per l'autenticazione a più fattori.

|===


== SANtricity 11.70.3

Nella tabella seguente sono elencate le modifiche apportate ai comandi CLI e script per la release 11.70.3.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
xref:./commands-a-z/start-diskpool-resourceprovisioning.adoc[Avviare Disk Pool Resource Provisioning]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/start-volumegroup-resourceprovisioning.adoc[Avviare il provisioning delle risorse del gruppo di volumi]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/start-diskpool-fullprovisioning.adoc[Avviare il provisioning completo del pool di dischi]
 a| 
Aggiornato `disableResourceProvisioning` descrizione del parametro.



 a| 
xref:./commands-a-z/start-volumegroup-fullprovisioning.adoc[Avviare il provisioning completo del gruppo di volumi]
 a| 
Aggiornato `disableResourceProvisioning` descrizione del parametro.



 a| 
xref:./commands-a-z/recreate-storagearray-securitykey.html[Ricreare la chiave di sicurezza esterna]
 a| 
Aggiunto `deleteOldKey` parametro.



 a| 
xref:./commands-a-z/create-diskpool.html[Creare un pool di dischi]
 a| 
Aggiornato `driveCount` descrizione del parametro.

|===


== SANtricity 11.70.2

Nella tabella seguente sono elencate le modifiche apportate ai comandi CLI e script per la release 11.70.2.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
xref:./commands-a-z/create-snmpuser-username.adoc[Registrare l'utente SNMPv3 USM]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/set-snmpuser-username.adoc[Aggiornare l'utente SNMPv3 USM]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/show-allsnmpusers.adoc[Mostra utente SNMPv3 USM]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/delete-snmpuser-username.adoc[Annullare la registrazione dell'utente SNMPv3 USM]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/create-snmptrapdestination.adoc[Registrare la destinazione della trap SNMP]
 a| 
Aggiunto `userName` e. `engineid` parametri.



 a| 
xref:./commands-a-z/set-snmptrapdestination-trapreceiverip.adoc[Aggiorna destinazione trap SNMP]
 a| 
Aggiunto `userName` e. `engineid` parametri.



 a| 
xref:./commands-a-z/start-snmptrapdestination.adoc[Verificare la destinazione della trap SNMP]
 a| 
Aggiunto `userName` e. `engineid` parametri.

|===


== SANtricity 11.70.1

Nella tabella seguente sono elencate le modifiche apportate ai comandi CLI e script per la release 11.70.1.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
xref:./commands-a-z/start-drive-erase.adoc[Avviare la cancellazione del disco]
 a| 
Aggiunto comando



 a| 
xref:./commands-a-z/import-storagearray-securitykey-file.adoc[Importare la chiave di sicurezza dello storage array]
 a| 
Aggiunto `forceOverwrite` parametro.



 a| 
xref:./commands-a-z/set-controller-hostport.adoc[Impostare le proprietà della porta host del controller]
 a| 
Aggiunto `fecMode` parametro.



 a| 
xref:./commands-a-z/show-syslog-summary.adoc[Mostra la configurazione syslog]
 a| 
Aggiunto `syslogFormat` parametro.



 a| 
xref:./commands-a-z/set-syslog.adoc[Configurare le impostazioni syslog]
 a| 
Aggiunto `syslogFormat` parametro.



 a| 
xref:./commands-a-z/set-emailalert.adoc[Configurare le impostazioni degli avvisi e-mail]
 a| 
Aggiunto `serverEncryption`, `serverPort`, `serverUsername`, e. `serverPassword` parametri.



 a| 
xref:./commands-a-z/show-emailalert-summary.adoc[Mostra la configurazione degli avvisi e-mail]
 a| 
Aggiunto `SMTP` crittografia, porta e dati dei parametri delle credenziali.



 a| 
xref:./commands-a-z/recover-volume.adoc[Ripristinare il volume RAID]
 a| 
Aggiunto `blockSize` parametro.

|===


== SANtricity 11.70

Nella tabella seguente sono elencate le modifiche apportate ai comandi CLI e script per la release 11.70.

[cols="2*"]
|===
| Comando | Descrizione della modifica 


 a| 
xref:./commands-a-z/download-storagearray-firmware.adoc[Scaricare il firmware/NVSRAM dell'array di storage]
 a| 
Aggiunto `healthCheckNeedsAttnOverride` parametro.



 a| 
xref:./commands-a-z/create-volume-diskpool.adoc[Creare un volume nel pool di dischi]
 a| 
Aggiunto `raidLevel` parametro.



 a| 
xref:./commands-a-z/enable-storagearray-externalkeymanagement-file.adoc[Abilitare la gestione esterna delle chiavi di sicurezza]
 a| 
Aggiunto `saveFile` parametro.



 a| 
xref:./commands-a-z/disable-storagearray-externalkeymanagement-file.adoc[Disattivare la gestione esterna delle chiavi di sicurezza]
 a| 
Aggiunto `saveFile` parametro.



 a| 
xref:./commands-a-z/recover-volume.adoc[Ripristinare il volume RAID]
 a| 
Aggiunto `hostUnmapEnabled` parametro.

|===