---
permalink: get-started/downloadable-smcli-parameters.html 
sidebar: sidebar 
keywords: downloadable, smcli, command line, parameters, identify, devices, SAML, multifactor, authentication, https, certificate, array, 
summary: 'SANtricity OS 11,60 e le versioni più recenti includono la possibilità di scaricare e installare la versione basata su http della CLI (nota anche come Secure CLI o SMcli) direttamente attraverso il Gestore di sistema di SANtricity.' 
---
= Parametri della riga di comando SMcli scaricabili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity OS 11,60 e le versioni più recenti includono la possibilità di scaricare e installare la versione basata su http della CLI (nota anche come "Secure CLI" o SMcli) direttamente attraverso il Gestore di sistema di SANtricity.



== 11.60 e parametri della riga di comando SMcli scaricabili più recenti

La versione scaricabile di SMcli è disponibile sui controller E4000, EF600, EF300, E5700, EF570, E2800, EF280, EF300C e EF600C. Per scaricare SMcli in Gestione di sistema di SANtricity, selezionare *Impostazioni* *sistema* e *componenti aggiuntivi* *interfaccia della riga di comando* .


NOTE: Sul sistema di gestione in cui si intende eseguire i comandi CLI deve essere disponibile Java Runtime Environment (JRE), versione 8 e successive.

Come per le versioni precedenti di SMcli, l'SMcli scaricabile tramite Gestore di sistema di SANtricity dispone di un insieme unico di parametri. Per informazioni sull'utilizzo dei parametri della riga di comando per SANtricity OS 11.53 e versioni precedenti, vedere link:https://docs.netapp.com/us-en/e-series-cli/get-started/command-line-parameters.html["Parametri della riga di comando legacy"].



=== Autenticazione a più fattori

Se SAML (Security Assertion Markup Language) è attivato, solo i token di accesso possono essere utilizzati con la CLI. Se SAML non è attivato, è possibile utilizzare il nome utente/password o i token di accesso. I token di accesso possono essere generati tramite Gestore di sistema di SANtricity.

[cols="2*"]
|===
| Parametro | Definizione 


 a| 
`-t`
 a| 
Definisce il token di accesso da utilizzare per l'autenticazione con un array di storage. Un token di accesso sostituisce il nome utente e la password.



 a| 
`-T` (maiuscolo)
 a| 
Questo argomento richiede uno dei due argomenti seguenti:

* `access_token-file` - Contiene il token di accesso da utilizzare per l'autenticazione
* `-(dash)` - Leggi il token di accesso da stdin




 a| 
`-u`
 a| 
Seguire questo parametro con `_username_` variabile. Questo parametro è obbligatorio quando non viene utilizzato un token di accesso.



 a| 
`-p`
 a| 
Definisce la password per lo storage array su cui si desidera eseguire i comandi. La password non è necessaria in presenza delle seguenti condizioni:

* Non è stata impostata una password sullo storage array.
* La password viene specificata in un file di script in esecuzione.




 a| 
`-P` (maiuscolo)
 a| 
Questo argomento richiede uno dei due argomenti seguenti:

* `_password_file_` - Contiene la password da utilizzare per l'autenticazione.
* `-` (Un trattino) - Leggi la password da `stdin`.


|===


=== Parametri generali della riga di comando della modalità https

L'SMcli scaricabile supporta solo la modalità https. Di seguito sono riportati i parametri della riga di comando comunemente utilizzati per la modalità https.

[cols="2*"]
|===
| Parametro | Definizione 


 a| 
`_host-name-or-IP-address_`
 a| 
Specifica il nome host o l'indirizzo IP (Internet Protocol) (`_xxx.xxx.xxx.xxx_`) di un array storage gestito fuori banda.

Quando si gestisce la gestione dello storage out-of-band tramite la connessione Ethernet su ciascun controller, è necessario specificare `_host-name-or-IP-address_` dei controller.



 a| 
`-k`
 a| 
Questo argomento opzionale consente di eseguire un `*https*` client per operare in modalità non sicura. Ciò significa che il certificato dello storage array non verrà validato. Per impostazione predefinita, se omesso, viene eseguita la convalida corretta.


NOTE: Per ulteriori informazioni sulla gestione dei certificati degli array di storage, vedere <<storedcertificates,Gestione dei parametri della riga di comando dei certificati memorizzati>>.



 a| 
`-e`
 a| 
Esegue i comandi senza eseguire prima un controllo della sintassi.



 a| 
`-L` (maiuscolo)
 a| 
Visualizza le note legali per SMcli scaricabili.



 a| 
`-n`
 a| 
Specifica l'etichetta memorizzata localmente sulla quale si desidera eseguire i comandi di script. Questa opzione è opzionale quando si utilizza `_host-name-or-IP-address_`. L'etichetta memorizzata localmente è necessaria quando `_host-name-or-IP-address_` non viene utilizzato.


NOTE: Per ulteriori informazioni sull'utilizzo di etichette memorizzate localmente per la gestione degli array di storage, vedere <<managearrays,Gestione dei parametri della riga di comando degli array memorizzati>>.



 a| 
`-o`
 a| 
Specifica un nome di file per tutto il testo di output che è il risultato dell'esecuzione dei comandi di script. Utilizzare `-o` parametro con questi parametri:

* `-c`
* `-f`


Se non si specifica un file di output, il testo di output passa all'output standard  `stdout`). Viene inviato tutto l'output dei comandi che non sono comandi di script a. `stdout`, indipendentemente dal fatto che questo parametro sia impostato o meno.



 a| 
`-S` (maiuscolo)
 a| 
Elimina i messaggi informativi che descrivono l'avanzamento del comando visualizzato quando si eseguono i comandi script. (La soppressione dei messaggi informativi viene anche chiamata modalità silenziosa). Questo parametro elimina i seguenti messaggi:

* `Performing syntax check`
* `Syntax check complete`
* `Executing script`
* `Script execution complete`
* `SMcli completed successfully`




 a| 
`-version`
 a| 
Visualizza la versione scaricabile di SMcli



 a| 
`-?`
 a| 
Mostra le informazioni sull'utilizzo dei comandi CLI.

|===


=== Gestione degli storage array

I seguenti parametri della riga di comando consentono di gestire gli array memorizzati tramite l'etichetta memorizzata localmente.


NOTE: L'etichetta memorizzata localmente potrebbe non corrispondere al nome effettivo dell'array di storage visualizzato sotto Gestione di sistema di SANtricity.

[cols="2*"]
|===
| Parametro | Definizione 


 a| 
`SMcli storageArrayLabel show all`
 a| 
Visualizza tutte le etichette memorizzate localmente e i relativi indirizzi



 a| 
`SMcli storageArrayLabel show label <LABEL>`
 a| 
Visualizza gli indirizzi associati all'etichetta memorizzata localmente denominata `<LABEL>`



 a| 
`SMcli storageArrayLabel delete all`
 a| 
Elimina tutte le etichette memorizzate localmente



 a| 
`SMcli storageArrayLabel delete label <LABEL>`
 a| 
Elimina l'etichetta memorizzata localmente denominata `<LABEL>`



 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] storageArrayLabel add label <LABEL>`
 a| 
* Aggiunge un'etichetta memorizzata localmente con il nome `<LABEL>` contenente gli indirizzi forniti
* Gli aggiornamenti non sono direttamente supportati. Per eseguire l'aggiornamento, eliminare l'etichetta e aggiungerla nuovamente.



NOTE: SMcli non contatta lo storage array quando si aggiunge un'etichetta memorizzata localmente.

|===
[cols="2*"]
|===
| Parametro | Definizione 


 a| 
`SMcli localCertificate show all`
 a| 
Visualizza tutti i certificati attendibili memorizzati localmente



 a| 
`SMcli localCertificate show alias <ALIAS>`
 a| 
Visualizza un certificato attendibile memorizzato localmente con l'alias `<ALIAS>`



 a| 
`SMcli localCertificate delete all`
 a| 
Elimina tutti i certificati attendibili memorizzati localmente



 a| 
`SMcli localCertificate delete alias <ALIAS>`
 a| 
Elimina un certificato attendibile memorizzato localmente con l'alias `<ALIAS>`



 a| 
`SMcli localCertificate trust file <CERT_FILE> alias <ALIAS>`
 a| 
* Salva un certificato per essere attendibile con l'alias `<ALIAS>`
* Il certificato da trusted viene scaricato dal controller in un'operazione separata, ad esempio utilizzando un browser Web




 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] localCertificate trust`
 a| 
* Si connette a ciascun indirizzo e salva il certificato restituito nell'archivio di certificati attendibili
* Il nome host o l'indirizzo IP specificato viene utilizzato come alias per ciascun certificato salvato in questo modo
* L'utente deve verificare che il certificato sui controller sia attendibile prima di eseguire questo comando
* Per la massima sicurezza, il comando trust che utilizza un file deve essere utilizzato per garantire che il certificato non sia cambiato tra la convalida dell'utente e l'esecuzione di questo comando


|===


=== Identificare i dispositivi

Il seguente parametro della riga di comando consente di visualizzare le informazioni relative a tutti i dispositivi applicabili visibili all'host.


NOTE: A partire dalla versione SANtricity 11,81, SMcli `identifyDevices` Parametro sostituisce le funzionalità disponibili in precedenza tramite lo strumento SMdevices.

[cols="2*"]
|===
| Parametro | Definizione 


 a| 
`identifyDevices`
 a| 
Cerca tutti i dispositivi a blocchi SCSI nativi associati ai nostri array di storage. Per ogni dispositivo trovato, riporta varie informazioni, come nome di dispositivo specifico del sistema operativo nativo, array di storage associato, nome del volume, informazioni LUN, ecc.

|===


==== Esempi

Fare riferimento a quanto segue per esempi di `-identifyDevices` Parametro all'interno dei sistemi operativi Linux e Windows.

.Linux
[listing]
----
ICTAE11S05H01:~/osean/SMcli-01.81.00.10004/bin # ./SMcli -identifyDevices
  <n/a> (/dev/sg2) [Storage Array ictae11s05a01, Volume 1, LUN 0, Volume ID <600a098000bbd04f00001c7365426b58>, Alternate Path (Controller-A): Non owning controller - Active/Non-optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  /dev/sdb (/dev/sg3) [Storage Array ictae11s05a01, Volume Access, LUN 7, Volume ID <600a098000bbcdd3000002005a731d29>]
  <n/a> (/dev/sg4) [Storage Array ictae11s05a01, Volume 1, LUN 0, Volume ID <600a098000bbd04f00001c7365426b58>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  /dev/sdc (/dev/sg5) [Storage Array ictae11s05a01, Volume Access, LUN 7, Volume ID <600a098000bbcdd3000002005a731d29>]
SMcli completed successfully.
----
.Windows
[listing]
----
PS C:\Users\Administrator\Downloads\SMcli-01.81.00.0017\bin> .\SMcli -identifyDevices
  \\.\PHYSICALDRIVE1 [Storage Array ICTAG22S08A01, Volume Vol1, LUN 1, Volume ID <600a0980006cee060000592e6564fa6a>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE2 [Storage Array ICTAG22S08A01, Volume Vol2, LUN 2, Volume ID <600a0980006ce727000001096564f9f5>, Preferred Path (Controller-A): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE3 [Storage Array ICTAG22S08A01, Volume Vol3, LUN 3, Volume ID <600a0980006cee06000059326564fa76>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE4 [Storage Array ICTAG22S08A01, Volume Vol4, LUN 4, Volume ID <600a0980006ce7270000010a6564fa01>, Preferred Path (Controller-A): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
SMcli completed successfully.
----


==== Note aggiuntive

* Compatibile con i sistemi operativi Linux e Windows che eseguono piattaforme x86-64 solo con interfacce host basate su SCSI.
+
** Le interfacce host basate su NVMe non sono supportate.


* Il `identifyDevices` Il parametro non causa una nuova scansione a livello del sistema operativo. Esegue l'iterazione dei dispositivi esistenti visti dal sistema operativo.
* È necessario disporre di autorizzazioni utente sufficienti per eseguire `identifyDevices` comando.
+
** Ciò include la capacità di leggere dai dispositivi a blocchi nativi del sistema operativo ed eseguire comandi di interrogazione SCSI.



