---
permalink: get-started/firmware-compatibility-levels.html 
sidebar: sidebar 
keywords: firmware, compatibility, levels 
summary: I comandi di script nelle sezioni seguenti elencano i livelli minimi di firmware sotto cui possono essere eseguiti i comandi di script. 
---
= Livelli di compatibilità del firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I comandi di script nelle sezioni seguenti elencano i livelli minimi di firmware sotto cui possono essere eseguiti i comandi di script.

I comandi script e i parametri dei comandi non vengono eseguiti in tutte le versioni del firmware del controller. Nei comandi di script, i livelli del firmware sono elencati sotto l'intestazione "`MInimum firmware Level`" (livello minimo firmware). Questo elenco descrive come interpretare le informazioni relative ai livelli del firmware.

* Se un comando script non elenca un livello minimo di firmware del controller, il comando script e tutti i parametri associati a tale comando possono essere eseguiti con qualsiasi livello di firmware del controller.
* Un numero di firmware del controller senza informazioni esplicative indica che il livello di firmware del controller si applica all'intero comando script e a tutti i parametri per quel comando script.
* Un numero di firmware del controller associato a un parametro indica il livello minimo di firmware del controller sotto il quale il parametro può essere eseguito.


[NOTE]
====
Il livello minimo del firmware del controller indica il supporto da parte del software che rilascia il comando, nonché il supporto da parte di tutti i software di gestione dello storage che prelevano l'utilizzo. Le funzionalità di supporto della CLI dipendono dall'hardware utilizzato. Quando viene inserito un comando non supportato, viene visualizzato un messaggio di errore.

====


== Esempi di livelli di compatibilità del firmware

Il `create hostGroup` command ha la seguente sezione.

*Livello minimo del firmware*

8.10

Questo livello indica che l'intero comando script viene eseguito con una versione minima del firmware del controller 8.10.

Il `create ssdCache` command ha la seguente sezione.

*Livello minimo del firmware*

7.84

8.20.11 - aggiunto il `*securityType*` parametro.

Queste annotazioni indicano che il comando script e tutti i parametri tranne `*securityType*` eseguire con una versione minima del firmware del controller 7.84. Il `*securityType*` Il parametro viene eseguito con una versione minima del firmware del controller 8.20_M3.
