---
permalink: commands-a-z/activate-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, asynchronous, mirroring 
summary: Il comando Activate StorageArray Feature attiva la funzione di mirroring asincrono. 
---
= Attivare il mirroring asincrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `activate storageArray feature` Attiva la funzione di mirroring asincrono.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.

[NOTE]
====
Questo comando è applicabile solo per il mirroring asincrono su Fibre Channel.

====


== Ruoli

Per eseguire questo comando su uno storage array E400, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Dopo aver attivato la funzione di mirroring asincrono, è necessario impostare un gruppo di mirror asincrono e una coppia di mirroring asincrono.



== Sintassi

[source, cli]
----
activate storageArray feature=asyncRemoteMirror
----


== Parametri

Nessuno.



== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
