---
permalink: commands-a-z/activate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, synchronous mirroring, supported arrays, roles, context, syntax, parameters, data assurance management, minimum firmware level 
summary: Il comando Activate StorageArray Feature attiva la funzione Synchronous Mirroring e crea il volume di repository mirror. 
---
= Attivare il mirroring sincrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `activate storageArray feature` Il comando attiva la funzione di mirroring sincrono e crea il volume di repository mirror.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800 e E5700, a condizione che siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800 o E5700, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Quando si utilizza questo comando, è possibile definire il volume di repository mirror in uno dei tre modi seguenti:

* Dischi definiti dall'utente
* Gruppo di volumi definito dall'utente
* Numero di dischi definito dall'utente


Se si sceglie di definire un numero di dischi, il firmware del controller sceglie quali dischi utilizzare per il volume repository mirror.

[NOTE]
====
Nelle versioni precedenti di questo comando, l'identificatore di funzione era `remoteMirror`. Questo identificatore di funzione non è più valido e viene sostituito da `syncMirror`.

====


== Sintassi (dischi definiti dall'utente)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_,pass:quotes[[_drawerIDn_,]pass:quotes[_slotIDn_
[driveType=(fibre | SATA | SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 5 | 6)
repositoryDrives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn)_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Sintassi (gruppo di volumi definito dall'utente)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryVolumeGroup=pass:quotes[_volumeGroupName_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== Sintassi (numero di dischi definito dall'utente)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`repositoryRAIDLevel`
 a| 
Il livello RAID per il volume repository mirror. I valori validi sono `0`, `1`, `3`, `5`, o. `6`.



 a| 
`repositoryDrives`
 a| 
I dischi per il volume di repository mirror. Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`repositoryVolumeGroupUserLabel`
 a| 
Il nome che si desidera assegnare al nuovo gruppo di volumi in cui si trova il volume del repository mirror. Racchiudere il nome del gruppo di volumi tra virgolette doppie (" ").



 a| 
`repositoryVolumeGroup`
 a| 
Il nome del gruppo di volumi del repository mirror in cui si trova il volume del repository mirror. Per determinare i nomi dei gruppi di volumi nell'array di storage, eseguire `show storageArray profile` comando.)



 a| 
`freeCapacityArea`
 a| 
Il numero di indice dello spazio libero in un gruppo di volumi esistente che si desidera utilizzare per creare il volume di repository mirror. La capacità libera è definita come la capacità libera tra i volumi esistenti in un gruppo di volumi. Ad esempio, un gruppo di volumi potrebbe avere le seguenti aree: Volume 1, capacità libera, volume 2, capacità libera, volume 3, capacità libera. Per utilizzare la capacità libera seguente volume 2, specificare:

[listing]
----
freeCapacityArea=2
----
Eseguire `show volumeGroup` comando per determinare se esiste un'area di capacità libera.



 a| 
`repositoryDriveCount`
 a| 
Il numero di dischi non assegnati che si desidera utilizzare per il volume di repository mirror.



 a| 
`driveType`
 a| 
Il tipo di disco per il quale si desidera recuperare le informazioni. Non è possibile combinare tipi di unità.

I tipi di dischi validi sono:

* `fibre`
* `SATA`
* `SAS`
* NVMe4K


Se non si specifica un tipo di disco, il comando viene impostato per impostazione predefinita su all type.



 a| 
`trayLossProtect`
 a| 
L'impostazione per applicare la protezione dalle perdite dei vassoi quando si crea il volume del repository mirror. Per applicare la protezione dalle perdite dei vassoi, impostare questo parametro su `TRUE`. Il valore predefinito è `FALSE`.



 a| 
`drawerLossProtect`
 a| 
L'impostazione per applicare la protezione dalle perdite dei cassetti quando si crea il volume di repository mirror. Per applicare la protezione dalle perdite dei cassetti, impostare questo parametro su `TRUE`. Il valore predefinito è `FALSE`.

|===


== Note

Il `repositoryDrives` il parametro supporta sia i vassoi per dischi ad alta capacità che quelli a bassa capacità. Un vassoio per dischi ad alta capacità dispone di cassetti che trattengono le unità. I cassetti scorrono fuori dal vassoio dell'unità per consentire l'accesso alle unità. Un vassoio per unità a bassa capacità non dispone di cassetti. Per un vassoio dell'unità ad alta capacità, è necessario specificare l'identificativo (ID) del vassoio dell'unità, l'ID del cassetto e l'ID dello slot in cui si trova l'unità. Per un vassoio dell'unità a bassa capacità, è necessario specificare solo l'ID del vassoio dell'unità e l'ID dello slot in cui si trova un'unità. Per un vassoio dell'unità a bassa capacità, un metodo alternativo per identificare una posizione per un'unità consiste nel specificare l'ID del vassoio dell'unità, impostare l'ID del cassetto su `0`E specificare l'ID dello slot in cui si trova un'unità.

Se le unità selezionate per `repositoryDrives` i parametri non sono compatibili con altri parametri, ad esempio `repositoryRAIDLevel` Parametro), il comando script restituisce un errore e Synchronous Mirroring non è attivato. L'errore restituisce la quantità di spazio necessaria per il volume del repository mirror. È quindi possibile immettere nuovamente il comando e specificare la quantità di spazio appropriata.

Se si inserisce un valore troppo piccolo per lo spazio di storage del repository per i volumi del repository mirror, il firmware del controller restituisce un messaggio di errore che fornisce la quantità di spazio necessaria per i volumi del repository mirror. Il comando non tenta di attivare il mirroring sincrono. È possibile immettere di nuovo il comando utilizzando il valore del messaggio di errore per il valore dello spazio di storage del repository.

Quando si assegnano i dischi, se si imposta `trayLossProtect` parametro a. `TRUE` se sono stati selezionati più dischi da un vassoio, l'array di storage restituisce un errore. Se si imposta `trayLossProtect` parametro a. `FALSE`, l'array di storage esegue le operazioni, ma il gruppo di volumi creato potrebbe non disporre della protezione contro la perdita dei vassoi.

Quando il firmware del controller assegna i dischi, se si imposta `trayLossProtect` parametro a. `TRUE`, lo storage array restituisce un errore se il firmware del controller non è in grado di fornire dischi che comportano la protezione della perdita dei vassoi nel nuovo gruppo di volumi. Se si imposta `trayLossProtect` parametro a. `FALSE`, lo storage array esegue l'operazione anche se significa che il gruppo di volumi potrebbe non disporre della protezione contro la perdita di vassoio.

Il `drawerLossProtect` il parametro determina se i dati di un volume sono accessibili in caso di guasto di un cassetto. Quando si assegnano i dischi, se si imposta `drawerLossProtect` parametro a. `TRUE` selezionando più di un disco da un cassetto, lo storage array restituisce un errore. Se si imposta `drawerLossProtect` parametro a. `FALSE`, lo storage array esegue le operazioni, ma il gruppo di volumi creato potrebbe non disporre della protezione contro la perdita di cassetto.



== Gestione della data assurance

La funzione Data Assurance (da) aumenta l'integrità dei dati nell'intero sistema storage. DA consente all'array di storage di verificare la presenza di errori che potrebbero verificarsi quando i dati vengono spostati tra gli host e i dischi. Quando questa funzione è attivata, l'array di storage aggiunge i codici di controllo degli errori (noti anche come CRC (Cyclic Redundancy Checks) a ciascun blocco di dati del volume. Dopo lo spostamento di un blocco di dati, l'array di storage utilizza questi codici CRC per determinare se si sono verificati errori durante la trasmissione. I dati potenzialmente corrotti non vengono scritti su disco né restituiti all'host.

Se si desidera utilizzare la funzione da, iniziare con un pool o un gruppo di volumi che include solo dischi che supportano da. Quindi, creare volumi compatibili con da. Infine, mappare questi volumi con funzionalità da all'host utilizzando un'interfaccia i/o in grado di eseguire il da. Le interfacce i/o che supportano il da includono Fibre Channel, SAS e iSER su InfiniBand (iSCSI Extensions per RDMA/IB). DA non è supportato da iSCSI su Ethernet o da SRP su InfiniBand.

[NOTE]
====
Quando tutti i dischi sono compatibili con da, è possibile impostare `dataAssurance` parametro a. `enabled` E quindi utilizzare da con determinate operazioni. Ad esempio, è possibile creare un gruppo di volumi che includa dischi compatibili con da e quindi creare un volume all'interno di tale gruppo di volumi abilitato per da. Altre operazioni che utilizzano un volume abilitato da dispongono di opzioni per supportare la funzione da.

====
Se il `dataAssurance` il parametro è impostato su `enabled`, per i candidati ai volumi verranno considerati solo i dischi con data assurance; in caso contrario, verranno presi in considerazione sia i dischi con data assurance che quelli non con data assurance. Se sono disponibili solo dischi Data Assurance, il nuovo gruppo di volumi verrà creato utilizzando i dischi Data Assurance abilitati.



== Livello minimo del firmware

7.10 aggiunge funzionalità RAID livello 6.

7.60 aggiunge `drawerID` input dell'utente, il `driveMediaType` e il `drawerLossProtect` parametro.

7.75 aggiunge `dataAssurance` parametro.

8.10 rimuove `driveMediaType` parametro.

8.60 aggiunge `driveType` parametro.
