---
permalink: commands-a-z/autoconfigure-storagearray-hotspares.html 
sidebar: sidebar 
keywords: autoconfigure, storage, array, hot spares, supported, roles, syntax, parameters, minimum firmware level 
summary: Il comando di configurazione automatica StorageArray Hotspares definisce e configura automaticamente le hot spare in un array di storage. È possibile eseguire questo comando in qualsiasi momento. Questo comando fornisce la migliore copertura hot spare per uno storage array. 
---
= Configurazione automatica degli hot spare dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `autoConfigure storageArray hotSpares` il comando definisce e configura automaticamente le hot spare in un array di storage. È possibile eseguire questo comando in qualsiasi momento. Questo comando fornisce la migliore copertura hot spare per uno storage array.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli]
----
autoConfigure storageArray hotSpares
----


== Parametri

Nessuno.



== Note

Quando si esegue `autoconfigure storageArray hotSpares` il firmware del controller determina il numero di hot spare da creare in base al numero totale e al tipo di dischi nell'array di storage. Per i dischi SAS, il firmware del controller crea un hot spare per lo storage array e un hot spare aggiuntivo per ogni 60 dischi nello storage array.



== Livello minimo del firmware

6.10
