---
permalink: commands-a-z/check-repositoryconsistency.html 
sidebar: sidebar 
keywords: check, repository, consistency 
summary: 'Il comando check repositoryConsistency genera un report basato sull"analisi dei dati nel volume di repository sottostante di un oggetto specificato.' 
---
= Verificare la coerenza del repository
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `check repositoryConsistency` il comando genera un report basato sull'analisi dei dati nel volume di repository sottostante di un oggetto specificato.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
check (snapGroup pass:quotes[[_snapGroupName_]] repositoryConsistency |
snapVolume pass:quotes[[_snapVolumeName_]] repositoryConsistency |
volume pass:quotes[[_volumeName_]] repositoryConsistency |
volumeCopy target pass:quotes[[_targetName_]] repositoryConsistency |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
repositoryConsistency localVolume=pass:quotes[_"localVolumeName"_]]
file=pass:quotes[_"filePath"_]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`repositoryConsistency`
 a| 
Specifica che il gruppo di snapshot, il volume di snapshot, il volume o il gruppo di mirror asincrono (a seconda di quale è specificato dal parametro corrispondente) viene controllato per verificare la coerenza.



 a| 
`snapGroup`
 a| 
Il nome del gruppo di snapshot su cui eseguire un controllo di coerenza. Racchiudere il nome del gruppo di snapshot tra parentesi quadre ([ ]). Se il nome del gruppo di snapshot contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`snapVolume`
 a| 
Il nome del volume di snapshot su cui eseguire un controllo di coerenza. Racchiudere il nome del volume snapshot tra parentesi quadre ([ ]). Se il nome del volume di snapshot contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`volume`
 a| 
Il nome del volume thin su cui eseguire un controllo di coerenza. Racchiudere il nome del volume sottile tra parentesi quadre ([ ]). Se il nome del volume sottile contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`volumeCopy`
 a| 
Specifica che la destinazione di una relazione di copia del volume viene controllata per verificarne la coerenza.



 a| 
`target`
 a| 
Utilizzare solo in combinazione con `volumeCopy` parametro per specificare il nome del volume di destinazione della relazione di copia del volume. Se il nome del volume contiene caratteri speciali o è composto solo da numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`asyncMirrorGroup`
 a| 
Il nome del gruppo di mirror asincrono su cui eseguire un controllo di coerenza. Racchiudere il nome del gruppo mirror asincrono tra parentesi quadre ([ ]). Se il nome del gruppo mirror asincrono contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`localVolume`
 a| 
Utilizzare solo con `asyncMirrorGroup` parametro per specificare il nome di un volume locale che partecipa alla relazione mirror. È possibile specificare un volume locale che sia l'origine o la destinazione su una relazione mirror. Racchiudere il nome del volume locale tra virgolette doppie (" ").



 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare il report risultante dalla verifica di coerenza. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\repoConsistency.txt"` Questo parametro deve essere visualizzato per ultimo, dopo uno qualsiasi dei parametri opzionali.

|===


== Note

Il report generato da questo comando è destinato all'utilizzo da parte del supporto tecnico per l'analisi dei problemi.



== Livello minimo del firmware

7.83
