---
permalink: commands-a-z/clear-storagearray-firmwarependingarea.html 
sidebar: sidebar 
keywords: clear, storage array, firmware, pending, area 
summary: 'Il comando clear StorageArray firmwarePendingArea elimina un"immagine del firmware o i valori NVSRAM precedentemente scaricati dal buffer di area in sospeso.' 
---
= Cancellare l'area in sospeso del firmware dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `clear storageArray firmwarePendingArea` Il comando elimina un'immagine del firmware o i valori NVSRAM precedentemente scaricati dal buffer di area in sospeso.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
*Possibili danni alla configurazione dell'array di storage* -- non appena si esegue questo comando, il contenuto dell'area in sospeso esistente nell'array di storage viene cancellato.

====


== Sintassi

[listing]
----
clear storageArray firmwarePendingArea
----


== Parametri

Nessuno.
