---
permalink: commands-a-z/clear-volume-reservations.html 
sidebar: sidebar 
keywords: clear, volume, reservations 
summary: Il comando clear volume reservations elimina le prenotazioni di volumi persistenti. 
---
= Cancellare le prenotazioni di volumi
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `clear volume reservations` il comando cancella le prenotazioni persistenti dei volumi.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing, subs="+macros"]
----
clear (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]]) reservations
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`allVolumes`
 a| 
L'impostazione per eliminare le riserve di volume persistenti su tutti i volumi nell'array di storage.



 a| 
`volume`
 a| 
Il nome di un volume per il quale si desidera eliminare le prenotazioni persistenti. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o è composto solo da numeri, è necessario racchiuderlo tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`volumes`
 a| 
I nomi di diversi volumi per i quali si stanno eliminando le riserve persistenti. Immettere i nomi dei volumi membri utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Racchiudere ciascuno dei nomi tra virgolette doppie (" ").
* Separare ciascuno dei nomi con uno spazio.


|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per i nomi. I nomi possono avere un massimo di 30 caratteri.
