---
permalink: commands-a-z/clear-storagearray-firmwarependingarea.html 
sidebar: sidebar 
keywords: clear, storage array, firmware, pending, area 
summary: 'Il comando clear StorageArray firmwarePendingArea elimina un"immagine del firmware o i valori NVSRAM precedentemente scaricati dal buffer di area in sospeso.' 
---
= Cancella l'area in attesa del firmware dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `clear storageArray firmwarePendingArea` Il comando elimina un'immagine del firmware o i valori NVSRAM precedentemente scaricati dal buffer di area in sospeso.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Contesto

[NOTE]
====
*Possibili danni alla configurazione dell'array di storage* -- non appena si esegue questo comando, il contenuto dell'area in sospeso esistente nell'array di storage viene cancellato.

====


== Sintassi

[source, cli]
----
clear storageArray firmwarePendingArea
----


== Parametri

Nessuno.
