---
permalink: commands-a-z/clear-volume-unreadablesectors.html 
sidebar: sidebar 
keywords: clear, volume, unreadable, sectors 
summary: Il comando clear volume unreadableSectors elimina le informazioni di settore illeggibili da uno o più volumi. 
---
= Cancella i settori illeggibili del volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `clear volume unreadableSectors` il comando cancella le informazioni di settore illeggibili da uno o più volumi.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Sintassi

[source, cli, subs="+macros"]
----
clear (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]]) unreadableSectors
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`allVolumes`
 a| 
L'impostazione per eliminare le informazioni di settore illeggibili da tutti i volumi nell'array di storage.



 a| 
`volume`
 a| 
Il nome di un volume per il quale si cancellano informazioni di settore illeggibili. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o è composto solo da numeri, è necessario racchiuderlo tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`volumes`
 a| 
I nomi di diversi volumi per i quali si cancellano informazioni di settore illeggibili. Immettere i nomi dei volumi membri utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Racchiudere ciascuno dei nomi tra virgolette doppie (" ").
* Separare ciascuno dei nomi con uno spazio.


|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per i nomi. I nomi possono avere un massimo di 30 caratteri.
