---
permalink: commands-a-z/create-snapshot-volume.html 
sidebar: sidebar 
keywords: create, snapshot, volume 
summary: Il comando create SnapVolume crea un volume di snapshot con funzionalità di lettura/scrittura per le immagini snapshot di un volume di base. 
---
= Crea volume snapshot - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `create snapVolume` il comando crea un volume di snapshot con funzionalità di lettura/scrittura per le immagini snapshot di un volume di base.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

È possibile mappare il volume di snapshot a un host e tutte le scritture dell'host risiedono nel volume di repository associato al volume di snapshot. È possibile assegnare il nuovo volume di snapshot a un volume di repository esistente oppure creare un nuovo volume di repository in un gruppo di volumi o in un pool di dischi.

[NOTE]
====
Non è possibile utilizzare questo comando per un'immagine snapshot utilizzata nella copia del volume online.

====


== Sintassi

[source, cli, subs="+macros"]
----
create snapVolume userLabel=pass:quotes[_"snapVolumeName_" snapImageID="_snapCGID:imageID_"]
[(repositoryVolume="repos_xxxx"]
[repositoryVolume=pass:quotes[_(volumeGroupName_]pass:quotes[[capacity=_capacityValue_]]]
[repositoryVolume=pass:quotes[(_diskPoolName_]pass:quotes[[capacity=_capacityValue_])]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`userLabel`
 a| 
Il nome che si desidera assegnare a un volume di snapshot. Racchiudere il nome del volume snapshot tra virgolette doppie (" ").



 a| 
`snapImageID`
 a| 
Identificativo alfanumerico di un'immagine snapshot che si desidera aggiungere al nuovo volume snapshot. L'identificatore di un'immagine snapshot è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` - Utilizzare questa opzione per visualizzare l'ultima immagine snapshot creata nel gruppo di snapshot.
* `OLDEST` - Utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ").



 a| 
`repositoryVolume`
 a| 
Il nome del volume del repository che contiene i dati modificati dell'immagine snapshot.

Sono disponibili due opzioni per definire il nome di un volume di repository:

* Utilizzare un nome di volume repository esistente
* Creare un nuovo volume di repository quando si esegue questo comando


Il nome di un volume di repository esistente è composto da due parti:

* Il termine "repos"
* Identificatore numerico a quattro cifre assegnato dal software di gestione dello storage al nome del volume del repository


Racchiudere il nome del volume di repository esistente tra virgolette doppie (" ").

Se si desidera creare un nuovo volume di repository quando si esegue questo comando, è necessario immettere il nome di un gruppo di volumi o di un pool di dischi in cui si desidera creare il volume di repository. In alternativa, è anche possibile definire la capacità del volume di repository. Se si desidera definire la capacità, è possibile utilizzare i seguenti valori:

* Un valore intero che rappresenta una percentuale della capacità del volume di base
* Un valore di frazione decimale che rappresenta una percentuale della capacità del volume di base
* Una dimensione specifica per il volume di repository. Le dimensioni sono definite in unità di `bytes`, `KB`, `MB`, `GB`, o. `TB`.


Se non si utilizza l'opzione di capacità, il software di gestione dello storage imposta la capacità sul 20% della capacità del volume di base.

Quando si esegue questo comando, il software di gestione dello storage crea il volume di repository per il volume di snapshot.



 a| 
`repositoryFullLimit`
 a| 
La percentuale di capacità del repository alla quale viene visualizzato un avviso che indica che il volume del repository snapshot è quasi pieno. USA valori interi. Ad esempio, un valore di 70 significa 70%. Il valore predefinito è 75.

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.

L'identificatore di un'immagine snapshot ha due parti separate da due punti (:):

* Il nome del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera creare un volume di snapshot denominato snapData1 utilizzando l'immagine snapshot più recente in un gruppo di snapshot con il nome snapGroup1 con un limite di riempimento massimo del 80% per il volume di repository, utilizzare questo comando:

[listing]
----
create snapVolume userLabel="snapData1" snapImageID="snapGroup1:newest"
repositoryVolume="repos_1234" repositoryFullLimit=80;
----
L'identificatore del volume del repository viene creato automaticamente dal software di gestione dello storage e dal firmware quando si crea un nuovo gruppo di snapshot. Non è possibile rinominare il volume del repository perché la ridenominazione del volume del repository interrompe il collegamento con le immagini snapshot.



== Livello minimo del firmware

7.83
