---
permalink: commands-a-z/create-read-only-snapshot-volume.html 
sidebar: sidebar 
keywords: create, read only, snapshot, volume 
summary: Il comando create snapVolume crea un volume snapshot di sola lettura per le immagini snapshot di un volume di base. Per modificare un volume snapshot di sola lettura in un volume di lettura/scrittura, utilizzare il comando set SnapVolume convertToReadWrite. 
---
= Creare un volume snapshot di sola lettura
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `create snapVolume` il comando crea un volume snapshot di sola lettura per le immagini snapshot di un volume di base. Per modificare un volume snapshot di sola lettura in un volume di lettura/scrittura, utilizzare `set snapVolume convertToReadWrite` comando.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Non è possibile utilizzare questo comando per un'immagine snapshot utilizzata nella copia del volume online.

====


== Sintassi

[source, cli, subs="+macros"]
----
create snapVolume userLabel=pass:quotes[_"snapVolumeName"_
snapImageID="_snapCGID:imageID"_]
readOnly
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`userLabel`
 a| 
Il nome che si desidera assegnare a un volume di snapshot. Racchiudere il nome del volume snapshot tra virgolette doppie (" ").



 a| 
`snapImageID`
 a| 
Il nome di un'immagine snapshot che si desidera aggiungere al nuovo volume di snapshot di sola lettura. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` - Utilizzare questa opzione per visualizzare l'ultima immagine snapshot creata nel gruppo di snapshot.
* `OLDEST` - Utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ").



 a| 
`readOnly`
 a| 
Questo parametro imposta il volume snapshot su sola lettura. Questo parametro è in realtà un booleano; tuttavia, nel contesto di questo comando, il valore booleano è sempre `TRUE`.

[NOTE]
====
Con `readOnly` parametro, i volumi snapshot non vengono creati.

====
|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.

L'identificatore di un'immagine snapshot ha due parti separate da due punti (:):

* Il nome del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera creare un volume di sola lettura denominato engData1 utilizzando l'immagine snapshot più recente in un gruppo di snapshot con il nome snapGroup1, utilizzare il seguente comando:

[listing]
----
create snapVolume userLabel="engData1" snapImageID="snapGroup1:newest" readOnly;
----


== Livello minimo del firmware

7.83
