---
permalink: commands-a-z/create-mapping-cgsnapvolume.html 
sidebar: sidebar 
keywords: create, consistency, group, snapshot, volume, map 
summary: Il comando create mapping cgSnapVolume crea un mapping logico da un volume snapshot di un gruppo di coerenza a un host o a un gruppo di host. 
---
= Creare il mapping del volume Snapshot del gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `create mapping cgSnapVolume` il comando crea un mapping logico da un volume snapshot di un gruppo di coerenza a un host o a un gruppo di host.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing, subs="+macros"]
----
create mapping cgSnapVolume=pass:quotes[_"snapVolumeName"_
(host="_hostName_" | hostGroup=("_hostGroupName_" | defaultGroup))]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`cgSnapVolume`
 a| 
Il nome del volume snapshot del gruppo di coerenza per il quale si desidera creare un mapping logico. Racchiudere il nome del volume snapshot del gruppo di coerenza tra virgolette doppie (" ").



 a| 
`host`
 a| 
Il nome di un host a cui si desidera creare un mapping logico. Racchiudere il nome host tra virgolette doppie (" ").



 a| 
`hostGroup`
 a| 
Il nome di un gruppo host a cui si desidera creare un mapping logico. Racchiudere il nome del gruppo di host tra virgolette doppie (" "). Se si utilizza `defaultGroup` parola chiave, non racchiuderla tra virgolette.

|===


== Note

Un host è un computer collegato all'array di storage che accede ai volumi sull'array di storage attraverso le porte host. È possibile definire mappature specifiche a un singolo host. È inoltre possibile assegnare l'host a un gruppo di host che condivide l'accesso a uno o più volumi.

Un gruppo di host è un elemento topologico opzionale che è possibile definire se si desidera designare una raccolta di host che condividono l'accesso agli stessi volumi. Il gruppo host è un'entità logica. Definire un gruppo di host solo se si dispone di due o più host che condividono l'accesso agli stessi volumi.



== Livello minimo del firmware

7.83
