---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: Il comando create VolumeGroup crea un gruppo di volumi a capacità libera o un gruppo di volumi con un volume quando si inserisce un set di dischi non assegnati. 
---
= Crea gruppo di volumi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `create volumeGroup` il comando crea un gruppo di volumi a capacità libera o un gruppo di volumi con un volume quando si inserisce un set di dischi non assegnati.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`drives`
 a| 
Le unità che si desidera assegnare al gruppo di volumi che si desidera creare. Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`raidLevel`
 a| 
Il livello RAID del gruppo di volumi che contiene il volume. I valori validi sono `0`, `1`, `3`, `5`, o. `6`.



 a| 
`userLabel`
 a| 
Il nome che si desidera assegnare al nuovo gruppo di volumi. Racchiudere il nome del gruppo di volumi tra virgolette doppie (" ").



 a| 
`driveMediaType`
 a| 
Il tipo di disco che si desidera utilizzare per il gruppo di volumi

È necessario utilizzare questo parametro quando si dispone di più tipi di dischi nell'array di storage.

Questi supporti sono validi:

* `HDD` -- utilizzare questa opzione se si dispone di dischi rigidi nel vassoio dell'unità
* `SSD` -- utilizzare questa opzione se si dispone di dischi a stato solido nel vassoio dell'unità
* `unknown` -- utilizzare questa opzione se non si è sicuri dei tipi di supporti presenti nel vassoio dell'unità
* `allMedia` -- utilizzare questa opzione se si desidera utilizzare tutti i tipi di supporti presenti nel vassoio dell'unità




 a| 
`driveType`
 a| 
Il tipo di disco che si desidera utilizzare nel gruppo di volumi. Non è possibile combinare tipi di unità.

È necessario utilizzare questo parametro quando si dispone di più di un tipo di disco nell'array di storage.

Questi tipi di unità sono validi:

* `SAS`
* `NVMe4K`


Se non si specifica un tipo di disco, il codice non verifica che le unità specificate siano di questo tipo.



 a| 
`trayLossProtect`
 a| 
L'impostazione di Imponi protezione perdita vassoio quando si crea il gruppo di volumi. Per applicare la protezione perdita vassoio, impostare questo parametro su `TRUE`. Il valore predefinito è `FALSE`.



 a| 
`drawerLossProtect`
 a| 
L'impostazione di Imponi protezione perdita cassetto quando si crea il gruppo di volumi. Per applicare la protezione perdita cassetto, impostare questo parametro su `TRUE`. Il valore predefinito è `FALSE`.



 a| 
`securityType`
 a| 
L'impostazione per specificare il livello di protezione durante la creazione dei gruppi di volumi e di tutti i volumi associati. Queste impostazioni sono valide:

* `none` -- il gruppo di volumi e i volumi non sono sicuri.
* `capable` -- il gruppo di volumi e i volumi sono in grado di impostare la protezione, ma la protezione non è stata attivata.
* `enabled` -- il gruppo di volumi e i volumi hanno attivato la protezione.




 a| 
`resourceProvisioningCapable`
 a| 
L'impostazione per specificare se le funzionalità di provisioning delle risorse sono attivate. Per disattivare il provisioning delle risorse, impostare questo parametro su `FALSE`. Il valore predefinito è `TRUE`.

|===


== Dischi e gruppi di volumi

Un gruppo di volumi è un insieme di dischi raggruppati logicamente dai controller dell'array di storage. Il numero di dischi in un gruppo di volumi è un limite del livello RAID e del firmware del controller. Quando si crea un gruppo di volumi, attenersi alle seguenti linee guida:

* A partire dalla versione del firmware 7.10, è possibile creare un gruppo di volumi vuoto in modo da riservare la capacità per un utilizzo successivo.
* Non è possibile combinare tipi di unità all'interno di un singolo gruppo di volumi.
* Non è possibile combinare dischi HDD e SSD in un singolo gruppo di volumi.
* Il numero massimo di dischi in un gruppo di volumi dipende dalle seguenti condizioni:
+
** Il tipo di controller
** Il livello RAID


* I livelli RAID includono: 0, 1, 3, 5 e 6 .
+
** Un gruppo di volumi con RAID livello 3, RAID livello 5 o RAID livello 6 non può avere più di 30 dischi.
** Un gruppo di volumi con livello RAID 6 deve avere un minimo di cinque dischi.
** Se un gruppo di volumi con RAID livello 1 dispone di quattro o più dischi, il software di gestione dello storage converte automaticamente il gruppo di volumi in un RAID livello 10, ovvero RAID livello 1 + RAID livello 0.


* Per attivare la protezione contro le perdite di vassoio/cassetto, fare riferimento alle seguenti tabelle per ulteriori criteri:


|===
| Livello | Criteri per la protezione dalla perdita dei vassoi | Numero minimo di vassoi richiesti 


 a| 
`Disk Pool`
 a| 
Il pool di dischi non contiene più di due dischi in un singolo vassoio
 a| 
6



 a| 
`RAID 6`
 a| 
Il gruppo di volumi non contiene più di due unità in un singolo vassoio
 a| 
3



 a| 
`RAID 3` oppure `RAID 5`
 a| 
Ciascuna unità del gruppo di volumi si trova in un vassoio separato
 a| 
3



 a| 
`RAID 1`
 a| 
Ogni disco di una coppia RAID 1 deve essere collocato in un vassoio separato
 a| 
2



 a| 
`RAID 0`
 a| 
Impossibile ottenere la protezione dalla perdita dei vassoi.
 a| 
Non applicabile

|===
|===
| Livello | Criteri per la protezione contro le perdite di cassetto | Numero minimo di cassetti richiesti 


 a| 
`Disk Pool`
 a| 
Il pool include dischi di tutti e cinque i cassetti e un numero uguale di dischi in ciascun cassetto. Un vassoio da 60 dischi può ottenere la protezione contro la perdita di cassetto quando il pool di dischi contiene 15, 20, 25, 30, 35, 40, 45, 50, 55 o 60 dischi.
 a| 
5



 a| 
`RAID 6`
 a| 
Il gruppo di volumi non contiene più di due dischi in un singolo cassetto.
 a| 
3



 a| 
`RAID 3` oppure `RAID 5`
 a| 
Ciascuna unità del gruppo di volumi si trova in un cassetto separato.
 a| 
3



 a| 
`RAID 1`
 a| 
Ogni disco di una coppia mirrorata deve essere collocato in un cassetto separato.
 a| 
2



 a| 
`RAID 0`
 a| 
Impossibile ottenere la protezione perdita cassetto.
 a| 
Non applicabile

|===


== Hot spare

Con i gruppi di volumi, una strategia preziosa per proteggere i dati consiste nell'assegnare le unità disponibili nell'array di storage come unità hot spare. Un hot spare è un disco, privo di dati, che agisce come standby nell'array di storage in caso di guasto di un disco in un gruppo di volumi RAID 1, RAID 3, RAID 5 o RAID 6. L'hot spare aggiunge un altro livello di ridondanza allo storage array.

In genere, i dischi hot spare devono avere capacità uguali o superiori alla capacità utilizzata sui dischi che stanno proteggendo. Le unità hot spare devono essere dello stesso tipo di supporto, dello stesso tipo di interfaccia e della stessa capacità delle unità che proteggono.

In caso di guasto di un disco nell'array di storage, il disco hot spare viene normalmente sostituito automaticamente per il disco guasto senza richiedere l'intervento dell'utente. Se è disponibile un hot spare in caso di guasto di un disco, il controller utilizza la parità dei dati di ridondanza per ricostruire i dati nell'hot spare. Il supporto per l'evacuazione dei dati consente inoltre di copiare i dati su un hot spare prima che il software contrassegni il disco "guasto".

Una volta sostituito fisicamente il disco guasto, è possibile utilizzare una delle seguenti opzioni per ripristinare i dati:

Una volta sostituito il disco guasto, i dati del disco hot spare vengono copiati nuovamente sul disco sostitutivo. Questa azione è chiamata copyback.

Se si designa l'unità hot spare come membro permanente di un gruppo di volumi, l'operazione copyback non è necessaria.

La disponibilità della protezione in caso di perdita dei vassoi e della protezione in caso di perdita dei cassetti per un gruppo di volumi dipende dalla posizione delle unità che compongono il gruppo di volumi. La protezione in caso di perdita dei vassoi e la protezione in caso di perdita dei cassetti potrebbero andare perse a causa di un disco guasto e della posizione dell'unità hot spare. Per assicurarsi che la protezione contro la perdita di vassoio e la protezione contro la perdita di cassetto non siano compromesse, è necessario sostituire un disco guasto per avviare il processo copyback.

Lo storage array seleziona automaticamente le unità compatibili con Data Assurance (da) per la copertura hot spare dei volumi abilitati da.

Assicurarsi di disporre di unità compatibili con da nell'array di storage per la copertura hot spare dei volumi abilitati da. Per ulteriori informazioni sulle unità compatibili con da, fare riferimento alla funzione Data Assurance.

I dischi con funzionalità sicure (FIPS e FDE) possono essere utilizzati come hot spare per dischi con funzionalità sicure e non sicure. I dischi non sicuri possono fornire copertura per altri dischi non sicuri e per dischi sicuri se il gruppo di volumi non dispone della protezione abilitata. Un gruppo di volumi FIPS può utilizzare solo un'unità FIPS come hot spare; tuttavia, è possibile utilizzare un hot spare FIPS per gruppi di volumi non sicuri, sicuri e abilitati alla protezione.

Se non si dispone di un hot spare, è comunque possibile sostituire un disco guasto mentre lo storage array è in funzione. Se l'unità fa parte di un gruppo di volumi RAID 1, RAID 3, RAID 5 o RAID 6, il controller utilizza la parità dei dati di ridondanza per ricostruire automaticamente i dati sull'unità sostitutiva. Questa azione è chiamata ricostruzione.



== Dimensione del segmento

Le dimensioni di un segmento determinano il numero di blocchi di dati che il controller scrive su un singolo disco di un volume prima di scrivere i dati sul disco successivo. Ogni blocco di dati memorizza 512 byte di dati. Un blocco di dati è l'unità di storage più piccola. La dimensione di un segmento determina il numero di blocchi di dati che contiene. Ad esempio, un segmento da 8 KB contiene 16 blocchi di dati. Un segmento da 64 KB contiene 128 blocchi di dati.

Quando si inserisce un valore per la dimensione del segmento, il valore viene controllato rispetto ai valori supportati forniti dal controller in fase di esecuzione. Se il valore immesso non è valido, il controller restituisce un elenco di valori validi. L'utilizzo di un singolo disco per una singola richiesta lascia disponibili altri dischi per supportare contemporaneamente altre richieste. Se il volume si trova in un ambiente in cui un singolo utente sta trasferendo grandi unità di dati (ad esempio, contenuti multimediali), le prestazioni vengono massimizzate quando una singola richiesta di trasferimento dati viene servita con una singola stripe di dati. (Una stripe di dati è la dimensione del segmento moltiplicata per il numero di dischi nel gruppo di volumi utilizzati per i trasferimenti di dati). In questo caso, vengono utilizzati più dischi per la stessa richiesta, ma a ciascun disco viene effettuato l'accesso una sola volta.

Per ottenere performance ottimali in un ambiente di storage di file system o database multiutente, impostare le dimensioni del segmento in modo da ridurre al minimo il numero di dischi necessari per soddisfare una richiesta di trasferimento dei dati.



== Suggerimento per l'utilizzo

[NOTE]
====
Non è necessario inserire un valore per `cacheReadPrefetch` o il `segmentSize` parametro. Se non si inserisce un valore, il firmware del controller utilizza `usageHint` parametro con `fileSystem` come valore predefinito. Immissione di un valore per `usageHint` e un valore per `cacheReadPrefetch` o un valore per `segmentSize` il parametro non causa alcun errore. Il valore immesso per `cacheReadPrefetch` o il `segmentSize` il parametro ha la priorità sul valore di `usageHint` parametro. Le impostazioni relative alle dimensioni dei segmenti e al prefetch di lettura della cache per i vari suggerimenti di utilizzo sono illustrate nella tabella seguente:

====
|===
| Suggerimento per l'utilizzo | Impostazione delle dimensioni dei segmenti | Impostazione del prefetch di lettura della cache dinamica 


 a| 
File system
 a| 
128 KB
 a| 
Attivato



 a| 
Database
 a| 
128 KB
 a| 
Attivato



 a| 
Multimediale
 a| 
256 KB
 a| 
Attivato

|===


== Prefetch di lettura della cache

Il prefetch di lettura della cache consente al controller di copiare ulteriori blocchi di dati nella cache, mentre il controller legge e copia i blocchi di dati richiesti dall'host dal disco nella cache. Questa azione aumenta la possibilità che una richiesta futura di dati possa essere soddisfatta dalla cache. Il prefetch di lettura della cache è importante per le applicazioni multimediali che utilizzano trasferimenti di dati sequenziali. Valori validi per `cacheReadPrefetch` i parametri sono `TRUE` oppure `FALSE`. L'impostazione predefinita è `TRUE`.



== Tipo di sicurezza

Utilizzare `securityType` parametro per specificare le impostazioni di sicurezza per lo storage array.

Prima di poter impostare `securityType` parametro a. `enabled`, è necessario creare una chiave di sicurezza dello storage array. Utilizzare `create storageArray securityKey` comando per creare una chiave di sicurezza dello storage array. Questi comandi sono correlati alla chiave di sicurezza:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Dischi sicuri

Le unità compatibili con la protezione possono essere dischi con crittografia completa del disco (FDE) o dischi FIPS (Federal Information Processing Standard). Utilizzare `secureDrives` parametro per specificare il tipo di dischi protetti da utilizzare. I valori che è possibile utilizzare sono `fips` e. `fde`.



== Gestione della data assurance

La funzione Data Assurance (da) aumenta l'integrità dei dati nell'intero sistema storage. DA consente all'array di storage di verificare la presenza di errori che potrebbero verificarsi quando i dati vengono spostati tra gli host e i dischi. Quando questa funzione è attivata, l'array di storage aggiunge i codici di controllo degli errori (noti anche come CRC (Cyclic Redundancy Checks) a ciascun blocco di dati del volume. Dopo lo spostamento di un blocco di dati, l'array di storage utilizza questi codici CRC per determinare se si sono verificati errori durante la trasmissione. I dati potenzialmente corrotti non vengono scritti su disco né restituiti all'host.

Se si desidera utilizzare la funzione da, iniziare con un pool o un gruppo di volumi che include solo dischi che supportano da. Quindi, creare volumi compatibili con da. Infine, mappare questi volumi con funzionalità da all'host utilizzando un'interfaccia i/o in grado di eseguire il da. Le interfacce i/o che supportano il da includono Fibre Channel, SAS e iSER su InfiniBand (iSCSI Extensions per RDMA/IB). DA non è supportato da iSCSI su Ethernet o da SRP su InfiniBand.

[NOTE]
====
Quando tutti i dischi sono compatibili con da, è possibile impostare `dataAssurance` parametro a. `enabled` E quindi utilizzare da con determinate operazioni. Ad esempio, è possibile creare un gruppo di volumi che includa dischi compatibili con da e quindi creare un volume all'interno di tale gruppo di volumi abilitato per da. Altre operazioni che utilizzano un volume abilitato da dispongono di opzioni per supportare la funzione da.

====
Se il `dataAssurance` il parametro è impostato su `enabled`, per i candidati ai volumi verranno considerati solo i dischi con data assurance; in caso contrario, verranno presi in considerazione sia i dischi con data assurance che quelli non con data assurance. Se sono disponibili solo dischi Data Assurance, il nuovo gruppo di volumi verrà creato utilizzando i dischi Data Assurance abilitati.



== Livello minimo del firmware

7.10

7.50 aggiunge `securityType` parametro.

7.60 aggiunge `drawerID` input dell'utente, il `driveMediaType` e il `drawerLossProtect` parametro.

7.75 aggiunge `dataAssurance` parametro.

8.63 aggiunge `resourceProvisioningCapable` parametro.
