---
permalink: commands-a-z/create-snapgroup.html 
sidebar: sidebar 
keywords: create, snapshot, group 
summary: Il comando create snapGroup crea un nuovo gruppo di snapshot e il volume di repository associato. 
---
= Creare un gruppo di snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `create snapGroup` il comando crea un nuovo gruppo di snapshot e il volume di repository associato.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Un gruppo di snapshot contiene una sequenza di immagini snapshot di un volume di base associato. Un gruppo di snapshot dispone di un volume di repository utilizzato per salvare i dati di tutte le immagini snapshot che fanno parte del gruppo di snapshot.

[NOTE]
====
Prima di creare un gruppo di snapshot, assicurarsi che sia disponibile un gruppo di volumi con capacità libera.

====


== Sintassi

[listing, subs="+macros"]
----
create snapGroup userLabel=pass:quotes[_"snapGroupName_" sourceVolume=_"volumeName"_]
[(repositoryVolume="repos_xxxx" |
repositoryVolume=(pass:quotes[_volumeGroupName_] [capacity=capacityValue]) |
repositoryVolume=(pass:quotes[_diskPoolName_] [capacity=capacityValue]))]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[rollbackPriority=(highest | high | medium | low | lowest)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]|
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapshotSchedule_)]]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`userLabel`
 a| 
Il nome che si desidera assegnare al nuovo gruppo di snapshot. Racchiudere l'identificatore del gruppo di snapshot tra virgolette doppie (" ").



 a| 
`sourceVolume`
 a| 
Il nome del volume che si desidera utilizzare come origine per le immagini snapshot. Racchiudere il nome del volume di origine tra virgolette doppie (" ").



 a| 
`repositoryVolume`
 a| 
Il nome del volume del repository che conterrà i dati modificati del gruppo di snapshot.

Sono disponibili due opzioni per definire il nome di un volume di repository:

* Utilizzare un volume repository esistente: Nome
* Creare un nuovo volume di repository quando si esegue questo comando


Il nome di un volume di repository esistente è composto da due parti:

* Il termine "repos"
* Identificatore numerico a quattro cifre assegnato dal software di gestione dello storage al nome del volume del repository


Racchiudere il nome del volume di repository esistente tra virgolette doppie (" ").

Se si desidera creare un nuovo volume di repository quando si esegue questo comando, è necessario immettere il nome di un gruppo di volumi o di un pool di dischi in cui si desidera creare il volume di repository. In alternativa, è anche possibile definire la capacità del volume di repository. Se si desidera definire la capacità, è possibile utilizzare i seguenti valori:

* Un valore intero che rappresenta una percentuale della capacità del volume di base
* Un valore di frazione decimale che rappresenta una percentuale della capacità del volume di base
* Una dimensione specifica per il volume di repository. Le dimensioni sono definite in unità di `bytes`, `KB`, `MB`, `GB`, o. `TB`.


Se non si utilizza l'opzione di capacità, il software di gestione dello storage imposta la capacità sul 20% della capacità del volume di base.

Quando si esegue questo comando, il software di gestione dello storage crea il volume di repository per il volume di snapshot.



 a| 
`repositoryFullPolicy`
 a| 
Definisce il modo in cui l'elaborazione dell'immagine snapshot continua se il volume del repository del gruppo di snapshot è pieno. È possibile scegliere di non eseguire le scritture i/o nel volume di base (`failBaseWrites`) o eliminare (eliminare) le immagini snapshot  `purgeSnapImages`) nel volume di repository. Il `purgeSnapImages` consente di eliminare le immagini snapshot meno recenti per liberare spazio. L'azione predefinita è `purgeSnapImages`.



 a| 
`rollBackPriority`
 a| 
Determina se le risorse di sistema devono essere allocate all'operazione di rollback a scapito delle prestazioni del sistema. Un valore di `high` Indica che l'operazione di rollback ha la priorità su tutti gli altri i/o host Un valore di `low` Indica che l'operazione di rollback deve essere eseguita con un impatto minimo sull'i/o host Il valore predefinito è `medium`.



 a| 
`repositoryFullLimit`
 a| 
La percentuale di capacità del repository alla quale viene visualizzato un avviso che indica che il volume del repository del gruppo di snapshot è quasi pieno. USA valori interi. Ad esempio, un valore di 70 significa 70%. Il valore predefinito è 75.



 a| 
`autoDeleteLimit`
 a| 
Ciascun gruppo di snapshot può essere configurato in modo da eseguire l'eliminazione automatica delle immagini snapshot per mantenere il numero totale di immagini snapshot nel gruppo di snapshot a un livello o al di sotto di quello designato. Quando questa opzione è attivata, ogni volta che viene creata una nuova immagine snapshot nel gruppo di snapshot, il sistema elimina automaticamente l'immagine snapshot meno recente nel gruppo per rispettare il valore limite. Questa azione libera la capacità del repository in modo che possa essere utilizzata per soddisfare i requisiti di copy-on-write per le immagini snapshot rimanenti.



 a| 
`enableSchedule`
 a| 
Utilizzare questo parametro per attivare o disattivare la possibilità di pianificare un'operazione di snapshot. Per attivare la pianificazione snapshot, impostare questo parametro su `TRUE`. Per disattivare la pianificazione snapshot, impostare questo parametro su `FALSE`.

|===


== Note

Ogni nome del gruppo di snapshot deve essere univoco. È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per l'etichetta utente. Le etichette dell'utente possono contenere un massimo di 30 caratteri.

Per creare un gruppo di snapshot, è necessario disporre di un volume di repository associato in cui memorizzare le immagini snapshot. È possibile utilizzare un volume di repository esistente o creare un nuovo volume di repository. È possibile creare il volume del repository quando si crea il gruppo di snapshot. Un volume di repository di gruppi di snapshot è un volume espandibile strutturato come un insieme concatenato di un massimo di 16 entità di volume standard. Inizialmente, un volume di repository espandibile ha un solo elemento. La capacità del volume di repository espandibile è esattamente quella del singolo elemento. È possibile aumentare la capacità di un volume di repository espandibile allegando volumi standard aggiuntivi. La capacità del volume del repository espandibile composito diventa quindi la somma delle capacità di tutti i volumi standard concatenati.

Un gruppo di snapshot dispone di un ordinamento rigoroso delle immagini snapshot in base al tempo di creazione di ciascuna immagine snapshot. Un'immagine snapshot creata dopo un'altra immagine snapshot è un _successore_ rispetto a quella di un'altra immagine snapshot. Un'immagine snapshot creata prima di un'altra immagine snapshot è un _predecessore_ rispetto all'altra.

Un volume di repository di gruppi di snapshot deve soddisfare un requisito di capacità minimo che corrisponde alla somma dei seguenti requisiti:

* 32 MB per supportare un overhead fisso per il gruppo di snapshot e per l'elaborazione copy-on-write.
* Capacità per l'elaborazione del rollback, pari a 1/5000esimo della capacità del volume di base.


La capacità minima viene utilizzata dal firmware del controller e dal software di gestione dello storage.

Quando si crea un gruppo di snapshot per la prima volta, non contiene immagini di snapshot. Quando si creano immagini snapshot, queste vengono aggiunte a un gruppo di snapshot. Utilizzare `create snapImage` comando per creare immagini snapshot e aggiungerle a un gruppo di snapshot.

Un gruppo di snapshot può avere uno dei seguenti stati:

* *Ottimale* -- il gruppo di snapshot funziona normalmente.
* *Full* -- il repository del gruppo di snapshot è pieno. Non è possibile eseguire ulteriori operazioni copy-on-write. Questo stato è possibile solo per i gruppi di snapshot che hanno il criterio Repository Full impostato su Fail base Scritture. Qualsiasi gruppo di snapshot in stato Full (completo) causa la pubblicazione di una condizione needs-Attention per l'array di storage.
* *Over Threshold* -- l'utilizzo del volume del repository del gruppo di snapshot è pari o superiore alla soglia di avviso. Qualsiasi gruppo di snapshot in questo stato causa la pubblicazione di una condizione di attenzione alle esigenze per l'array di storage.
* *Failed* -- il gruppo di snapshot ha riscontrato un problema che ha reso inutilizzabili tutte le immagini snapshot del gruppo di snapshot. Ad esempio, alcuni tipi di errori del volume del repository possono causare uno stato di errore. Per eseguire il ripristino dallo stato Failed (non riuscito), utilizzare `revive snapGroup` comando.


È possibile configurare ciascun gruppo di snapshot in modo che elimini automaticamente le immagini snapshot utilizzando `autoDeleteLimit` parametro. L'eliminazione automatica delle immagini Snapshot consente di evitare di dover cancellare manualmente le immagini non desiderate e di impedire la creazione di future immagini Snapshot perché il volume del repository è pieno. Quando si utilizza `autoDeleteLimit` parametro che fa sì che il software di gestione dello storage elimini automaticamente le immagini snapshot, a partire dalla meno recente. Il software di gestione dello storage elimina le immagini snapshot fino a raggiungere un numero di immagini snapshot pari al numero immesso con `autoDeleteLimit` parametro. Quando vengono aggiunte nuove immagini snapshot al volume del repository, il software di gestione dello storage elimina le immagini snapshot meno recenti fino a `autoDeleteLimit` il numero del parametro è stato raggiunto.

Il `enableSchedule` e il `schedule` il parametro consente di pianificare la creazione di immagini snapshot per un gruppo di snapshot. Utilizzando questi parametri, è possibile pianificare le snapshot giornalmente, settimanalmente o mensilmente (per giorno o per data). Il `enableSchedule` il parametro attiva o disattiva la possibilità di pianificare snapshot. Quando si attiva la pianificazione, si utilizza `schedule` parametro per definire quando si desidera che vengano eseguite le istantanee.

Questa tabella spiega come utilizzare le opzioni per `schedule` parametro:

|===
| Parametro | Descrizione 


 a| 
`schedule`
 a| 
Necessario per specificare i parametri di pianificazione.



 a| 
`immediate`
 a| 
Avviare immediatamente l'operazione. Questo elemento si esclude a vicenda con qualsiasi altro parametro di pianificazione.



 a| 
`enableSchedule`
 a| 
Quando è impostato su `true`, la pianificazione è attivata. Quando è impostato su `false`, la pianificazione è disattivata.

[NOTE]
====
L'impostazione predefinita è `false`.

====


 a| 
`startDate`
 a| 
Una data specifica in cui iniziare l'operazione. Il formato per l'immissione della data è MM:GG:AA. L'impostazione predefinita è la data corrente. Un esempio di questa opzione è `startDate=06:27:11`.



 a| 
`scheduleDay`
 a| 
Il giorno della settimana in cui iniziare l'operazione. Possono essere tutti o uno o più dei seguenti valori:

* `monday`
* `tuesday`
* `wednesday`
* `thursday`
* `friday`
* `saturday`
* `sunday`


[NOTE]
====
Racchiudere il valore tra parentesi. Ad esempio, `scheduleDay=(wednesday)`.

====
È possibile specificare più di un giorno racchiudendo i giorni in un singolo set di parentesi e separando ogni giorno con uno spazio. Ad esempio, `scheduleDay=(monday wednesday friday)`.

[NOTE]
====
Questo parametro non è compatibile con una pianificazione mensile.

====


 a| 
`startTime`
 a| 
L'ora del giorno in cui iniziare l'operazione. Il formato per l'immissione dell'ora è HH:MM, dove HH è l'ora e MM è il minuto che ha superato l'ora. Utilizza un orologio a 24 ore. Ad esempio, le 2:00 del pomeriggio sono le 14:00. Un esempio di questa opzione è `startTime=14:27`.



 a| 
`scheduleInterval`
 a| 
Un intervallo di tempo, espresso in minuti, minimo tra le operazioni. L'intervallo di pianificazione non deve superare le 1440 (24 ore) e deve essere un multiplo di 30.

Un esempio di questa opzione è `scheduleInterval=180`.



 a| 
`endDate`
 a| 
Una data specifica in cui interrompere l'operazione. Il formato per l'immissione della data è MM:GG:AA. Se non si desidera una data di fine, è possibile specificare `noEndDate`. Un esempio di questa opzione è `endDate=11:26:11`.



 a| 
`timesPerDay`
 a| 
Il numero di volte in cui eseguire l'operazione in un giorno. Un esempio di questa opzione è `timesPerDay=4`.



 a| 
`timezone`
 a| 
Specifica il fuso orario da utilizzare per la pianificazione. Può essere specificato in due modi:

* *GMT±HH:MM*
+
L'offset del fuso orario dal GMT. Esempio: `timezone=GMT-06:00`.

* *Stringa di testo*
+
La stringa di testo del fuso orario standard deve essere racchiusa tra virgolette. Esempio:``timezone="America/Chicago"``





 a| 
`scheduleDate`
 a| 
Il giorno del mese in cui eseguire l'operazione. I valori per i giorni sono numerici e nell'intervallo da 1 a 31.

[NOTE]
====
Questo parametro non è compatibile con una pianificazione settimanale.

====
Un esempio di `scheduleDate` l'opzione è `scheduleDate=("15")`.



 a| 
`month`
 a| 
Un mese specifico in cui eseguire l'operazione. I valori per i mesi sono:

* `jan` Gennaio
* `feb` - Febbraio
* `mar` - Marzo
* `apr` – Aprile
* `may` Maggio
* `jun` Giugno
* `jul` Luglio
* `aug` - Agosto
* `sep` Settembre
* `oct` Ottobre
* `nov` - Novembre
* `dec` Dicembre


[NOTE]
====
Racchiudere il valore tra parentesi. Ad esempio, `month=(jan)`.

====
È possibile specificare più di un mese racchiudendo i mesi in una singola serie di parentesi e separando ogni mese con uno spazio. Ad esempio, `month=(jan jul dec)`.

Utilizzare questo parametro con `scheduleDate` parametro per eseguire l'operazione in un giorno specifico del mese.

[NOTE]
====
Questo parametro non è compatibile con una pianificazione settimanale.

====
|===
Questa tabella spiega come utilizzare `timeZone` parametro:

|===
| Nome fuso orario | Offset GMT 


 a| 
`Etc/GMT+12`
 a| 
`GMT-12:00`



 a| 
`Etc/GMT+11`
 a| 
`GMT-11:00`



 a| 
`Pacific/Honolulu`
 a| 
`GMT-10:00`



 a| 
`America/Anchorage`
 a| 
`GMT-09:00`



 a| 
`America/Santa_Isabel`
 a| 
`GMT-08:00`



 a| 
`America/Los_Angeles`
 a| 
`GMT-08:00`



 a| 
`America/Phoenix`
 a| 
`GMT-07:00`



 a| 
`America/Chihuahua`
 a| 
`GMT-07:00`



 a| 
`America/Denver`
 a| 
`GMT-07:00`



 a| 
`America/Guatemala`
 a| 
`GMT-06:00`



 a| 
`America/Chicago`
 a| 
`GMT-06:00`



 a| 
`America/Mexico_City`
 a| 
`GMT-06:00`



 a| 
`America/Regina`
 a| 
`GMT-06:00`



 a| 
`America/Bogota`
 a| 
`GMT-05:00`



 a| 
`America/New_York`
 a| 
`GMT-05:00`



 a| 
`Etc/GMT+5`
 a| 
`GMT-05:00`



 a| 
`America/Caracas`
 a| 
`GMT-04:30`



 a| 
`America/Asuncion`
 a| 
`GMT-04:00`



 a| 
`America/Halifax`
 a| 
`GMT-04:00`



 a| 
`America/Cuiaba`
 a| 
`GMT-04:00`



 a| 
`America/La_Paz`
 a| 
`GMT-04:00`



 a| 
`America/Santiago`
 a| 
`GMT-04:00`



 a| 
`America/St_Johns`
 a| 
`GMT-03:30`



 a| 
`America/Sao_Paulo`
 a| 
`GMT-03:00`



 a| 
`America/Buenos_Aires`
 a| 
`GMT-03:00`



 a| 
`America/Cayenne`
 a| 
`GMT-03:00`



 a| 
`America/Godthab`
 a| 
`GMT-03:00`



 a| 
`America/Montevideo`
 a| 
`GMT-03:00`



 a| 
`Etc/GMT+2`
 a| 
`GMT-02:00`



 a| 
`Atlantic/Azores`
 a| 
`GMT-01:00`



 a| 
`Atlantic/Cape_Verde`
 a| 
`GMT-01:00`



 a| 
`Africa/Casablanca`
 a| 
`GMT`



 a| 
`Etc/GMT`
 a| 
`GMT`



 a| 
`Europe/London`
 a| 
`GMT`



 a| 
`Atlantic/Reykjavik`
 a| 
`GMT`



 a| 
`Europe/Berlin`
 a| 
`GMT+01:00`



 a| 
`Europe/Budapest`
 a| 
`GMT+01:00`



 a| 
`Europe/Paris`
 a| 
`GMT+01:00`



 a| 
`Europe/Warsaw`
 a| 
`GMT+01:00`



 a| 
`Africa/Lagos`
 a| 
`GMT+01:00`



 a| 
`Africa/Windhoek`
 a| 
`GMT+01:00`



 a| 
`Asia/Anman`
 a| 
`GMT+02:00`



 a| 
`Asia/Beirut`
 a| 
`GMT+02:00`



 a| 
`Africa/Cairo`
 a| 
`GMT+02:00`



 a| 
`Asia/Damascus`
 a| 
`GMT+02:00`



 a| 
`Africa/Johannesburg`
 a| 
`GMT+02:00`



 a| 
`Europe/Kiev`
 a| 
`GMT+02:00`



 a| 
`Asia/Jerusalem`
 a| 
`GMT+02:00`



 a| 
`Europe/Istanbul`
 a| 
`GMT+03:00`



 a| 
`Europe/Minsk`
 a| 
`GMT+02:00`



 a| 
`Asia/Baghdad`
 a| 
`GMT+03:00`



 a| 
`Asia/Riyadh`
 a| 
`GMT+03:00`



 a| 
`Africa/Nairobi`
 a| 
`GMT+03:00`



 a| 
`Asia/Tehran`
 a| 
`GMT+03:30`



 a| 
`Europe/Moscow`
 a| 
`GMT+04:00`



 a| 
`Asia/Dubai`
 a| 
`GMT+04:00`



 a| 
`Asia/Baku`
 a| 
`GMT+04:00`



 a| 
`Indian/Mauritius`
 a| 
`GMT+04:00`



 a| 
`Asia/Tbilisi`
 a| 
`GMT+04:00`



 a| 
`Asia/Yerevan`
 a| 
`GMT+04:00`



 a| 
`Asia/Kabul`
 a| 
`GMT+04:30`



 a| 
`Asia/Karachi`
 a| 
`GMT+05:00`



 a| 
`Asia//Tashkent`
 a| 
`GMT+05:00`



 a| 
`Asia/Calcutta`
 a| 
`GMT+05:30`



 a| 
`Asia/Colombo`
 a| 
`GMT+05:30`



 a| 
`Asia/Katmandu`
 a| 
`GMT+05:45`



 a| 
`Asia/Yekaterinburg`
 a| 
`GMT+06:00`



 a| 
`Asia/Almaty`
 a| 
`GMT+06:00`



 a| 
`Asia/Dhaka`
 a| 
`GMT+06:00`



 a| 
`Asia/Rangoon`
 a| 
`GMT+06:30`



 a| 
`Asia/Novosibirsk`
 a| 
`GMT+07:00`



 a| 
`Asia/Bangkok`
 a| 
`GMT+07:00`



 a| 
`Asia/Krasnoyarsk`
 a| 
`GMT+08:00`



 a| 
`Asia/Shanghai`
 a| 
`GMT+08:00`



 a| 
`Asia/Singapore`
 a| 
`GMT+08:00`



 a| 
`Australia/Perth`
 a| 
`GMT+08:00`



 a| 
`Asia/Taipei`
 a| 
`GMT+08:00`



 a| 
`Asia/Ulaanbaatar`
 a| 
`GMT+08:00`



 a| 
`Asia/Irkutsk`
 a| 
`GMT+09:00`



 a| 
`Asia/Tokyo`
 a| 
`GMT+09:00`



 a| 
`Asia/Seoul`
 a| 
`GMT+09:00`



 a| 
`Australia/Adelaide`
 a| 
`GMT+09:30`



 a| 
`Australia/Darwin`
 a| 
`GMT+09:30`



 a| 
`Asia/Yakutsk`
 a| 
`GMT+10:00`



 a| 
`Australia/Brisbane`
 a| 
`GMT+10:00`



 a| 
`Australia/Sydney`
 a| 
`GMT+10:00`



 a| 
`Pacific/Port Moresby`
 a| 
`GMT+10:00`



 a| 
`Australia/Hobart`
 a| 
`GMT+10:00`



 a| 
`Asia/Vladivostok`
 a| 
`GMT+11:00`



 a| 
`Pacific/Guadalcanal`
 a| 
`GMT+11:00`



 a| 
`Pacific/Auckland`
 a| 
`GMT+12:00`



 a| 
`Etc/GMT-12`
 a| 
`GMT+12:00`



 a| 
`Pacific/Fiji`
 a| 
`GMT+12:00`



 a| 
`Asia/Kamchatka`
 a| 
`GMT+12:00`



 a| 
`Pacific/Tongatapu`
 a| 
`GMT+13:00`

|===
La stringa di codice per la definizione di una pianificazione è simile a questi esempi:

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
Se si utilizza anche `scheduleInterval` il firmware sceglie tra `timesPerDay` e il `scheduleInterval` selezionando il valore più basso delle due opzioni. Il firmware calcola un valore intero per `scheduleInterval` dividendo 1440 per `scheduleInterval` valore dell'opzione impostato. Ad esempio, 1440/180 = 8. Il firmware confronta quindi `timesPerDay` valore intero con il calcolato `scheduleInterval` valore intero e utilizza il valore più piccolo.

Per rimuovere un programma, utilizzare `delete volume` con il `schedule` parametro. Il `delete volume` con il `schedule` il parametro elimina solo la pianificazione, non il volume di snapshot.



== Livello minimo del firmware

7.83

7.86 aggiunge `scheduleDate` e il `month` opzione.
