---
permalink: commands-a-z/create-cgsnapimage-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency group, snapshot image 
summary: Il comando create cgSnapImage consistencyGroup crea una nuova immagine snapshot per ogni volume di base che è membro di un gruppo di coerenza snapshot. 
---
= Crea un'immagine snapshot del gruppo di coerenza - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `create cgSnapImage consistencyGroup` il comando crea una nuova immagine snapshot per ogni volume di base che è membro di un gruppo di coerenza snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
create cgSnapImage consistencyGroup=pass:quotes[_"consistencyGroupName"_]
----


== Parametro

|===
| Parametro | Descrizione 


 a| 
`consistencyGroup`
 a| 
Il nome del gruppo di coerenza per il quale si stanno creando immagini snapshot. Racchiudere il nome del gruppo di coerenza tra virgolette doppie (" ").

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per i nomi. I nomi possono avere un massimo di 30 caratteri.

Il comando consente di svuotare e sospendere tutte le operazioni i/o in sospeso su ciascun volume di base membro del gruppo di coerenza prima di creare le immagini snapshot. Se la creazione di tutte le immagini snapshot non può essere completata correttamente per tutti i membri del gruppo di coerenza, l'operazione non riesce e non vengono create nuove immagini snapshot.

In genere, tutti i membri di un gruppo di coerenza snapshot hanno lo stesso numero di immagini snapshot. Quando si aggiunge un nuovo membro a un gruppo di coerenza snapshot, il nuovo membro non dispone delle immagini snapshot precedentemente create sui membri stabiliti del gruppo di coerenza snapshot. Non si tratta di una condizione di errore. Le richieste di eliminazione o rollback delle immagini snapshot che esistono solo su un sottoinsieme dei membri del gruppo di coerenza snapshot influiscono solo sui membri per i quali esiste effettivamente l'immagine snapshot specificata.



== Livello minimo del firmware

7.83
