---
permalink: commands-a-z/create-raid-volume-free-extent-based-select.html 
sidebar: sidebar 
keywords: create, raid, volume, free, extent, based, select 
summary: Il comando create volume crea un volume nello spazio libero di un gruppo di volumi. 
---
= Creazione di un volume RAID (selezione basata su estensione libera)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `create volume` il comando crea un volume nello spazio libero di un gruppo di volumi.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing, subs="+macros"]
----
create volume volumeGroup=pass:quotes[_"volumeGroupName"_
userLabel="_volumeName"_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[dataAssurance=(none | enabled)]
[blockSize=blockSizeValue]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome di un gruppo di volumi specifico nell'array di storage. Racchiudere il nome del gruppo di volumi tra virgolette doppie (" ").



 a| 
`userLabel`
 a| 
Il nome che si desidera assegnare al nuovo volume. Racchiudere il nuovo nome del volume tra virgolette doppie (" ").

[NOTE]
====
Questo parametro è obbligatorio.

====


 a| 
`freeCapacityArea`
 a| 
Il numero di indice dello spazio libero in un gruppo di volumi esistente che si desidera utilizzare per creare il nuovo volume. La capacità libera è definita come la capacità libera tra i volumi esistenti in un gruppo di volumi. Ad esempio, un gruppo di volumi potrebbe avere le seguenti aree: Volume 1, capacità libera, volume 2, capacità libera, volume 3, capacità libera. Per utilizzare la capacità libera seguente volume 2, inserire questo numero di indice:

`freeCapacityArea=2`

[NOTE]
====
Eseguire `show volumeGroup` comando per determinare se l'area di capacità libera esiste.

====
[NOTE]
====
Se questo parametro non viene specificato, il volume viene creato nell'area di capacità libera con il numero più basso e una capacità sufficiente per il volume.

====


 a| 
`capacity`
 a| 
La dimensione del volume che si sta aggiungendo all'array di storage. Le dimensioni sono definite in unità di `bytes`, `KB`, `MB`, `GB`, o. `TB`.



 a| 
`owner`
 a| 
Il controller proprietario del volume. Gli identificatori del controller validi sono `a` oppure `b`, dove `a` È il controller nello slot A, e. `b` Il controller si trova nello slot B. Se non si specifica un proprietario, il firmware del controller determina il proprietario.



 a| 
`cacheReadPrefetch`
 a| 
L'impostazione per attivare o disattivare il prefetch di lettura della cache. Per attivare il prefetch di lettura della cache, impostare questo parametro su `TRUE`. Per disattivare il prefetch di lettura della cache, impostare questo parametro su `FALSE`.



 a| 
`segmentSize`
 a| 
La quantità di dati (in KB) che il controller scrive su un singolo disco di un volume prima di scrivere i dati sul disco successivo. I valori validi sono `8`, `16`, `32`, `64`, `128`, `256`, o. `512`.



 a| 
`usageHint`
 a| 
Le impostazioni di `cacheReadPrefetch` e il `segmentSize` parametro da impostare come valori predefiniti. I valori predefiniti si basano sul tipico modello di utilizzo i/o dell'applicazione che utilizza il volume. I valori validi sono `fileSystem`, `dataBase`, o. `multiMedia`.



 a| 
`dssPreAllocate`
 a| 
L'impostazione per assicurarsi che la capacità di riserva venga allocata per le dimensioni future del segmento aumenta. Il valore predefinito è `TRUE`.



 a| 
`securityType`
 a| 
L'impostazione per specificare il livello di protezione durante la creazione dei gruppi di volumi e di tutti i volumi associati. Queste impostazioni sono valide:

`none` -- il gruppo di volumi e i volumi non sono sicuri.

`capable` -- il gruppo di volumi e i volumi sono in grado di impostare la protezione, ma la protezione non è stata attivata.

`enabled` -- il gruppo di volumi e i volumi hanno attivato la protezione.



 a| 
`mapping`
 a| 
Questo parametro consente di mappare il volume a un host. Se si desidera eseguire la mappatura in un secondo momento, impostare questo parametro su `none`. Se si desidera eseguire la mappatura ora, impostare questo parametro su `default`. Il volume viene mappato a tutti gli host che hanno accesso al pool di storage. Il valore predefinito è `none`.



 a| 
`blockSize`
 a| 
Questo parametro imposta la dimensione del blocco del volume da creare. Un valore pari a 0 o il parametro non impostato utilizza la dimensione predefinita del blocco.

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per i nomi. I nomi possono avere un massimo di 30 caratteri.

Il `owner` parameter (parametro): definisce il controller proprietario del volume. La proprietà preferita del controller di un volume è il controller che attualmente possiede il gruppo di volumi.

Se non si specifica una capacità utilizzando `capacity` parametro, viene utilizzata tutta la capacità disponibile nell'area di capacità libera del gruppo di volumi. Se non si specificano le unità di capacità, `bytes` viene utilizzato come valore predefinito.



== Dimensione del segmento

Le dimensioni di un segmento determinano il numero di blocchi di dati che il controller scrive su un singolo disco di un volume prima di scrivere i dati sul disco successivo. Ogni blocco di dati memorizza 512 byte di dati. Un blocco di dati è l'unità di storage più piccola. La dimensione di un segmento determina il numero di blocchi di dati che contiene. Ad esempio, un segmento da 8 KB contiene 16 blocchi di dati. Un segmento da 64 KB contiene 128 blocchi di dati.

Quando si inserisce un valore per la dimensione del segmento, il valore viene controllato rispetto ai valori supportati forniti dal controller in fase di esecuzione. Se il valore immesso non è valido, il controller restituisce un elenco di valori validi. L'utilizzo di un singolo disco per una singola richiesta lascia disponibili altri dischi per supportare contemporaneamente altre richieste. Se il volume si trova in un ambiente in cui un singolo utente sta trasferendo grandi unità di dati (ad esempio, contenuti multimediali), le prestazioni vengono massimizzate quando una singola richiesta di trasferimento dati viene servita con una singola stripe di dati. (Una stripe di dati è la dimensione del segmento moltiplicata per il numero di dischi nel gruppo di volumi utilizzati per i trasferimenti di dati). In questo caso, vengono utilizzati più dischi per la stessa richiesta, ma a ciascun disco viene effettuato l'accesso una sola volta.

Per ottenere performance ottimali in un ambiente di storage di file system o database multiutente, impostare le dimensioni del segmento in modo da ridurre al minimo il numero di dischi necessari per soddisfare una richiesta di trasferimento dei dati.



== Suggerimento per l'utilizzo

[NOTE]
====
Non è necessario inserire un valore per `cacheReadPrefetch` o il `segmentSize` parametro. Se non si inserisce un valore, il firmware del controller utilizza `usageHint` parametro con `fileSystem` come valore predefinito. Immissione di un valore per `usageHint` e un valore per `cacheReadPrefetch` o un valore per `segmentSize` il parametro non causa alcun errore. Il valore immesso per `cacheReadPrefetch` o il `segmentSize` il parametro ha la priorità sul valore di `usageHint` parametro. Le impostazioni relative alle dimensioni dei segmenti e al prefetch di lettura della cache per i vari suggerimenti di utilizzo sono illustrate nella tabella seguente:

====
|===
| Suggerimento per l'utilizzo | Impostazione delle dimensioni dei segmenti | Impostazione del prefetch di lettura della cache dinamica 


 a| 
File system
 a| 
128 KB
 a| 
Attivato



 a| 
Database
 a| 
128 KB
 a| 
Attivato



 a| 
Multimediale
 a| 
256 KB
 a| 
Attivato

|===


== Prefetch di lettura della cache

Il prefetch di lettura della cache consente al controller di copiare ulteriori blocchi di dati nella cache, mentre il controller legge e copia i blocchi di dati richiesti dall'host dal disco nella cache. Questa azione aumenta la possibilità che una richiesta futura di dati possa essere soddisfatta dalla cache. Il prefetch di lettura della cache è importante per le applicazioni multimediali che utilizzano trasferimenti di dati sequenziali. Valori validi per `cacheReadPrefetch` i parametri sono `TRUE` oppure `FALSE`. L'impostazione predefinita è `TRUE`.



== Tipo di sicurezza

Utilizzare `securityType` parametro per specificare le impostazioni di sicurezza per lo storage array.

Prima di poter impostare `securityType` parametro a. `enabled`, è necessario creare una chiave di sicurezza dello storage array. Utilizzare `create storageArray securityKey` comando per creare una chiave di sicurezza dello storage array. Questi comandi sono correlati alla chiave di sicurezza:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Livello minimo del firmware

7.10 aggiunge `dssPreAllocate` parametro.

7.50 aggiunge `securityType` parametro.

7.75 aggiunge `dataAssurance` parametro.

11.70 aggiunge `blockSize` parametro.
