---
permalink: commands-a-z/deactivate-storagearray-feature.html 
sidebar: sidebar 
keywords: deactivate, synchronous, mirror 
summary: Il comando Disattiva feature StorageArray disattiva la funzionalità di mirroring sincrono, disassembla il volume di repository mirror e rilascia il proprietario del controller del volume secondario. 
---
= Disattivare il mirroring sincrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `deactivate storageArray feature` il comando disattiva la funzionalità di mirroring sincrono, disassembla il volume di repository mirror e rilascia il proprietario del controller del volume secondario.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800 e E5700, a condizione che siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800 o E5700, è necessario avere il ruolo di amministratore dello storage o di amministratore del supporto.



== Contesto

La porta host del controller dedicata al volume secondario è disponibile per i trasferimenti di dati dell'host.

[NOTE]
====
Nelle versioni precedenti di questo comando, l'identificatore di funzione era `remoteMirror`. Questo identificatore di funzione non è più valido e viene sostituito da `syncMirror`.

====


== Sintassi

[source, cli]
----
deactivate storageArray feature=syncMirror
----


== Parametri

Nessuno.



== Livello minimo del firmware

6.10
