---
permalink: commands-a-z/delete-host.html 
sidebar: sidebar 
keywords: delete, host 
summary: Il comando delete host elimina uno o più host. 
---
= Elimina host - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete host` il comando elimina uno o più host.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Sintassi

[source, cli, subs="+macros"]
----
delete host pass:quotes[[_hostName_]]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`host`
 a| 
Il nome dell'host che si desidera eliminare. Racchiudere il nome host tra parentesi quadre ([ ]). Se il nome host contiene caratteri speciali, racchiudere il nome host tra virgolette doppie (" ") tra parentesi quadre.

|===


== Note

Un host è un computer collegato all'array di storage che accede ai volumi sull'array di storage attraverso le porte host sull'host.



== Livello minimo del firmware

5.20
