---
permalink: commands-a-z/delete-storagearray-trustedcertificate.html 
sidebar: sidebar 
keywords: delete, storage, array, trusted, certificate, command, remove, specified, installed, web, servers 
summary: 'Il comando delete StorageArray trustedCertificate rimuove i certificati CA installati dall"utente specificati dai server Web dell"array.' 
---
= Rimuovere i certificati CA attendibili installati
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `delete storageArray trustedCertificate` Il comando rimuove i certificati CA installati dall'utente specificati dai server Web dell'array.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Sintassi

[listing, subs="+macros"]
----

pass:quotes[delete storageArray trustedCertificate [(allUserInstalled |
aliases=("_alias1_" ... "_aliasN_]"))]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allUserInstalled`
 a| 
Consente di specificare la rimozione di tutti i certificati installati dall'utente.



 a| 
`aliases`
 a| 
Consente di specificare uno o più certificati CA da eliminare utilizzando i nomi alias o specificare tutti. Gli alias possono provenire da qualsiasi controller. Racchiudere tutti gli alias tra parentesi. Se si immettono più alias, separarli con uno spazio.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "delete storageArray trustedCertificate allUserInstalled;"

SMcli -n Array1 -c "delete storageArray trustedCertificate
   aliases=("19527b38-8d26-44e5-8c7f-5bf2ca9db7cf" "04bf744c-413a-49f1-9666-88d74189591d");"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
