---
permalink: commands-a-z/delete-volumegroup.html 
sidebar: sidebar 
keywords: delete, volume, group, command, entire, associated, support, role 
summary: Il comando delete VolumeGroup elimina un intero gruppo di volumi e i volumi associati. 
---
= Elimina gruppo di volumi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete volumeGroup` il comando elimina un intero gruppo di volumi e i volumi associati.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Contesto

[IMPORTANT]
====
*Possibili danni alla configurazione dello storage array* -- tutti i dati nel gruppo di volumi vengono persi non appena si esegue questo comando.

====


== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[delete volumeGroup [_volumeGroupName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi che si desidera eliminare. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.10
