---
permalink: commands-a-z/delete-auditlog.html 
sidebar: sidebar 
keywords: delete, audit, log, records 
summary: Il comando delete AuditLog elimina alcuni o tutti i record del registro di controllo. 
---
= Eliminare i record del registro di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `delete auditLog` il comando elimina alcuni o tutti i record del registro di controllo.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Sintassi

[listing, subs="+macros"]
----

delete auditLog (all | (endRecord=pass:quotes[_timestamp_ | endDate=_date_) |
 (retentionCount=_integer_))]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`all`
 a| 
Consente di eliminare tutti i record del registro di controllo.



 a| 
`endRecord`
 a| 
Consente di specificare il record finale da eliminare, a partire dal record meno recente. Il valore è il valore integrale che rappresenta la data e l'ora dell'ultimo record del registro di controllo, incluso.



 a| 
`endDate`
 a| 
Consente di specificare la data finale da eliminare, a partire dal record meno recente. Il formato per l'immissione della data è MM:GG:YY nel fuso orario del client.

[NOTE]
====
I record del registro di controllo, inclusa la data specificata, verranno cancellati.

====


 a| 
`retentionCount`
 a| 
Consente di specificare il numero dei record di registro di controllo più recenti da conservare.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "delete auditLog all;"

SMcli -n Array1 -c "delete auditLog endRecord=1493070393313;"

SMcli -n Array1 -c "delete auditLog endDate=04:30:17;"

SMcli -n Array1 -c "delete auditLog retentionCount=1000;"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
