---
permalink: commands-a-z/delete-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: delete, storage, array, key, management, certificate, command, remove, install, external 
summary: Il comando delete StorageArray keyManagementCertificate rimuove il certificato di gestione delle chiavi esterne installato dallo storage array. 
---
= Rimuovere il certificato di gestione delle chiavi esterne installato - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete storageArray keyManagementCertificate` il comando rimuove il certificato di gestione delle chiavi esterne installato dall'array di storage.



[[supported-arrays]]
== Array supportati

Questo comando si applica ai singoli array di storage E4000, E2800, E5700, EF600, EF300, EF50 e EF80. Non si applica agli array di storage E2700 o E5600.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Security Admin.



[[context]]
== Contesto

[NOTE]
====
Questo comando si applica solo alla gestione esterna delle chiavi.

====


[[syntax]]
== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[delete storageArray keyManagementCertificate certificateType=_certificate_type_]
----


[[parameters]]
== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`certificateType`
 a| 
Consente di specificare il tipo di certificato da eliminare. Le scelte valide sono: `client` oppure `server`.

|===


[[example]]
== Esempio

[listing]
----
 SMcli -n Array1 -c "delete storageArray keyManagementCertificate certificateType="client";"

   SMcli completed successfully.
----


[[minimum-firmware-level]]
== Livello minimo del firmware

8.40
