---
permalink: commands-a-z/delete-ssdcache.html 
sidebar: sidebar 
keywords: delete, cache, command, data, purged, array, support, role, parameter 
summary: Il comando delete ssdCache elimina la cache SSD. Tutti i dati nella cache SSD vengono eliminati. 
---
= Eliminare la cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete ssdCache` Il comando elimina la cache SSD. Tutti i dati nella cache SSD vengono eliminati.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di Support Admin.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[delete ssdCache [_ssdCacheName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`ssdCache`
 a| 
Il nome della cache SSD che si desidera eliminare. Racchiudere il nome della cache SSD tra parentesi quadre ([ ]). Se il nome della cache SSD contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome della cache SSD tra virgolette doppie (" ") tra parentesi quadre.

|===


== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
