---
permalink: commands-a-z/delete-hostgroup.html 
sidebar: sidebar 
keywords: delete, hostgroup, command, support, role 
summary: Il comando delete hostGroup elimina un gruppo di host. 
---
= Eliminare il gruppo di host
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `delete hostGroup` il comando elimina un gruppo di host.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
*Possibili danni alla configurazione dell'array di storage* -- questo comando elimina tutte le definizioni degli host nel gruppo di host.

====


== Sintassi

[listing, subs="+macros"]
----
pass:quotes[delete hostGroup [_hostGroupName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`hostGroup`
 a| 
Il nome del gruppo di host che si desidera eliminare. Racchiudere il nome del gruppo di host tra parentesi quadre ([ ]). Se il nome del gruppo di host contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome del gruppo di host tra virgolette doppie (" ") tra parentesi quadre.

|===


== Note

Un gruppo di host è un elemento topologico opzionale che consiste in un insieme di host che condividono l'accesso agli stessi volumi. Il gruppo host è un'entità logica.



== Livello minimo del firmware

5.20
