---
permalink: commands-a-z/delete-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: delete, storage, array, key, management, certificate, command, remove, install, external 
summary: Il comando delete StorageArray keyManagementCertificate rimuove il certificato di gestione delle chiavi esterne installato dallo storage array. 
---
= Rimuovere il certificato di gestione delle chiavi esterne installato
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `delete storageArray keyManagementCertificate` il comando rimuove il certificato di gestione delle chiavi esterne installato dall'array di storage.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Contesto

[NOTE]
====
Questo comando si applica solo alla gestione esterna delle chiavi.

====


== Sintassi

[listing, subs="+macros"]
----

pass:quotes[delete storageArray keyManagementCertificate certificateType=_certificate_type_]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`certificateType`
 a| 
Consente di specificare il tipo di certificato da eliminare. Le scelte valide sono: `client` oppure `server`.

|===


== Esempio

[listing]
----
 SMcli -n Array1 -c "delete storageArray keyManagementCertificate certificateType="client";"

   SMcli completed successfully.
----


== Livello minimo del firmware

8.40
