---
permalink: commands-a-z/delete-volumegroup.html 
sidebar: sidebar 
keywords: delete, volume, group, command, entire, associated, support, role 
summary: Il comando delete VolumeGroup elimina un intero gruppo di volumi e i volumi associati. 
---
= Elimina gruppo di volumi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete volumeGroup` il comando elimina un intero gruppo di volumi e i volumi associati.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[IMPORTANT]
====
*Possibili danni alla configurazione dello storage array* -- tutti i dati nel gruppo di volumi vengono persi non appena si esegue questo comando.

====


== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[delete volumeGroup [_volumeGroupName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi che si desidera eliminare. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.10
