---
permalink: commands-a-z/delete-hostgroup.html 
sidebar: sidebar 
keywords: delete, hostgroup, command, support, role 
summary: Il comando delete hostGroup elimina un gruppo di host. 
---
= Elimina gruppo host - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete hostGroup` il comando elimina un gruppo di host.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
*Possibili danni alla configurazione dell'array di storage* -- questo comando elimina tutte le definizioni degli host nel gruppo di host.

====


== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[delete hostGroup [_hostGroupName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`hostGroup`
 a| 
Il nome del gruppo di host che si desidera eliminare. Racchiudere il nome del gruppo di host tra parentesi quadre ([ ]). Se il nome del gruppo di host contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome del gruppo di host tra virgolette doppie (" ") tra parentesi quadre.

|===


== Note

Un gruppo di host è un elemento topologico opzionale che consiste in un insieme di host che condividono l'accesso agli stessi volumi. Il gruppo host è un'entità logica.



== Livello minimo del firmware

5.20
