---
permalink: commands-a-z/delete-storagearray-syslog.html 
sidebar: sidebar 
keywords: delete, storage, array, syslog, command, allow, delete, specified, configuration, storing, audit, logs, role 
summary: Il comando delete StorageArray syslog consente di eliminare la configurazione syslog specificata utilizzata per la memorizzazione dei registri di controllo. 
---
= Elimina la configurazione syslog dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `delete storageArray syslog` il comando consente di eliminare la configurazione syslog specificata utilizzata per la memorizzazione dei registri di controllo.



== Array supportati

Questo comando si applica ai singoli array di storage E4000, E2800, E5700, EF600, EF300, EF50 e EF80. Non si applica agli array di storage E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Security Admin.



== Sintassi

[source, cli]
----
delete storageArray syslog (allServers | id="<id>")
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allServers`
 a| 
Eliminare tutte le configurazioni syslog.



 a| 
`id`
 a| 
ID del server syslog da eliminare. L'ID è disponibile utilizzando `show storageArray syslog` comando.

|===


== Livello minimo del firmware

8.42
