---
permalink: commands-a-z/disable-storagearray.html 
sidebar: sidebar 
keywords: disable, storage, array, command, storage, feature 
summary: Il comando disable StorageArray disattiva la funzione di array di storage. 
---
= Disabilitare la funzionalità di array di archiviazione - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `disable storageArray` il comando disattiva una funzione di array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Eseguire `show storageArray` per visualizzare un elenco degli identificatori di funzionalità per tutte le funzionalità abilitate nell'array di storage.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[disable storageArray (featurePack | feature=_featureAttributeList_)]
----
Pass:quotes[il `_featureAttributeList_`] può essere uno o più di questi valori di attributo. Se si inseriscono più valori di attributo, separare i valori con uno spazio.

* `driveSecurity`




== Parametri

Nessuno.



== Livello minimo del firmware

8.20 aggiunge `driveSecurity` attribuire e rimuovere tutti gli altri attributi.
