---
permalink: commands-a-z/disable-storagearray.html 
sidebar: sidebar 
keywords: disable, storage, array, command, storage, feature 
summary: Il comando disable StorageArray disattiva la funzione di array di storage. 
---
= Disattivare la funzione di array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `disable storageArray` il comando disattiva una funzione di array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Eseguire `show storageArray` per visualizzare un elenco degli identificatori di funzionalità per tutte le funzionalità abilitate nell'array di storage.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[disable storageArray (featurePack | feature=_featureAttributeList_)]
----
Pass:quotes[il `_featureAttributeList_`] può essere uno o più di questi valori di attributo. Se si inseriscono più valori di attributo, separare i valori con uno spazio.

* `driveSecurity`




== Parametri

Nessuno.



== Livello minimo del firmware

8.20 aggiunge `driveSecurity` attribuire e rimuovere tutti gli altri attributi.
