---
permalink: commands-a-z/download-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: download, storage, array, management, key, certificate, command, intall, external, support, role 
summary: 'Il comando download StorageArray keyManagementCertificate installa i certificati di gestione delle chiavi esterne sull"array di storage.' 
---
= Installare il certificato di gestione delle chiavi esterne dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `download storageArray keyManagementCertificate` il comando installa i certificati di gestione delle chiavi esterne sull'array di storage.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Contesto

[NOTE]
====
Questo comando si applica solo alla gestione esterna delle chiavi.

====


== Sintassi

[listing, subs="+macros"]
----

pass:quotes[download storageArray keyManagementClientCertificate certificateType=(client|server) file="_filename_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`certificateType`
 a| 
Consente di specificare il tipo di file del certificato. Le scelte valide sono `client` oppure `server`.



 a| 
`file`
 a| 
Consente di specificare il certificato firmato dal client o il certificato CA principale/intermedio del server. Il file deve essere in formato PEM/DER.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "download storageArray keyManagementClientCertificate certificateType=client
   file="C:\serverSignedKeyMgmtClientCert.cer";"


SMcli completed successfully.
----


== Livello minimo del firmware

8.40
