---
permalink: commands-a-z/download-controller-arraymanagementservercertificate.html 
sidebar: sidebar 
keywords: download, controller, array, management, server, certificate, command, install 
summary: Il comando download controller arrayManagementServerCertificate installa il certificato del server sul controller. 
---
= Installare il certificato firmato dal server
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `download controller arrayManagementServerCertificate` il comando installa il certificato del server sul controller.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Contesto

Eseguire questa azione per ciascun controller utilizzando il certificato firmato applicabile al controller. Il certificato firmato deve includere i nomi IP/DNS del controller.



== Sintassi

[listing, subs="+macros"]
----

download controller [(a|b)] pass:quotes[arrayManagementServerCertificate file="_filename_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Consente all'utente di specificare il controller per cui si desidera installare il certificato firmato dal server. Gli identificatori di controller validi sono a o b, dove a è il controller nello slot A e b è il controller nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]).



 a| 
`file`
 a| 
Consente all'utente di specificare il percorso del file e il nome del file che contiene il certificato firmato. Le estensioni accettabili sono .cer, .crt, .der.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "download controller [a] arrayManagementServerCertificate
   file="C:\serverSignedCertificateA.cer";"

SMcli -n Array1 -c "download controller [b] arrayManagementServerCertificate
   file="C:\serverSignedCertificateB.cer";"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
