---
permalink: commands-a-z/enable-controller-datatransfer.html 
sidebar: sidebar 
keywords: enable, controller, datatransfer, command, revive, quiesced, running, diagnostics, role, syntax, parameter, firmware level 
summary: 'Il comando enable controller DataTransfer riattiva un controller che è stato interrotto durante l"esecuzione della diagnostica.' 
---
= Abilitare il trasferimento dei dati del controller
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `enable controller dataTransfer` command consente di ripristinare un controller che è stato messo in stato di quiescenza durante l'esecuzione della diagnostica.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing]
----
enable controller [(a|b)] dataTransfer
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Il controller che si desidera ripristinare. Gli identificatori del controller validi sono `a` oppure `b`, dove `a` È il controller nello slot A, e. `b` Il controller si trova nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]). Se non si specifica un controller, il software di gestione dello storage restituisce un errore di sintassi.

|===


== Livello minimo del firmware

6.10
