---
permalink: commands-a-z/enable-diskpool-security.html 
sidebar: sidebar 
keywords: enable, diskpool, security, command, convert, non secure, diskpool, support, arrays, role, context 
summary: Il comando enable diskPool Security converte un pool di dischi non sicuro in un pool di dischi sicuro. 
---
= Abilitare la sicurezza del pool di dischi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `enable diskPool security` il comando converte un pool di dischi non sicuro in un pool di dischi sicuro.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Tutte le unità che compongono il pool di dischi devono essere sicure.

====


== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[enable diskPool [_diskPoolName_]] security
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`diskPool`
 a| 
Il nome del pool di dischi che si desidera inserire nello stato Security Enabled (protezione abilitata). Racchiudere l'identificatore del pool di dischi tra parentesi quadre ([ ]).

|===


== Note

Ciascun nome del pool di dischi deve essere univoco. È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per l'etichetta utente. Le etichette dell'utente possono contenere un massimo di 30 caratteri.



== Livello minimo del firmware

7.83
