---
permalink: commands-a-z/reduce-disk-pool-capacity.html 
sidebar: sidebar 
keywords: reduce, disk pool, capacity 
summary: Il comando set diskPool riduce la capacità del pool di dischi rimuovendo logicamente i dischi dal pool. 
---
= Ridurre la capacità del pool di dischi
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `set diskPool` il comando riduce la capacità del pool di dischi rimuovendo logicamente le unità dal pool.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Questo comando utilizza la funzione DCR (Dynamic Capacity Reduction), che consente di rimuovere le unità selezionate da un pool di dischi e riutilizzare le unità rimosse in base alle necessità.

Il numero massimo di unità che è possibile rimuovere da un pool di dischi in una singola operazione DCR è 60. Non è possibile ridurre il pool di dischi al di sotto delle dimensioni minime del pool di dischi.



== Sintassi

[listing, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
removeDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1
... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_])
----


== Parametro

|===
| Parametro | Descrizione 


 a| 
`diskPool`
 a| 
Il nome del pool di dischi per il quale si desidera ridurre la capacità. Racchiudere il nome del pool di dischi tra parentesi quadre ([ ]).



 a| 
`removeDrives`
 a| 
Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).

|===


== Note

Ciascun nome del pool di dischi deve essere univoco. È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per l'etichetta utente. Le etichette dell'utente possono contenere un massimo di 30 caratteri.

È possibile rimuovere le unità selezionate da un pool di dischi se è necessario creare un gruppo separato o rimuovere la capacità non necessaria dall'array di storage. I dischi rimossi diventano dischi non assegnati e i dati presenti su di essi vengono ridistribuiti tra i dischi rimanenti nel pool di dischi. La capacità del pool di dischi viene ridotta dalla capacità dei dischi rimossi. La rimozione delle unità da un pool di dischi viene sempre eseguita come attività in background e i volumi rimangono completamente accessibili durante questa operazione. L'avanzamento dell'operazione di rimozione viene riportato come parte dello stato delle operazioni a esecuzione prolungata.

Questo comando non riesce se non c'è sufficiente capacità libera sulle unità che rimangono nel pool di dischi per memorizzare tutti i dati che erano sulle unità rimosse dal pool di dischi. La capacità di riserva nel pool di dischi potrebbe essere utilizzata per memorizzare i dati presenti sulle unità rimosse dal pool di dischi. Tuttavia, se la capacità di riserva scende al di sotto della soglia critica, un evento critico viene scritto nel registro eventi principale.

La riduzione delle dimensioni del pool di dischi potrebbe ridurre la capacità di riserva necessaria. In alcuni casi, per ridurre la probabilità che questo comando non funzioni, ridurre la capacità di riserva prima di eseguire questo comando per aumentare la quantità di spazio disponibile per i dati del pool di dischi.

Il firmware del controller determina il numero di dischi che è possibile rimuovere ed è quindi possibile selezionare le unità specifiche da rimuovere. Il firmware del controller basa il conteggio sulla quantità di spazio libero necessaria per ridistribuire i dati tra i dischi rimanenti senza consumare alcuna capacità riservata alle ricostruzioni. Se la capacità libera del pool di dischi è già inferiore alla quantità di unità di ricostruzione riservata, il controller non consente l'avvio di un'operazione DCR.

Un'operazione DCR potrebbe comportare il superamento di una o di entrambe le soglie di utilizzo del pool da parte della capacità configurata. In tal caso, vengono emessi avvisi di soglia normali.



== Livello minimo del firmware

8.10
