---
permalink: commands-a-z/remove-volumecopy-target.html 
sidebar: sidebar 
keywords: remove, volume, copy 
summary: Il comando di destinazione Remove VolumeCopy rimuove una coppia di copie del volume. 
---
= Rimuovere la copia del volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `remove volumeCopy target` il comando rimuove una coppia di copie del volume.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Questo comando è valido per le coppie di copie di volumi snapshot.

[NOTE]
====
Con la versione del firmware 7.83 di `copyType=(online | offline)` il parametro non viene più utilizzato.

====


== Sintassi

[listing, subs="+macros"]
----
remove volumeCopy target pass:quotes[[_targetName_]] [source pass:quotes[[_sourceName_]]]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`target`
 a| 
Il nome del volume di destinazione che si desidera rimuovere. Racchiudere il nome del volume di destinazione tra parentesi quadre ([ ]). Se il nome del volume di destinazione contiene caratteri speciali o è composto solo da numeri, racchiudere il nome del volume di destinazione tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`source`
 a| 
Il nome del volume di origine che si desidera rimuovere. Racchiudere il nome del volume di origine tra parentesi quadre ([ ]). Se il nome del volume di origine ha caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome del volume di origine tra virgolette doppie (" ") tra parentesi quadre.

|===


== Livello minimo del firmware

5.40

7.83 rimuove `copyType=(online | offline)` parametro.
