---
permalink: commands-a-z/remove-drives-from-ssd-cache.html 
sidebar: sidebar 
keywords: remove, drives, ssd, cache 
summary: 'Il comando set ssdCache riduce la capacità della cache SSD rimuovendo i dischi a stato solido (SSD).' 
---
= Rimuovere le unità dalla cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set ssdCache` Il comando riduce la capacità della cache SSD rimuovendo i dischi a stato solido (SSD).



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di Support Admin.



== Sintassi

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]
removeDrives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`ssdCache`
 a| 
Il nome della cache SSD da cui si desidera rimuovere gli SSD. Racchiudere il nome della cache SSD tra parentesi quadre ([ ]). Se il nome della cache SSD contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome della cache SSD tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`removeDrives`
 a| 
Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).

|===


== Note

Non è possibile rimuovere tutti gli SSD dalla cache SSD utilizzando questo comando; almeno un SSD deve rimanere nella cache SSD. Se si desidera rimuovere completamente la cache SSD, utilizzare `delete ssdCache` comando invece.



== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
