---
permalink: commands-a-z/remove-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: remove, incomplete, asynchronous, mirror, pair, group 
summary: 'Il comando remove asyncMirrorGroup rimuove un volume di coppia di mirroring orfano sull"array di storage.' 
---
= Rimuovere la coppia di mirroring asincrono incompleta dal gruppo di mirror asincrono
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `remove asyncMirrorGroup` il comando rimuove un volume di coppia di mirroring orfano sull'array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E2700, E5600, E2800 e E5700, Finché tutti i pacchetti SMcli sono installati.



== Ruoli

Per eseguire questo comando su uno storage array E2800 o E5700, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Un volume di coppia di mirroring orfano esiste quando un volume membro in un gruppo di mirror asincrono è stato rimosso da un lato del gruppo di mirror asincrono (lato primario o lato secondario) ma non dall'altro lato.

I volumi di coppia di mirroring orfani vengono rilevati quando viene ripristinata la comunicazione tra controller e i due lati della configurazione di mirroring riconciliano i parametri di mirroring.

Utilizzare questo comando quando la relazione di mirroring viene rimossa correttamente sull'array di storage locale o remoto, ma non può essere rimossa sull'array di storage corrispondente a causa di un problema di comunicazione.



== Sintassi

[listing, subs="+macros"]
----
remove asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
incompleteMirror volume=pass:quotes[_"volumeName"_]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`asyncMirrorGroup`
 a| 
Il nome del gruppo di mirror asincrono che contiene il volume orfano che si desidera rimuovere. Racchiudere il nome del gruppo mirror asincrono tra virgolette doppie (" ") tra parentesi quadre ([ ]).



 a| 
`volume`
 a| 
Il nome del volume orfano che si desidera rimuovere dal gruppo di mirror asincrono. Racchiudere il nome del volume tra virgolette doppie (" ").

|===


== Livello minimo del firmware

7.84
