---
permalink: commands-a-z/remove-volume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: remove, volume, asynchronous, mirror, group 
summary: Il comando remove volume asyncMirrorGroup rimuove un volume membro da un gruppo di mirror asincrono esistente. 
---
= Rimuovi volume dal gruppo mirror asincrono - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `remove volume asyncMirrorGroup` il comando rimuove un volume membro da un gruppo mirror asincrono esistente.



[[supported-arrays]]
== Array supportati

Questo comando si applica a qualsiasi array di storage, inclusi E4000, E2700, E5600, E2800, E5700, EF600 ed EF300, a condizione che tutti i pacchetti SMcli siano installati.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600 o EF300, devi avere il ruolo Storage Admin.



[[context]]
== Contesto

Facoltativamente, è possibile eliminare i membri del volume del repository dal gruppo di mirror asincrono.

Questo comando è valido solo sull'array di storage locale che contiene il gruppo mirror asincrono di cui si desidera rimuovere il volume membro.



[[syntax]]
== Sintassi

[source, cli, subs="+macros"]
----
remove volume pass:quotes[[_"volumeName"_]] asyncMirrorGroup=pass:quotes[_"asyncMirrorGroupName"_]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


[[parameters]]
== Parametri

|===
| Parametro | Descrizione 


 a| 
`volume`
 a| 
Il nome del volume specifico che si desidera rimuovere dal gruppo di mirror asincrono. Racchiudere il nome del volume tra virgolette doppie (" ") tra parentesi quadre ([ ]).



 a| 
`asyncMirrorGroup`
 a| 
Il nome del gruppo di mirror asincrono che contiene il volume membro che si desidera rimuovere. Racchiudere il nome del gruppo mirror asincrono tra virgolette doppie (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Determina se rimuovere tutti i membri del repository dal gruppo di mirror asincrono.

|===


[[minimum-firmware-level]]
== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
