---
permalink: commands-a-z/rename-ssd-cache.html 
sidebar: sidebar 
keywords: rename, ssd, cache 
summary: Il comando set ssdCache modifica il nome della cache SSD. 
---
= Rinominare la cache SSD - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set ssdCache` Il comando modifica il nome della cache SSD.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di Support Admin.



== Sintassi

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_old_ssdCacheName_]] userLabel=pass:quotes[_"new_ssdCacheName_"]
----


== Parametro

|===
| Parametro | Descrizione 


 a| 
`ssdCache`
 a| 
Il nome della cache SSD che si desidera rinominare. Racchiudere il nome della cache SSD tra parentesi quadre ([ ]). Se il nome della cache SSD contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome della cache SSD tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`userLabel`
 a| 
Il nuovo nome della cache SSD. Racchiudere il nome tra virgolette doppie (" "). È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per l'identificatore. Gli identificatori possono avere un massimo di 30 caratteri.

|===


== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
