---
permalink: commands-a-z/repair-volume-parity.html 
sidebar: sidebar 
keywords: repair, volume, parity 
summary: Il comando di riparazione della parità del volume corregge gli errori di parità su un volume. 
---
= Riparare la parità del volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `repair volume parity` il comando corregge gli errori di parità su un volume.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[CAUTION]
====
Se la parità del volume e i dati del volume non corrispondono, i dati del volume potrebbero essere difettosi piuttosto che la parità del volume. La riparazione della parità del volume elimina la possibilità di riparare i dati del volume difettosi, se necessario.

====


== Sintassi

[listing, subs="+macros"]
----
repair volume pass:quotes[[_volumeName_]] parity
parityErrorFile=pass:quotes[_"filename"_]
[verbose=(TRUE | FALSE)]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`volume`
 a| 
Il nome del volume per il quale si sta riparando la parità. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiudere il nome del volume tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`parityErrorFile`
 a| 
Il percorso del file e il nome del file che contiene le informazioni sull'errore di parità utilizzate per correggere gli errori. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\sup\parfile.txt"`

[NOTE]
====
R `parityErrorFile` è il risultato di un precedente `check volume parity` operazione.

====


 a| 
`verbose`
 a| 
L'impostazione per acquisire i dettagli di avanzamento, ad esempio la percentuale di completamento, e mostrare le informazioni durante la riparazione della parità del volume. Per acquisire i dettagli di avanzamento, impostare questo parametro su `TRUE`. Per impedire l'acquisizione dei dettagli di avanzamento, impostare questo parametro su `FALSE`.

|===


== Livello minimo del firmware

6.10
