---
permalink: commands-a-z/replace-drive-replacementdrive.html 
sidebar: sidebar 
keywords: replace, drive 
summary: Il comando replace drive replacementDrive sostituisce un disco in un gruppo di volumi. 
---
= Sostituire l'unità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `replace drive replacementDrive` il comando sostituisce un disco in un gruppo di volumi.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

La sostituzione di un disco in un gruppo di volumi ridefinisce la composizione di un gruppo di volumi. È possibile utilizzare questo comando per sostituire un disco con un disco non assegnato o con un hot spare completamente integrato.



== Sintassi

[source, cli]
----
replace (drive \[trayID,[drawerID,]slotID\] \| drives\[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\]
 | <"wwID">)
replacementDrive=trayID,drawerID,slotID
[copyDrive][failDrive]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`drive`
 a| 
Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`drive`
 a| 
Il WWID (World Wide Identifier) dell'unità che si desidera sostituire. Racchiudere il WWID tra virgolette doppie (" ") all'interno di parentesi angolari (< >).



 a| 
`replacementDrive`
 a| 
La posizione dell'unità che si desidera utilizzare per la sostituzione. Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`. I valori ID slot sono `1` a. `24`.

|===


== Note

Il `drive` il parametro supporta sia i vassoi per dischi ad alta capacità che quelli a bassa capacità. Un vassoio per dischi ad alta capacità dispone di cassetti che trattengono le unità. I cassetti scorrono fuori dal vassoio dell'unità per consentire l'accesso alle unità. Un vassoio per unità a bassa capacità non dispone di cassetti. Per un vassoio dell'unità ad alta capacità, è necessario specificare l'identificativo (ID) del vassoio dell'unità, l'ID del cassetto e l'ID dello slot in cui si trova l'unità. Per un vassoio dell'unità a bassa capacità, è necessario specificare solo l'ID del vassoio dell'unità e l'ID dello slot in cui si trova un'unità. Per un vassoio dell'unità a bassa capacità, un metodo alternativo per identificare una posizione per un'unità consiste nel specificare l'ID del vassoio dell'unità, impostare l'ID del cassetto su `0`E specificare l'ID dello slot in cui si trova un'unità.



== Livello minimo del firmware

7.10

7.60 aggiunge `_drawerID_` input dell'utente.
