---
permalink: commands-a-z/reset-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: reset, installed, signed, certificate 
summary: Il comando reset controller arrayManagementSignedCertificate ripristina il certificato firmato installato e i certificati root/intermedi sul controller. Tutti i certificati root e intermedi e tutti i certificati firmati verranno sostituiti da un singolo certificato autofirmato. 
---
= Ripristinare il certificato firmato installato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `reset controller arrayManagementSignedCertificate` il comando ripristina il certificato firmato installato e i certificati root/intermedi sul controller. Tutti i certificati root e intermedi e tutti i certificati firmati verranno sostituiti da un singolo certificato autofirmato.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Sintassi

[source, cli]
----
reset controller [(a|b)] arrayManagementSignedCertificate
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Consente all'utente di specificare il controller su cui si desidera recuperare i certificati root/intermedi. Gli identificatori di controller validi sono a o b, dove a è il controller nello slot A e b è il controller nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]).

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "reset controller [a] arrayManagementSignedCertificate;"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
