---
permalink: commands-a-z/reset-storagearray-socbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, soc, baseline 
summary: 'Il comando reset StorageArray SOCBaseline ripristina la linea di base per tutti i dispositivi switch-on-a-chip (SOC) a cui si accede attraverso i controller.' 
---
= Reimposta la baseline SOC dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `reset storageArray SOCBaseline` Command ripristina la linea di base per tutti i dispositivi switch-on-a-chip (SOC) a cui si accede attraverso i controller.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Questo comando ripristina la linea di base impostando tutti i conteggi SOC su 0. Questo comando è valido solo per i dispositivi Fibre Channel in una topologia ad anello arbitrato.



== Sintassi

[source, cli]
----
reset storageArray SOCBaseline
----


== Parametri

Nessuno.



== Livello minimo del firmware

6.16
