---
permalink: commands-a-z/reset-storagearray-iserstatsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, iser, baseline 
summary: Il comando reset StorageArray iserStatsBaseline reimposta la linea di base iSER su 0 per lo storage array. 
---
= Ripristinare la linea di base iSER dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `reset storageArray iserStatsBaseline` Il comando ripristina la linea di base iSER su 0 per l'array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E2700, E5600, E2800 ed E5700, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E2800 o E5700, è necessario disporre del ruolo di amministratore dello storage.

[NOTE]
====
Questo comando è obsoleto e viene sostituito da xref:reset-storagearray-hostportstatisticsbaseline.adoc[Ripristinare la baseline delle statistiche della porta host dell'array di storage] comando.

====


== Sintassi

[listing]
----
reset storageArray iserStatsBaseline
----


== Parametri

Nessuno.



== Note

Questo comando non ripristina effettivamente i conteggi raw mantenuti nell'hardware e nel firmware. Al contrario, il firmware crea un'istantanea dei valori correnti del contatore e utilizza questi valori per segnalare le differenze nei conteggi quando le statistiche vengono recuperate. Il nuovo tempo di riferimento viene applicato a entrambi i controller in modo che i conteggi dei controller siano sincronizzati l'uno con l'altro. Se un controller viene reimpostato senza che l'altro controller venga reimpostato, i contatori non vengono più sincronizzati. Il client si rende conto che i controller non sono sincronizzati perché i dati di timestamp riportati insieme alle statistiche non sono gli stessi per entrambi i controller.



== Livello minimo del firmware

8.20

8.41 questo comando è obsoleto.
