---
permalink: commands-a-z/reset-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: reset, installed, signed, certificate 
summary: Il comando reset controller arrayManagementSignedCertificate ripristina il certificato firmato installato e i certificati root/intermedi sul controller. Tutti i certificati root e intermedi e tutti i certificati firmati verranno sostituiti da un singolo certificato autofirmato. 
---
= Reimposta il certificato firmato installato - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `reset controller arrayManagementSignedCertificate` il comando ripristina il certificato firmato installato e i certificati root/intermedi sul controller. Tutti i certificati root e intermedi e tutti i certificati firmati verranno sostituiti da un singolo certificato autofirmato.



== Array supportati

Questo comando si applica ai singoli array di storage E4000, E2800, E5700, EF600, EF300, EF50 e EF80. Non si applica agli array di storage E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Security Admin.



== Sintassi

[source, cli]
----
reset controller [(a|b)] arrayManagementSignedCertificate
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Consente all'utente di specificare il controller su cui si desidera recuperare i certificati root/intermedi. Gli identificatori di controller validi sono a o b, dove a è il controller nello slot A e b è il controller nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]).

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "reset controller [a] arrayManagementSignedCertificate;"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
