---
permalink: commands-a-z/reset-storagearray-sasphybaseline.html 
sidebar: sidebar 
keywords: reset, storage array, sas, phy, baseline 
summary: 'Il comando RESET StorageArray SASPHYBaseline ripristina la linea di base SAS Physical Layer (SAS PHY) per tutti i dispositivi e rimuove l"elenco degli errori dal file .csv.' 
---
= Reimposta la baseline PHY SAS dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `reset storageArray SASPHYBaseline` Il comando ripristina la linea di base SAS Physical Layer (SAS PHY) per tutti i dispositivi e rimuove l'elenco degli errori da `.csv` file.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Il `.csv` il file viene generato quando si esegue `save storageArray SASPHYCounts` comando.

[NOTE]
====
La versione precedente di `reset storageArray SASPHYBaseline` il comando ha cancellato i conteggi degli errori per tutti i dispositivi ad eccezione dei dischi. Il `reset storageArray SASPHYBaseline` Command reimposta la linea di base SAS PHY per i dischi e gli altri dispositivi. Tutti gli errori vengono cancellati da `.csv` file.

====


== Sintassi

[source, cli]
----
reset storageArray SASPHYBaseline
----


== Parametri

Nessuno.



== Livello minimo del firmware

6.10

7.83 Ripristina la linea di base SAS PHY per i dischi.
