---
permalink: commands-a-z/resume-snapvolume.html 
sidebar: sidebar 
keywords: resume, snapshot, volume 
summary: 'Il comando resume snapVolume riprende un"operazione di volume snapshot interrotta.' 
---
= Riprendi volume snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `resume snapVolume` il comando riprende un'operazione di volume snapshot interrotta.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing, subs="+macros"]
----
resume snapVolume pass:quotes[[_"snapVolumeName"_]] snapImage=pass:quotes[_"snapCGID:imageID"_]
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`snapVolume`
 a| 
Il nome del volume di snapshot per il quale si desidera riprendere le operazioni. Racchiudere il nome del volume snapshot tra virgolette doppie (" ") tra parentesi quadre ([ ]).



 a| 
`snapImage`
 a| 
Il nome dell'immagine snapshot per la quale si desidera riprendere le operazioni del volume snapshot. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` - Utilizzare questa opzione per visualizzare l'ultima immagine snapshot creata nel gruppo di snapshot.
* `OLDEST` - Utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ").

|===


== Note

Il nome di un'immagine istantanea ha due parti separate da due punti (:):

* L'identificatore del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera riprendere le operazioni del volume di snapshot per l'immagine snapshot 12345 in un gruppo di snapshot con il nome snapGroup1, utilizzare questo comando:

[listing]
----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:12345";
----
Per riprendere le operazioni del volume di snapshot per l'immagine snapshot più recente in un gruppo di snapshot con il nome snapGroup1, utilizzare questo comando:

[listing]
----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:newest";
----


== Livello minimo del firmware

7.83
