---
permalink: commands-a-z/resume-snapimage-rollback.html 
sidebar: sidebar 
keywords: resume, snapshot, image, rollback 
summary: 'Il comando resume SnapImage rollback riprende un"operazione di rollback che è entrata in uno stato di pausa.' 
---
= Riprendere il rollback dell'immagine snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `resume snapImage rollback` command riprende un'operazione di rollback che è entrata in uno stato di pausa.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Un'operazione di rollback può entrare in uno stato di pausa a causa di errori di elaborazione, causando una condizione di attenzione necessaria per l'array di storage.

Se non è possibile riprendere l'operazione di rollback, l'immagine istantanea selezionata torna in stato di pausa e viene visualizzata la condizione di attenzione necessaria.

[NOTE]
====
Non è possibile utilizzare questo comando per le immagini snapshot coinvolte nella copia del volume online.

====


== Sintassi

[listing, subs="+macros"]
----
resume snapImage pass:quotes[[_snapImageName_]] rollback
----


== Parametro

|===
| Parametro | Descrizione 


 a| 
`snapImage`
 a| 
Il nome dell'immagine snapshot per la quale si desidera riavviare un'operazione di rollback. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` - Utilizzare questa opzione per visualizzare l'ultima immagine snapshot creata nel gruppo di snapshot.
* `OLDEST` - Utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ") tra parentesi quadre ([ ]).

|===


== Note

Il nome di un'immagine istantanea ha due parti separate da due punti (:):

* L'identificatore del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera riavviare un'operazione di rollback per l'immagine snapshot 12345 in un gruppo di snapshot che ha il nome snapgroup1, utilizzare questo comando:

[listing]
----
resume snapImage ["snapgroup1:12345"] rollback;
----


== Livello minimo del firmware

7.83
