---
permalink: commands-a-z/revive-volumegroup.html 
sidebar: sidebar 
keywords: revive, volume, group 
summary: 'Il comando Revive VolumeGroup (Revive VolumeGroup) forza lo stato ottimale del gruppo di volumi specificato e dei dischi guasti associati.' 
---
= Ripristina gruppo di volumi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `revive volumeGroup` Il comando forza lo stato ottimale del gruppo di volumi specificato e dei relativi dischi guasti associati.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di amministratore del supporto.



== Contesto

[NOTE]
====
*Possibile perdita di accesso ai dati* -- l'uso corretto di questo comando dipende dalla configurazione dei dati su tutti i dischi del gruppo di volumi. Non tentare mai di ripristinare un disco a meno che non si sia supervisionati dal supporto tecnico.

====


== Sintassi

[source, cli, subs="+macros"]
----
revive volumeGroup pass:quotes[[_volumeGroupName_]]
----


== Parametro

|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi da impostare sullo stato ottimale. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.10
