---
permalink: commands-a-z/save-storage-array-diagnostic-data.html 
sidebar: sidebar 
keywords: save, storage, array, diagnostic, data 
summary: 'Il comando SAVE StorageArray diagnosticData salva i dati diagnostici dello storage array dai controller o dai moduli dei servizi ambientali (ESM) in un file.' 
---
= Salvataggio dei dati diagnostici dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save storageArray diagnosticData` Il comando salva i dati diagnostici dello storage array dai controller o dai moduli dei servizi ambientali (ESM) in un file.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

È possibile rivedere il contenuto del file in un secondo momento. È inoltre possibile inviare il file al supporto tecnico per ulteriori revisioni.

Dopo aver salvato i dati diagnostici, è possibile ripristinare i registri NVSRAM che contengono i dati diagnostici in modo che i vecchi dati possano essere sovrascritti. Utilizzare `reset storageArray diagnosticData` comando per resettare i registri dei dati diagnostici.

[NOTE]
====
Eseguire questo comando solo con l'assistenza del supporto tecnico.

====


== Sintassi

[source, cli, subs="+macros"]
----
save storageArray diagnosticData [(controller | tray)]
file=pass:quotes["_filename_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`diagnosticData`
 a| 
Questo parametro consente di scaricare i dati diagnostici dai controller o dagli ESM.



 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare i dati diagnostici dell'array di storage. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\sadiag.zip"`

Questo comando salva automaticamente i dati in un file compresso; tuttavia, questo comando non aggiunge automaticamente un'estensione al file salvato. Specificare `.zip` extension quando si inserisce il nome del file.

|===


== Note

Nelle versioni di questo comando precedenti alla 7.77, l'opzione utente era `esm` invece di `tray`. A partire dal 7.77, `tray` sostituisce `esm`. L'utilizzo di `esm` è ancora supportato, ma per la migliore compatibilità con le versioni future, sostituire `esm` con `tray`.



== Livello minimo del firmware

6.16

7.77 `tray` sostituisce `esm`.
