---
permalink: commands-a-z/save-alldrives-logfile.html 
sidebar: sidebar 
keywords: save, drive log 
summary: Il comando Save allDrives logfile salva i log del disco in un file. 
---
= Salvataggio del registro di unità - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save allDrives logFile` il comando salva i registri del disco in un file.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Contesto

I dati del log dei dischi vengono gestiti dall'array di storage per ciascun disco.

[NOTE]
====
Non eseguire questo comando a meno che non venga richiesto dal supporto tecnico.

====


== Sintassi

[source, cli, subs="+macros"]
----
save allDrives logFile=pass:quotes["_filename_"]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`*logFile*`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare i log del disco. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\drive01.zip"`

[NOTE]
====
Questo comando non aggiunge automaticamente un'estensione al file salvato. Specificare l'estensione del file .zip quando si inserisce il nome del file.

====
|===


== Livello minimo del firmware

6.10
