---
permalink: commands-a-z/save-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, server, certificate, sign, request, csr 
summary: 'Il comando Save controller arrayManagementCSR recupera la richiesta di firma del certificato (CSR) del server installato per il controller in modo da poter visualizzare i dettagli del certificato.' 
---
= Recupera il certificato del server installato - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save controller arrayManagementCSR` comando recupera la richiesta di firma del certificato (CSR) del server installato per il controller in modo da poter visualizzare i dettagli del certificato.



== Array supportati

Questo comando si applica ai singoli array di storage E4000, E2800, E5700, EF600, EF300, EF50 e EF80. Non si applica agli array di storage E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Security Admin.



== Sintassi

[source, cli, subs="+macros"]
----

save controller [(a|b)] arrayManagementCSR file=pass:quotes["_filename_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Consente di specificare il controller da cui si desidera scaricare il certificato firmato. Gli identificatori di controller validi sono a o b, dove a è il controller nello slot A e b è il controller nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]).



 a| 
`file`
 a| 
Consente di specificare il file per il quale salvare il file di certificato firmato del controller.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "save controller [a] aarrayManagementCSR
   file="C:\controllerAcertificate.cer";"

SMcli -n Array1 -c "save controller [b] arrayManagementCSR
   file="C:\controllerBcertificate.cer";"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
