---
permalink: commands-a-z/save-storagearray-performancestats.html 
sidebar: sidebar 
keywords: save, storage, array, performance, statistics 
summary: Il comando Save StorageArray performanceStats salva le statistiche delle performance in un file. 
---
= Salva le statistiche sulle prestazioni dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save storageArray performanceStats` il comando salva le statistiche delle performance in un file.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Contesto

Prima di utilizzare questo comando, eseguire `set session performanceMonitorInterval` e il `set session performanceMonitorIterations` per specificare la frequenza con cui vengono raccolte le statistiche.



== Sintassi

[source, cli, subs="+macros"]
----
save storageArray performanceStats file=pass:quotes["_filename_"]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare le statistiche delle prestazioni. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\sastat.csv"`

Il nome predefinito del file che contiene le statistiche delle prestazioni è `performanceStatistics.csv`. È possibile utilizzare qualsiasi nome di file, ma è necessario utilizzare `.csv` interno.

|===


== Livello minimo del firmware

6.10
