---
permalink: commands-a-z/save-alltrays-logfile.html 
sidebar: sidebar 
keywords: save, tray log 
summary: Il comando Save allTrimes logfile salva i dati di rilevamento del log in un file. 
---
= Salva registro vassoio - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save allTrays logFile` il comando salva i dati di rilevamento dei log in un file.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

I dati di log sense vengono conservati dalle schede ambientali di ciascun vassoio Non tutte le schede ambientali contengono dati di rilevamento dei log.



== Sintassi

[source, cli, subs="+macros"]
----
save allTrays logFile=pass:quotes["_filename_"]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`*logFile*`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare i dati di rilevamento del log. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\traylogdat.txt"`

Questo comando non aggiunge automaticamente un'estensione al file salvato. Specificare un'estensione del file quando si inserisce il nome del file.

|===


== Livello minimo del firmware

6.50
