---
permalink: commands-a-z/save-storagearray-configuration.html 
sidebar: sidebar 
keywords: save, storage, array, configuration 
summary: 'Il comando di configurazione SAVE StorageArray crea un file di script che può essere utilizzato per ricreare la configurazione corrente del volume dell"array di storage.' 
---
= Salvare la configurazione dello storage array
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `save storageArray configuration` command crea un file di script che è possibile utilizzare per ricreare la configurazione corrente del volume dell'array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage. Tuttavia, l'utilizzo di questo comando con il parametro LDAP è limitato a quelli con il ruolo Security Admin.



== Contesto

[NOTE]
====
Questo comando non salva i dati di configurazione del mirroring remoto o della copia del volume sull'array di storage corrente in un file.

====


== Sintassi

[listing, subs="+macros"]
----
save storageArray configuration file=pass:quotes["_filename_"]
(allconfig|[globalSettings=(TRUE | FALSE)]
[volumeConfigAndSettings=(TRUE | FALSE)]
[hostTopology=(TRUE | FALSE)]
[lunMappings=(TRUE | FALSE)])
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare le impostazioni di configurazione. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\saconf.cfg"`

Il nome predefinito del file che contiene le impostazioni di configurazione è `storage-array-configuration.cfg`. Questo comando non aggiunge automaticamente un'estensione al file salvato. Specificare un'estensione del file quando si inserisce il nome del file.



 a| 
`allConfig`
 a| 
L'impostazione per salvare tutti i valori di configurazione nel file. Se si sceglie questo parametro, tutti i parametri di configurazione vengono impostati su `TRUE` .)



 a| 
`globalSettings`
 a| 
L'impostazione per salvare le impostazioni globali nel file. Per salvare le impostazioni globali, impostare questo parametro su `TRUE`. Per evitare di salvare le impostazioni globali, impostare questo parametro su `FALSE`. Il valore predefinito è `TRUE`.



 a| 
`volumeConfigAndSettings`
 a| 
L'impostazione per salvare le impostazioni di configurazione del volume e tutte le impostazioni globali nel file. Per salvare le impostazioni di configurazione del volume e le impostazioni globali, impostare questo parametro su `TRUE`. Per evitare di salvare le impostazioni di configurazione del volume e le impostazioni globali, impostare questo parametro su `FALSE`. Il valore predefinito è `TRUE`.



 a| 
`hostTopology`
 a| 
L'impostazione per salvare la topologia host nel file. Per salvare la topologia host, impostare questo parametro su `TRUE`. Per impedire il salvataggio della topologia host, impostare questo parametro su `FALSE`. Il valore predefinito è `FALSE`.



 a| 
`lunMappings`
 a| 
L'impostazione per salvare la mappatura LUN o NSID nel file. Per salvare la mappatura LUN o NSID, impostare questo parametro su `TRUE`. Per impedire il salvataggio della mappatura LUN o NSID, impostare questo parametro su `FALSE`. Il valore predefinito è `FALSE`.

|===


== Note

Quando si utilizza questo comando, è possibile specificare qualsiasi combinazione dei parametri per l'impostazione globale, l'impostazione di configurazione del volume, la topologia dell'host o la mappatura del LUN. Se si desidera inserire tutte le impostazioni, utilizzare `allConfig` parametro. È necessario utilizzare il `allConfig` o uno o più degli altri quattro parametri.



== Livello minimo del firmware

6.10
