---
permalink: commands-a-z/save-storagearray-controllerhealthimage.html 
sidebar: sidebar 
keywords: save, storage, array, controller, health, image 
summary: 'Il comando SAVE StorageArray controllerHealthImage salva un"immagine dello stato di salute del controller in un file specifico su un host, per gli array di storage che supportano la funzionalità dell"immagine dello stato di salute del controller.' 
---
= Salvare l'immagine dello stato del controller dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `save storageArray controllerHealthImage` il comando salva un'immagine dello stato di salute del controller in un file specifico su un host, per gli array di storage che supportano la funzionalità dell'immagine dello stato di salute del controller.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Con la versione del firmware 8.20 di `coreDump` il parametro viene sostituito da `controllerHealthImage` parametro.

====
Se lo storage array non supporta la funzione di immagine dello stato del controller, il comando restituisce un errore.



== Sintassi

[listing, subs="+macros"]
----
save storageArray controllerHealthImage file=pass:quotes["_filename_"]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si salva l'immagine di stato del controller. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

[listing]
----
file="C:\Array Backups\DBMbackup_03302010.core"
----
|===


== Note

Un file di immagine dello stato di salute del controller potrebbe avere una dimensione di uno o due gigabyte e richiedere alcuni minuti per il salvataggio. Oltre a salvare l'immagine di integrità del controller, questo comando genera un file di descrittore XML basato sui metadati dell'immagine di integrità del controller. Questo file descrittore viene salvato in formato ZIP nello stesso percorso dell'immagine dello stato del controller. L'esempio seguente mostra il formato XML per il file descrittore.

[listing]
----
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
- <DPLcontrollerHealthImageInfo>
<dplcontrollerHealthImageTag>sometag#</dplcontrollerHealthImageTag>
<captureTime>12/22/10 3:58:53 PM IST</captureTime>
- <StorageArrayData>
<ArraySAID>600a0b80006e006a000000004c65efc1</ArraySAID>
<ManagementApiVersion>devmgr.v1083api01.Manager</ManagementApiVersion>
<fwVersion>07.83.01.00</fwVersion>
<platformType>7091</platformType>
</StorageArrayData>
<fullcontrollerHealthImageCtlr>controllerserialNumber1
     </fullcontrollerHealthImageCtlr>
<fullcontrollerHealthImageSize>fullCaptureSize</fullcontrollerHealthImageSize>
<altcontrollerHealthImageCtlr>controllerserialNumber2</altcontrollerHealthImage
     Ctlr>
<altcontrollerHealthImageSize>altCaptureSize</altcontrollerHealthImageSize>
<triggerReason>Exception</triggerReason>-<DPLcontrollerHealthImageDetail>
<dplcontrollerHealthImageReason>DPLcontrollerHealthImageReason
     </dplcontrollerHealthImageReason>
- <fwLocation >
<filename>filename</filename>
<lineNumber>line#</lineNumber>
</fwLocation >
<panicReason>panicString</panicReason>
</DPLcontrollerHealthImageDetail>
</DPLcontrollerHealthImageInfo>
----
Quando si recupera un'immagine dello stato di salute del controller dalla cache del controller a un host, viene impostato un flag sul controller per indicare che non è necessario recuperare l'immagine dello stato di salute del controller. Questa impostazione persiste per 48 ore. Se si verifica una nuova immagine dello stato di salute del controller durante tale periodo, la nuova immagine dello stato di salute del controller viene salvata nella cache del controller e sovrascrive eventuali dati precedenti dell'immagine dello stato di salute del controller nella cache.



== Livello minimo del firmware

7.83

8.20 sostituisce `coreDump` con il `controllerHealthImage` parametro.
