---
permalink: commands-a-z/save-controller-cacertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, ca, certificates 
summary: Il comando Save controller caCertificate recupera i certificati CA installati dal controller specificato. Nei certificati recuperati sono inclusi tutti i certificati CA richiesti dal server Web del controller. 
---
= Recupera i certificati CA installati - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save controller caCertificate` Il comando recupera i certificati CA installati dal controller specificato. Nei certificati recuperati sono inclusi tutti i certificati CA richiesti dal server Web del controller.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Sintassi

[source, cli, subs="+macros"]
----

save controller[(a|b)] caCertificate [all | aliases=pass:quotes[("_alias1_" ... "_aliasN_")]]
 path="fileLocation"
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Consente di specificare il controller su cui si desidera recuperare i certificati root/intermedi. Gli identificatori di controller validi sono a o b, dove a è il controller nello slot A e b è il controller nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]).



 a| 
`all`
 a| 
Consente di specificare il recupero di tutti i certificati importati per risolvere la catena di certificati firmati. I certificati installati dall'utente includono i certificati di gestione delle chiavi.



 a| 
`aliases`
 a| 
Consente di specificare quale certificato root/intermedio installato dall'utente recuperare in base all'alias. Racchiudere tutti gli alias tra parentesi. Se si immettono più alias, separarli con uno spazio.



 a| 
`path`
 a| 
Consente di specificare la posizione locale per il salvataggio dei certificati root/intermedi dei controller`.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "save controller[a] caCertificate all path="C:\";"

SMcli -n Array1 -c "save controller[b] caCertificate aliases=("myAlias" "anotherAlias") path="C:\";"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
