---
permalink: commands-a-z/save-storagearray-performancestats.html 
sidebar: sidebar 
keywords: save, storage, array, performance, statistics 
summary: Il comando Save StorageArray performanceStats salva le statistiche delle performance in un file. 
---
= Salva le statistiche sulle performance degli array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `save storageArray performanceStats` il comando salva le statistiche delle performance in un file.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Prima di utilizzare questo comando, eseguire `set session performanceMonitorInterval` e il `set session performanceMonitorIterations` per specificare la frequenza con cui vengono raccolte le statistiche.



== Sintassi

[listing, subs="+macros"]
----
save storageArray performanceStats file=pass:quotes["_filename_"]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare le statistiche delle prestazioni. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\sastat.csv"`

Il nome predefinito del file che contiene le statistiche delle prestazioni è `performanceStatistics.csv`. È possibile utilizzare qualsiasi nome di file, ma è necessario utilizzare `.csv` interno.

|===


== Livello minimo del firmware

6.10
