---
permalink: commands-a-z/save-check-vol-parity-job-errors.html 
sidebar: sidebar 
keywords: save, check, volume, parity, job, errors 
summary: Il comando Save check volume parity job errors salva nel file specificato gli errori di parità registrati da un job di controllo della parità del volume. 
---
= Salvataggio, verifica volume, errori di parità del lavoro di parità - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save check volume parity job parity errors` il comando salva nel file specificato gli errori di parità registrati da un processo di verifica della parità del volume. Il file di output viene scritto nello stesso formato del comando di parità del volume di controllo obsoleto e può quindi essere utilizzato come input per il comando di parità del volume di riparazione esistente.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi gli array EF600, EF300, EF50 e EF80, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage EF600, EF300, EF50 e EF80, devi avere il ruolo Storage Admin.



== Sintassi

[source, cli, subs="+macros"]
----
save check volume parity job parityErrors jobId=<job_id> parityErrorFile=<parity_error_file>;
----


== Parametri

|===
| Parametro | Descrizione 


 a| 
`jobId`
 a| 
l'id lavoro per il quale recuperare e salvare gli errori di parità registrati. Questo valore è obbligatorio.



 a| 
`parityErrorFile`
 a| 
Il file specificato dall'utente per indicare dove salvare gli errori di parità registrati. Questo valore è obbligatorio.

|===


== Livello minimo del firmware

11.80
