---
permalink: commands-a-z/save-storagearray-statecapture.html 
sidebar: sidebar 
keywords: save, storage, array, state, capture 
summary: 'Il comando Save StorageArray stateCapture salva l"acquisizione dello stato di un array di storage in un file.' 
---
= Salvataggio dell'acquisizione dello stato dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save storageArray stateCapture` il comando salva l'acquisizione dello stato di un array di storage in un file.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
save storageArray stateCapture file=pass:quotes["_filename_"]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare l'acquisizione dello stato. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\state.txt"`

È possibile utilizzare qualsiasi nome di file, ma è necessario utilizzare `.txt` interno.

Il nome predefinito del file che contiene l'acquisizione dello stato è `state-capture-data.txt`. Questo comando non aggiunge automaticamente un'estensione al file salvato. Specificare un'estensione del file quando si inserisce il nome del file.

|===