---
permalink: commands-a-z/save-storagearray-iscsistatistics.html 
sidebar: sidebar 
keywords: save, storage, array, iscsi, statistics 
summary: Il comando Save StorageArray iscsiStatistics salva le statistiche delle performance iSCSI dello storage array in un file. 
---
= Salvare le statistiche iSCSI degli array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save storageArray iscsiStatistics` Il comando salva in un file le statistiche delle performance iSCSI dello storage array.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.

[NOTE]
====
Questo comando è obsoleto e viene sostituito da xref:save-storagearray-hostportstatistics.adoc[Salvare le statistiche delle porte host dell'array di storage] comando.

====


== Sintassi

[source, cli, subs="+macros"]
----
save storageArray iscsiStatistics [(raw | baseline)] file=pass:quotes["_filename_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`raw`
 a| 
Le statistiche raccolte sono tutte statistiche dell'inizio della giornata del controller. Racchiudere il parametro tra parentesi quadre ([ ]).



 a| 
`baseline`
 a| 
Le statistiche raccolte sono tutte statistiche del momento in cui i controller sono stati azzerati utilizzando `reset storageArray ibStatsBaseline` comando. Racchiudere il parametro tra parentesi quadre ([ ]).



 a| 
`file`
 a| 
Il percorso del file e il nome del file in cui si desidera salvare le statistiche delle prestazioni. Racchiudere il nome del file tra virgolette doppie (" "). Ad esempio:

`file="C:\Program Files\CLI\logs\iscsistat.csv"`

Il nome predefinito del file che contiene le statistiche delle prestazioni iSCSI è `iscsi-statistics.csv`. È possibile utilizzare qualsiasi nome di file, ma è necessario utilizzare `.csv` interno.

|===


== Note

Se le statistiche di base iSCSI non sono state reimpostate dall'inizio della giornata del controller, l'ora all'inizio della giornata è l'ora di riferimento predefinita.



== Livello minimo del firmware

7.10

8.41 questo comando è obsoleto.
