---
permalink: commands-a-z/save-storagearray-trustedcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, trusted, ca, certificates 
summary: 'Il comando Save StorageArray trustedCertificate recupera i certificati CA attendibili installati per l"array. Nei file recuperati sono inclusi tutti i certificati CA richiesti dai server Web dell"array.' 
---
= Recuperare i certificati CA attendibili installati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save storageArray trustedCertificate` Il comando recupera i certificati CA attendibili installati per l'array. Nei file recuperati sono inclusi tutti i certificati CA richiesti dai server Web dell'array.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Sintassi

[source, cli, subs="+macros"]
----
save storageArray trustedCertificate [allUserInstalled |
aliases=pass:quotes[("_alias1_" ... "_aliasN_")]] path=pass:quotes["_fileLocation_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allUserInstalled`
 a| 
Consente di specificare il recupero dei certificati installati dall'utente. L'opzione predefinita è `allUserInstalled` se non sono stati specificati alias.



 a| 
`aliases`
 a| 
Consente di specificare quale certificato attendibile installato dall'utente deve essere recuperato in base all'alias. Racchiudere tutti gli alias tra parentesi. Se si immettono più alias, separarli con uno spazio.



 a| 
`path`
 a| 
Consente di specificare la posizione locale per cui salvare i certificati attendibili del controller.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "save storageArray trustedCertificate allUserInstalled path="C:\";"

SMcli -n Array1 -c "save storageArray trustedCertificate aliases=("myAlias" "anotherAlias") path="C:\";"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
