---
permalink: commands-a-z/save-storagearray-keymanagementclientcsr.html 
sidebar: sidebar 
keywords: generate, key, management, certificate, sign, request, csr 
summary: Il comando Save StorageArray keyManagementClientCSR richiede una CSR generata per lo storage array che è possibile salvare in un file. 
---
= Genera richiesta di firma del certificato di gestione delle chiavi (CSR) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `save storageArray keyManagementClientCSR` Il comando richiede una CSR generata per l'array di storage che è possibile salvare in un file.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Contesto

[NOTE]
====
Questo comando si applica solo alla gestione esterna delle chiavi.

====


== Sintassi

[source, cli, subs="+macros"]
----

save storageArray keyManagementClientCSR commonName=pass:quotes["_common_name_"]
organization=pass:quotes["_organization_"]
locality=pass:quotes["_locality_"]
country=pass:quotes["_country_"]
file=pass:quotes["_file_"]
[organizationalUnit=pass:quotes["_organizational unit_"]]
[stateProvince=pass:quotes["_state_province_"]]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`commonName`
 a| 
Il valore immesso per questo parametro deve corrispondere a uno dei nomi utente definiti sul server KMIP.



 a| 
`organization`
 a| 
Consente di specificare il nome legale completo dell'organizzazione a cui appartiene lo storage array. Non abbreviarlo e non includere suffissi come Inc, Corp o LLC.



 a| 
`locality`
 a| 
Consente di specificare la città o la località in cui si trova lo storage array,



 a| 
`country`
 a| 
Consente di specificare il codice alfa-2 ISO (International Organization for Standardization) 3166-1 a due cifre del proprio paese, ad esempio USA.



 a| 
`file`
 a| 
Consente di specificare la posizione del file e del file in cui salvare il file di certificato firmato dal controller.



 a| 
`organizationalUnit`
 a| 
Consente di specificare la divisione dell'organizzazione che gestisce il certificato.



 a| 
`stateProvince`
 a| 
Consente di specificare lo stato o la regione in cui si trova l'array di storage. Questa operazione non deve essere abbreviata.

|===


== Esempio

[listing, subs="+macros"]
----

SMcli -n Array1 -c "save storageArray keyManagementClientCSR commonName=pass:quotes["_192.0.2.1_"]
organization=pass:quotes["_Widgets Are Us_, _Inc_."]
locality=pass:quotes["_sedgwick_"]
country=pass:quotes["_US_"]
file=pass:quotes["_latestCertificate_"]
organizationalUnit=pass:quotes["_Products Unit_"]
stateProvince=pass:quotes["_Kansas_"];"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40
