---
permalink: commands-a-z/save-auditlog.html 
sidebar: sidebar 
keywords: save, audit log, records 
summary: Il comando SAVE AuditLog recupera i record del registro di controllo. 
---
= Salvare i record del registro di controllo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `save auditLog` il comando recupera i record del registro di controllo.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Sintassi

[listing, subs="+macros"]
----

save auditLog (all | (beginDate=pass:quotes[_date_ | endDate=_date_)]
|(beginRecord=pass:quotes[_timestamp_] | endRecord=pass:quotes[_timestamp_))] file=pass:quotes["_filename_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`all`
 a| 
Consente di recuperare tutti i record del registro di controllo.



 a| 
`beginDate`
 a| 
Consente di specificare la data di inizio da recuperare. Il formato per l'immissione della data è MM:GG:YY nel fuso orario del client. Il primo record del registro di controllo recuperato sarà il primo record pubblicato il o dopo la data specificata.

[NOTE]
====
L'intervallo da mezzanotte a mezzanotte si basa sul fuso orario del client.

====


 a| 
`endDate`
 a| 
Consente di specificare la data finale da recuperare. Se non specificato, viene recuperato l'ultimo record del log. Il formato per l'immissione della data è MM:GG:YY nel fuso orario del client. L'ultimo record del registro di controllo recuperato sarà l'ultimo record pubblicato il o prima della data specificata.

[NOTE]
====
L'intervallo da mezzanotte a mezzanotte si basa sul fuso orario del client.

====


 a| 
`beginRecord`
 a| 
Consente di specificare il record iniziale da recuperare. Il valore è il valore integrale che rappresenta l'indicazione dell'ora del primo record del registro di controllo, incluso. Se non specificato, viene recuperato il primo record del log.



 a| 
`endRecord`
 a| 
Consente di specificare il record finale da recuperare. Il valore è il valore integrale che rappresenta la data e l'ora dell'ultimo record del registro di controllo, incluso. Se non specificato, viene recuperato l'ultimo record del log.



 a| 
`file`
 a| 
Consente di specificare il nome del file di output del registro di controllo.

[NOTE]
====
I record del registro di controllo vengono salvati nel file in ordine decrescente, dal più recente al meno recente.

====
|===


== Esempi

[listing]
----

SMcli -n Array1 -c "save auditLog all file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog endRecord=1493070393313 file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog beginDate=12:12:16 endDate=04:01:17 file="myAuditLog.txt";"


SMcli completed successfully.
----


== Livello minimo del firmware

8.40
