---
permalink: commands-a-z/set-isertarget.html 
sidebar: sidebar 
keywords: set, iser, target 
summary: Il comando set iserTarget definisce le proprietà di una destinazione iSER. 
---
= Imposta target iSER - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set iserTarget` Il comando definisce le proprietà di una destinazione iSER.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.

[NOTE]
====
Questo comando è obsoleto e viene sostituito da xref:set-target.adoc[Impostare le proprietà di destinazione] comando.

====


== Sintassi

[source, cli, subs="+macros"]
----
set iserTarget pass:quotes[["_userLabel_"]]
authenticationMethod=(none | chap) |
chapSecret=pass:quotes[_securityKey_] |
targetAlias=pass:quotes["_userLabel_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`iserTarget`
 a| 
La destinazione iSER per cui si desidera impostare le proprietà. Racchiudere il `_userLabel_` tra virgolette doppie (" "). È inoltre necessario racchiudere il `_userLabel_` Tra parentesi quadre ([ ]) se l'etichetta utente è un alias di destinazione o parentesi angolari (< >) se l'etichetta utente è un nome iSCSI qualificato (IQN).



 a| 
`authenticationMethod`
 a| 
Il mezzo per autenticare la sessione iSCSI.



 a| 
`chapSecret`
 a| 
La chiave di sicurezza che si desidera utilizzare per autenticare una connessione peer.



 a| 
`targetAlias`
 a| 
Il nuovo nome che si desidera utilizzare per la destinazione. Racchiudere il nome tra virgolette doppie (" ").

|===


== Note

Challenge Handshake Authentication Protocol (CHAP) è un protocollo che autentica il peer di una connessione. Il CHAP si basa sui peer che condividono un _segreto_. Un segreto è una chiave di sicurezza simile a una password.

Utilizzare `chapSecret` parametro per impostare le chiavi di sicurezza per gli iniziatori che richiedono un'autenticazione reciproca. Il segreto CHAP deve essere compreso tra 12 e 57 caratteri. Questa tabella elenca i caratteri validi.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Spazio
 a| 
!
 a| 
"
 a| 
N.
 a| 
€
 a| 
%
 a| 
&
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
<
 a| 
=
 a| 
>
 a| 
?
 a| 
@
 a| 
R
 a| 
B
 a| 
C.



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
IO
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P.
 a| 
D
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V.
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[.



 a| 
.
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
r
 a| 
b
 a| 
c.
 a| 
d
 a| 
e
 a| 
f
 a| 
g



 a| 
h
 a| 
io
 a| 
j
 a| 
k
 a| 
l
 a| 
m
 a| 
n
 a| 
o
 a| 
p.
 a| 
d
 a| 
r
 a| 
s



 a| 
t
 a| 
u
 a| 
v.
 a| 
w
 a| 
x
 a| 
y
 a| 
z
 a| 
{
 a| 
|
 a| 
}
 a| 
~
 a| 

|===


== Livello minimo del firmware

8.20

8.41 questo comando è obsoleto.
