---
permalink: commands-a-z/set-hostgroup.html 
sidebar: sidebar 
keywords: set, host, group 
summary: Il comando set hostGroup rinomina un gruppo di host. 
---
= Impostare il gruppo di host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set hostGroup` il comando rinomina un gruppo di host.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
set hostGroup pass:quotes[[_hostGroupName_]]
userLabel=pass:quotes["_newHostGroupName_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`hostGroup`
 a| 
Il nome del gruppo di host che si desidera rinominare. Racchiudere il nome del gruppo di host tra parentesi quadre ([ ]). Se il nome del gruppo di host contiene caratteri speciali o numeri, è necessario racchiudere il nome del gruppo di host tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`userLabel`
 a| 
Il nuovo nome del gruppo host. Racchiudere il nome del nuovo gruppo di host tra virgolette doppie (" ").

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per i nomi. I nomi possono avere un massimo di 30 caratteri.



== Livello minimo del firmware

6.10
