---
permalink: commands-a-z/set-initiator.html 
sidebar: sidebar 
keywords: set, initiator 
summary: 'Il comando Set Initiator aggiorna l"oggetto Initiator.' 
---
= Inizializzatore set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set initiator` il comando aggiorna l'oggetto initiator.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Questo comando sostituisce il deprecato xref:set-iscsiinitiator.adoc[Impostare iSCSI Initiator] comando.

====
[NOTE]
====
Questo comando è applicabile solo a iSCSI, iSER, NVMe su RoCE, NVMe su InfiniBand e NVMe su Fibre Channel.

====


== Sintassi

[source, cli]
----
set initiator (["initiatorName"] | <"initiatorQualifiedName">) ([userLabel="newInitiatorName"] |
[host="newHostName"] | [chapSecret="newSecurityKey"])
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`initiator`
 a| 
Consente di specificare l'identificativo dell'iniziatore per il quale si desidera impostare le proprietà. Racchiudere il nome tra virgolette doppie ("` "`). È inoltre necessario racchiudere il nome tra parentesi quadre ([ ]) se il valore è un'etichetta utente o tra parentesi angolari (< >) se il valore è un nome qualificato (ad esempio, iqn o nqn).



 a| 
`userLabel`
 a| 
Consente di immettere una nuova etichetta utente per l'oggetto Initiator. Racchiudere la nuova etichetta utente tra virgolette doppie (" ").



 a| 
`host`
 a| 
Consente di inserire un nuovo host a cui è connessa la porta host. Racchiudere il nome host tra virgolette doppie (" ").



 a| 
`chapSecret`
 a| 
Consente di immettere una nuova chiave di sicurezza da utilizzare per autenticare una connessione peer. Racchiudere la chiave di sicurezza tra virgolette doppie (" "). Questo parametro è applicabile solo a. `iSCSI` e. `iSER` tipi di interfaccia host.

|===


== Livello minimo del firmware

8.41
