---
permalink: commands-a-z/set-storagearray-learncycledate-controller.html 
sidebar: sidebar 
keywords: set, storage, array, controller, battery, learn, cycle 
summary: Il comando Set StorageArray learnCycleDate controller imposta i cicli di apprendimento della batteria del controller. 
---
= Impostare il ciclo di apprendimento della batteria del controller dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `set storageArray learnCycleDate controller` il comando imposta i cicli di apprendimento della batteria del controller.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Per impostare singoli cicli di apprendimento per ciascun controller dell'array di storage, inviare questo comando a entrambi i controller.

====
[NOTE]
====
I cicli di apprendimento non sono collegati tra loro, pertanto un'interruzione di un ciclo di apprendimento della batteria di un controller non avrà alcun impatto sul ciclo di apprendimento della batteria nell'altro controller.

====
[NOTE]
====
Il completamento di un ciclo di apprendimento potrebbe richiedere diverse ore.

====


== Sintassi

[listing, subs="+macros"]
----
set storageArray learnCycleDate (controller[(a| b)] )
pass:quotes[(daysToNextLearnCycle=_numberOfDays_ |
day=_dayOfTheWeek_)] pass:quotes[time=_HH:MM_]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`*controller*`
 a| 
Il controller per il quale si desidera specificare un ciclo di apprendimento della batteria. Gli identificatori del controller validi sono `a` oppure `b`, dove `a` È il controller nello slot A, e. `b` Il controller si trova nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]). Se non si specifica un controller, il firmware del controller restituisce un errore di sintassi.

[NOTE]
====
Omettendo questo parametro si imposta il ciclo di apprendimento per entrambe le batterie del controller in un array a controller doppio.

====


 a| 
`daysToNextLearnCycle`
 a| 
I valori validi sono `0` attraverso `7`, dove `0` è immediatamente e. `7` è in sette giorni. Il `daysToNextLearnCycle` il parametro viene eseguito fino a sette giorni dopo il successivo ciclo di apprendimento pianificato.



 a| 
`day`
 a| 
Valori validi per `day` il parametro include i giorni della settimana (`Sunday`, `Monday`, `Tuesday`, `Wednesday`, `Thursday`, `Friday`, e. `Saturday`). Impostando il giorno, il ciclo di apprendimento successivo viene pianificato nel giorno specificato, dopo il ciclo di apprendimento attualmente pianificato.



 a| 
`time`
 a| 
L'ora nel formato a 24 ore, ad esempio 8:00 viene immesso come `08:00`. Ore nove viene immesso come `21:00`e alle 21:30 viene immesso come `21:30`.

|===


== Esempio

[listing]
----
set storageArray learnCycleDate controller [a] daysToNextLearnCycle=4 time=08:30;
----


== Note

È possibile impostare il ciclo di apprendimento in modo che si verifichi una sola volta durante un periodo di sette giorni.

Il `time` parameter (parametro) consente di selezionare l'ora specifica in cui si desidera eseguire il ciclo di apprendimento. Se non viene immesso alcun valore, il comando utilizza un valore predefinito di `00:00` (mezzanotte).

Se il giorno e l'ora specificati sono passati, il ciclo di apprendimento successivo viene eseguito il giorno successivo possibile specificato.



== Livello minimo del firmware

7.15

8.30 - aggiunto il `controller` parametro.
