---
permalink: commands-a-z/set-snapvolume-converttoreadwrite.html 
sidebar: sidebar 
keywords: set, read-only, snapshot, volume, read/write, volume 
summary: Il comando set SnapVolume convertToReadWrite modifica un volume di snapshot di sola lettura in un volume di snapshot di lettura/scrittura. 
---
= Impostare il volume snapshot di sola lettura su un volume di lettura/scrittura
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set snapVolume convertToReadWrite` il comando consente di modificare un volume di snapshot di sola lettura in un volume di snapshot di lettura/scrittura.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

È inoltre possibile utilizzare questo comando per identificare un nuovo volume di repository per il volume di lettura/scrittura o per impostare un livello di avviso di limite completo per il volume di repository.



== Sintassi

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapImageVolumeName_"]] convertToReadWrite
[(repositoryVolume="repos_xxxx" |
repositoryVolume=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]])
repositoryVolume=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapVolume`
 a| 
Il nome del volume di snapshot che si desidera modificare da sola lettura a lettura/scrittura. Racchiudere l'identificatore del volume snapshot tra virgolette doppie (" ") all'interno di parentesi quadre ([ ]).



 a| 
`repositoryVolume`
 a| 
Il nome del volume di repository che si desidera utilizzare per il volume di lettura/scrittura.

Sono disponibili due opzioni per definire il nome di un volume di repository:

* Utilizzare un volume repository esistente: Nome
* Creare un nuovo volume di repository quando si esegue questo comando


Il nome di un volume di repository esistente è composto da due parti:

* Il termine "repos"
* Identificatore numerico a quattro cifre assegnato dal software di gestione dello storage al nome del volume del repository


Racchiudere il nome del volume di repository esistente tra virgolette doppie (" ").

Se si desidera creare un nuovo volume di repository quando si esegue questo comando, è necessario immettere il nome di un gruppo di volumi o di un pool di dischi in cui si desidera creare il volume di repository. In alternativa, è anche possibile definire la capacità del volume di repository. Se si desidera definire la capacità, è possibile utilizzare i seguenti valori:

* Un valore intero che rappresenta una percentuale della capacità del volume di base
* Un valore di frazione decimale che rappresenta una percentuale della capacità del volume di base
* Una dimensione specifica per il volume di repository. Le dimensioni sono definite in unità di `bytes`, `KB`, `MB`, `GB`, o. `TB`.


Se non si utilizza l'opzione di capacità, il software di gestione dello storage imposta la capacità sul 20% della capacità del volume di base.

Quando si esegue questo comando, il software di gestione dello storage crea il volume di repository per il volume di snapshot.



 a| 
`repositoryFullLimit`
 a| 
La percentuale di capacità del volume del repository alla quale viene visualizzato un avviso che indica che il volume del repository di immagini snapshot è quasi pieno. USA valori interi. Ad esempio, un valore di 70 significa 70%. Il valore predefinito è 75.

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per l'etichetta utente. Le etichette dell'utente possono contenere un massimo di 30 caratteri.

Il nome del volume del repository viene creato automaticamente dal software di gestione dello storage e dal firmware quando si crea un nuovo gruppo di snapshot. Non è possibile rinominare il volume del repository perché la ridenominazione del volume del repository interromperà il collegamento con le immagini snapshot.

Un volume di repository di gruppi di snapshot è un volume espandibile strutturato come un insieme concatenato di un massimo di 16 entità di volume standard. Inizialmente, un volume di repository espandibile ha un solo elemento. La capacità del volume di repository espandibile è esattamente quella del singolo elemento. È possibile aumentare la capacità di un volume di repository espandibile allegando volumi standard aggiuntivi. La capacità del volume del repository espandibile composito diventa quindi la somma delle capacità di tutti i volumi standard concatenati.

Un volume di repository di gruppi di snapshot deve soddisfare un requisito di capacità minimo che corrisponde alla somma dei seguenti requisiti:

* 32 MB per supportare un overhead fisso per il gruppo di snapshot e per l'elaborazione copy-on-write.
* Capacità per l'elaborazione del rollback, pari a 1/5000esimo della capacità del volume di base.


La capacità minima viene utilizzata dal firmware del controller e dal software di gestione dello storage.



== Livello minimo del firmware

7.83
