---
permalink: commands-a-z/set-storagearray-passwordlength.html 
sidebar: sidebar 
keywords: set, storage, array, password, length 
summary: 'Il comando set StorageArray passwordlength consente all"utente amministratore di impostare una lunghezza minima per tutte le password nuove o aggiornate sull"array di storage.' 
---
= Impostare la lunghezza della password dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set storageArray passwordlength` il comando consente all'utente amministratore di impostare una lunghezza minima per tutte le password nuove o aggiornate sull'array di storage.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Sintassi

[source, cli]
----
set storageArray passwordLength=<INTEGER>
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`password length`
 a| 
Consente di impostare la lunghezza minima richiesta per tutte le password nuove o aggiornate.



 a| 
`INTEGER`
 a| 
Consente di impostare la lunghezza minima richiesta, tra 0 e 30, per tutte le password nuove o aggiornate.

|===


== Esempi

[listing]
----

SMcli <array_ip> -u <username> -p <password> -c "set storageArray passwordLength=0;"

SMcli completed successfully.
----


== Livello minimo del firmware

8.41 aggiunge il comando.
