---
permalink: commands-a-z/set-storagearray-isnsipv6address.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, ipv6, address 
summary: 'Il comando Set StorageArray isnsIPv6Address imposta l"indirizzo IPv6 per il server iSNS.' 
---
= Imposta l'indirizzo IPv6 del server iSNS dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set storageArray isnsIPv6Address` Il comando imposta l'indirizzo IPv6 per il server iSNS.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
set storageArray isnsIPv6Address=pass:quotes[_ipAddress_]
----


== Parametro

[cols="2*"]
|===
| Parametri | Descrizione 


 a| 
`isnsIPv6Address`
 a| 
L'indirizzo IPv6 che si desidera utilizzare per il server iSNS.

|===


== Note

Il protocollo iSNS facilita il rilevamento, la gestione e la configurazione automatizzate dei dispositivi iSCSI e Fibre Channel su una rete TCP/IP. ISNS offre servizi intelligenti di rilevamento e gestione dello storage paragonabili a quelli delle reti Fibre Channel, che consentono a una rete IP commodity di funzionare in una capacità simile a quella di una rete SAN (Storage Area Network). ISNS semplifica inoltre l'integrazione perfetta delle reti IP e Fibre Channel, grazie alla sua capacità di emulare i servizi Fibre Channel Fabric e di gestire sia i dispositivi iSCSI che i dispositivi Fibre Channel. ISNS offre valore in qualsiasi rete di storage con dispositivi iSCSI, dispositivi Fibre Channel o qualsiasi combinazione.



== Livello minimo del firmware

7.10
