---
permalink: commands-a-z/set-drivechannel.html 
sidebar: sidebar 
keywords: set, drive, channel, status 
summary: Il comando Set DriveChannel definisce le prestazioni del canale del disco. 
---
= Imposta lo stato del canale di unità - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set driveChannel` command definisce le prestazioni del canale di trasmissione.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di amministratore del supporto.



== Sintassi

[source, cli]
----
set driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)]
status=(optimal | degraded)
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`driveChannel`
 a| 
Il numero identificativo del canale del disco per il quale si desidera impostare lo stato. I valori validi del canale del disco sono `1`, `2`, `3`, `4`, `5`, `6`, `7`, o. `8`. Racchiudere il numero del canale dell'unità tra parentesi quadre ([ ]).



 a| 
`status`
 a| 
La condizione del canale del disco. È possibile impostare lo stato del canale su `optimal` oppure `degraded`.

|===


== Note

Utilizzare `optimal` Opzione per riportare un canale disco degradato allo stato ottimale. Utilizzare `degraded` opzione quando si verificano problemi nel canale del disco e l'array di storage richiede tempo aggiuntivo per il trasferimento dei dati.



== Livello minimo del firmware

6.10

7.15 aggiunge l'aggiornamento all'identificatore del canale del disco.
