---
permalink: commands-a-z/set-snapgroup-mediascanenabled.html 
sidebar: sidebar 
keywords: set, snapshot, group, media, scan 
summary: Il comando Set SnapGroup mediaScanEnabled esegue una scansione dei supporti su un gruppo di snapshot. 
---
= Imposta la scansione del supporto del gruppo snapshot - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set snapGroup mediaScanEnabled` il comando esegue una scansione dei supporti su un gruppo di snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
mediaScanEnabled=(TRUE | FALSE)
redundancyCheckEnabled=(TRUE | FALSE)
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapGroup`
 a| 
Il nome del gruppo di snapshot su cui si desidera eseguire una scansione del supporto. Racchiudere il nome del gruppo di snapshot tra virgolette doppie (" ") all'interno delle parentesi quadre ([ ]).



 a| 
`mediaScanEnabled`
 a| 
L'impostazione per attivare o disattivare la scansione dei supporti per il volume. Per attivare la scansione dei supporti, impostare questo parametro su `TRUE`. Per disattivare la scansione dei supporti, impostare questo parametro su `FALSE`. (Se la scansione dei supporti è disattivata a livello di array di storage, questo parametro non ha alcun effetto).



 a| 
`redundancyCheckEnabled`
 a| 
L'impostazione per attivare o disattivare il controllo della ridondanza durante una scansione del supporto. Per attivare il controllo della ridondanza, impostare questo parametro su `TRUE`. Per disattivare il controllo della ridondanza, impostare questo parametro su `FALSE`.

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.



== Livello minimo del firmware

7.83
