---
permalink: commands-a-z/set-storagearray-host-io-protocol.html 
sidebar: sidebar 
keywords: set, storage, array, host, io, protocol 
summary: 'Il comando set storageArray hostIoProtocol configura il protocollo I/O host a livello dell"array di storage' 
---
= Imposta protocollo I/O host array di storage - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il  `set storageArray hostIoProtocol` comando configura il protocollo I/O dell'host a livello dell'array di storage.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo di Support Admin.



== Sintassi

[source, cli, subs="+macros"]
----
set storageArray hostIoProtocol={"FC" | "ISCSI" | "ISER" | "nvmeIb" | "nvmeFc" | "nvmeRoce" | "SAS" | "SRP"}
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`set storageArray hostIoProtocol`
 a| 
Consente di specificare quale protocollo I/O host utilizzare per il tuo array di storage. Le opzioni valide sono: FC, ISCSI, ISER, nvmeIb, nvmeFc, nvmeRoce, SAS o SRP.

|===


== Livello minimo del firmware

12,00
