---
permalink: commands-a-z/set-volumegroup.html 
sidebar: sidebar 
keywords: set, volume, group 
summary: Il comando Set VolumeGroup definisce le proprietà di un gruppo di volumi. 
---
= Impostare il gruppo di volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set volumeGroup` command definisce le proprietà di un gruppo di volumi.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
È necessario eseguire una sola operazione (aggiunta di dischi, modifica del livello RAID o modifica della proprietà del gruppo di volumi) per ogni comando. Non è possibile eseguire più di un'operazione con un singolo comando.

====


== Sintassi

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi per cui si desidera impostare le proprietà. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).



 a| 
`addDrives`
 a| 
La posizione dell'unità che si desidera aggiungere al gruppo di volumi. Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`raidLevel`
 a| 
Il livello RAID per il gruppo di volumi. I valori validi sono `0`, `1`, `3`, `5`, o. `6`.



 a| 
`owner`
 a| 
Controller proprietario del gruppo di volumi. Gli identificatori del controller validi sono `a` oppure `b`, dove `a` È il controller nello slot A , e. `b` Il controller si trova nello slot B. Utilizzare questo parametro solo se si desidera modificare il proprietario del gruppo di volumi.

|===


== Note

Gli errori di i/o dell'host possono causare gruppi di volumi con più di 32 volumi. Questa operazione potrebbe anche causare il riavvio del controller interno perché il periodo di timeout termina prima dell'impostazione della definizione del gruppo di volumi. Se si verifica questo problema, interrompere le operazioni di i/o dell'host e provare a eseguire nuovamente il comando.

Quando si utilizza questo comando, è possibile specificare solo uno dei parametri.

[NOTE]
====
Specifica di `addDrives` o il `raidLevel` parameter avvia un'operazione a esecuzione prolungata che non è possibile arrestare.

====
Il `addDrives` il parametro supporta sia i vassoi per dischi ad alta capacità che quelli a bassa capacità. Un vassoio per dischi ad alta capacità dispone di cassetti che trattengono le unità. I cassetti scorrono fuori dal vassoio dell'unità per consentire l'accesso alle unità. Un vassoio per unità a bassa capacità non dispone di cassetti. Per un vassoio dell'unità ad alta capacità, è necessario specificare l'identificativo (ID) del vassoio dell'unità, l'ID del cassetto e l'ID dello slot in cui si trova l'unità. Per un vassoio dell'unità a bassa capacità, è necessario specificare solo l'ID del vassoio dell'unità e l'ID dello slot in cui si trova un'unità. Per un vassoio dell'unità a bassa capacità, un metodo alternativo per identificare una posizione per un'unità consiste nel specificare l'ID del vassoio dell'unità, impostare l'ID del cassetto su `0`E specificare l'ID dello slot in cui si trova un'unità.



== Risoluzione dei problemi

Se si tenta di espandere gruppi di volumi di grandi dimensioni aggiungendo unità, denominate anche Dynamic Capacity Expansion (DCE), potrebbe non riuscire e viene visualizzato il seguente messaggio:

`Return code: Error 26 - The modification operation cannot complete because of the number of drives in the volume group and the segment size of the associated volumes. Reduce the segment size of all volumes in the volume group to 128 KB or below using the Change Segment Size option. Then, retry the operation.`

I sistemi che eseguono il firmware 7.35.xx.xx potrebbero non riuscire e potrebbe essere visualizzato il seguente messaggio invece di quello indicato in precedenza:

`Return code: Error 462 - A SYMbol procedure could not be carried out because the firmware could not allocate sufficient cache memory. Operation when error occurred: PROC_startVolum`

Oltre ai messaggi sopra riportati, potrebbe verificarsi un evento MEL (Major Event Log) che indica una cache insufficiente per completare l'operazione DCE.

Questo problema potrebbe verificarsi su qualsiasi controller che esegue il firmware 7.xx.

DCE richiede una quantità di memoria sufficiente per il buffer dei dati letti dal volume originale e dei dati da scrivere nel volume espanso. Una combinazione del numero di dischi nell'operazione di espansione, delle dimensioni dello stripe e dell'attivazione delle operazioni mirror potrebbe causare la mancanza di memoria sufficiente per completare l'operazione DCE.

Se si riscontra la situazione sopra descritta, le possibili soluzioni sono le seguenti:

* Creare il gruppo di volumi delle dimensioni desiderate utilizzando altri dischi non assegnati.
* Eliminare il gruppo di volumi corrente, quindi ricreare il gruppo di volumi con il numero di dischi desiderato.
* Ridurre la dimensione del segmento utilizzato e riprovare l'operazione.
* Se possibile, aggiungere ulteriore memoria al controller e riprovare l'operazione.




== Livello minimo del firmware

7.10 aggiunge funzionalità RAID 6.

7.30 rimuove `availability` parametro.

7.60 aggiunge `drawerID` input dell'utente.
