---
permalink: commands-a-z/set-storagearray-odxenabled.html 
sidebar: sidebar 
keywords: enable, disable, odx 
summary: 'Il comando Set StorageArray odxEnabled attiva o disattiva Offloaded Data Transfer (ODX) per uno storage array.' 
---
= Abilitare o disabilitare ODX - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set storageArray odxEnabled` Il comando attiva o disattiva il trasferimento dati offloaded (ODX) per un array di storage.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Support Admin.



== Contesto

Lo storage array viene fornito con ODX attivato. Utilizzare questo comando per disattivare ODX se non si desidera eseguire ODX o se ODX sta causando problemi con lo storage array. L'unico array di storage interessato è l'array di storage su cui viene eseguito il comando.



== Sintassi

[source, cli]
----
set storageArray odxEnabled=(TRUE | FALSE)
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`odxEnabled`
 a| 
L'impostazione per attivare o disattivare ODX. Per attivare ODX, impostare questo parametro su `TRUE`. Per disattivare ODX, impostare questo parametro su `FALSE`. Per impostazione predefinita, ODX è attivato.

|===


== Note

ODX offre un metodo per trasferire dati senza utilizzare operazioni di lettura e scrittura bufferizzate e non richiede il coinvolgimento diretto dell'host nell'operazione di trasferimento dati. Quando ODX non è abilitato, i dati vengono letti dalla memoria di origine all'host e quindi scritti sulla memoria di destinazione dall'host. Con ODX abilitato, le operazioni di trasferimento dati sono gestite direttamente dall'infrastruttura di storage. I dati vengono spostati direttamente dalla memoria di origine alla memoria di destinazione all'interno dello stesso array, bypassando l'host.



== Livello minimo del firmware

8.20
