---
permalink: commands-a-z/set-snapvolume.html 
sidebar: sidebar 
keywords: rename, snapshot, volume 
summary: Il comando set snapVolume rinomina un volume di snapshot esistente. 
---
= Rinomina volume snapshot - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set snapVolume` il comando rinomina un volume di snapshot esistente.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Sintassi

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] userLabel=pass:quotes["_snapImageVolumeName_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapVolume`
 a| 
Il nome del volume snapshot che si desidera rinominare. Racchiudere il nome del volume snapshot tra virgolette doppie (" ") all'interno di parentesi quadre ([ ]).



 a| 
`userLabel`
 a| 
Un nuovo nome che si desidera assegnare al volume di snapshot. Racchiudere il nome del nuovo volume snapshot tra virgolette doppie (" ").

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.



== Livello minimo del firmware

7.83
