---
permalink: commands-a-z/set-autosupport-https-delivery-method.html 
sidebar: sidebar 
keywords: 'Specify AutoSupport HTTP(S) delivery method' 
summary: 'Il comando set StorageArray AutoSupport deliveryMethod imposta il metodo di consegna per l"invio di messaggi AutoSupport a HTTP(S).' 
---
= Specificare il metodo di consegna http(s) di AutoSupport - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set storageArray autoSupport deliveryMethod` Command imposta il metodo di invio dei messaggi AutoSupport a HTTP(S).



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di amministratore del supporto.



== Sintassi

[source, cli, subs="+macros"]
----

set storageArray autoSupport deliveryMethod=email mailRelayServer="mail.example.com" senderEmail="sender@example.com"
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`deliveryMethod`
 a| 
Consente all'utente di specificare il metodo di consegna per la raccolta AutoSupport. Le scelte valide sono:

* e-mail
* HTTPS


[NOTE]
====
Se il metodo e-mail è configurato, la diagnostica AutoSupport su richiesta e la diagnostica remota verranno disattivate.

====


 a| 
`direct`
 a| 
Consente all'utente di connettersi direttamente ai sistemi di supporto tecnico di destinazione utilizzando il protocollo HTTP o HTTPS.



 a| 
`proxyConfigScript`
 a| 
Consente all'utente di specificare la posizione di un file di script PAC (Proxy Auto-Configuration)



 a| 
`proxyServer`
 a| 
Consente all'utente di specificare i dettagli del server proxy HTTP(S) necessari per stabilire la connessione con il sistema di supporto tecnico di destinazione.



 a| 
`hostAddress`
 a| 
Consente all'utente di specificare l'indirizzo host del server proxy. Obbligatorio se si utilizza proxyServer.



 a| 
`portNumber`
 a| 
Consente all'utente di specificare il numero di porta del server proxy. Obbligatorio se si utilizza proxyServer.



 a| 
`username`
 a| 
Consente all'utente di specificare il nome utente del server proxy, se configurato.



 a| 
`password`
 a| 
Consente all'utente di specificare la password del server proxy, se configurato.

|===


== Livello minimo del firmware

8.40



== Esempi

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP direct;"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP
proxyConfigScript=\"http://company.com/~username/proxy.pac\";"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTPS
proxyServer hostAddress=10.117.12.112 portNumber=8080 userName=\"tracyt\" password=\"1234456\";"

SMcli completed successfully.
----


== Verifica

Inviare un messaggio di prova utilizzando `start storageArray autoSupport deliveryTest` per verificare che i metodi di consegna siano impostati correttamente.



== Livello minimo del firmware

8.40
