---
permalink: commands-a-z/set-consistency-group-attributes.html 
sidebar: sidebar 
keywords: set, consistency, group, attributes 
summary: Il comando set consistencyGroup definisce le proprietà di un gruppo di coerenza snapshot. 
---
= Impostare gli attributi del gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `set consistencyGroup` il comando definisce le proprietà di un gruppo di coerenza snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing, subs="+macros"]
----
set consistencyGroup pass:quotes[["_consistencyGroupName_"]]
[userLabel=pass:quotes["_consistencyGroupName_"]]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`consistencyGroupName`
 a| 
Il nome del gruppo di coerenza per cui si stanno impostando le proprietà. Racchiudere il nome del gruppo di coerenza tra virgolette doppie (" ") tra parentesi quadre ([ ]).



 a| 
`userLabel`
 a| 
Il nuovo nome che si desidera assegnare al gruppo di coerenza snapshot. Racchiudere il nome del nuovo gruppo di coerenza tra virgolette doppie (" ").



 a| 
`repositoryFullPolicy`
 a| 
Come si desidera che l'elaborazione degli snapshot continui se i volumi del repository degli snapshot sono pieni. È possibile scegliere di non eseguire operazioni di scrittura nel volume di base (`failBaseWrites`) o eliminare (eliminare) le immagini snapshot  `purgeSnapImages`). L'azione predefinita è `purgeSnapImages`.



 a| 
`repositoryFullLimit`
 a| 
La percentuale di capacità del repository alla quale viene visualizzato un avviso che indica che il volume del repository snapshot è quasi pieno. USA valori interi. Ad esempio, un valore di 70 significa 70%. Il valore predefinito è 75.



 a| 
`autoDeleteLimit`
 a| 
Ciascun gruppo di coerenza può essere configurato in modo da eseguire l'eliminazione automatica delle immagini snapshot per mantenere il numero totale di immagini snapshot nel gruppo di snapshot a un livello o al di sotto di quello designato. Quando questa opzione è attivata, ogni volta che viene creata una nuova immagine snapshot nel gruppo di snapshot, il sistema elimina automaticamente l'immagine snapshot meno recente nel gruppo per rispettare il valore limite. Questa azione libera la capacità del repository in modo che possa essere utilizzata per soddisfare i requisiti di copy-on-write per le immagini snapshot rimanenti.



 a| 
`rollBackPriority`
 a| 
La priorità delle operazioni di rollback per un gruppo di coerenza mentre lo storage array è operativo. I valori validi sono `highest`, `high`, `medium`, `low`, o. `lowest`.

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.

Quando si utilizza questo comando, è possibile specificare uno o più parametri. Tuttavia, non è necessario utilizzare tutti i parametri.

La priorità di rollback definisce la quantità di risorse di sistema da allocare all'operazione di rollback a scapito delle prestazioni del sistema. Un valore di `high` Indica che l'operazione di rollback ha la priorità su tutti gli altri i/o host Un valore di `low` Indica che l'operazione di rollback deve essere eseguita con un impatto minimo sull'i/o host



== Eliminazione automatica

È possibile configurare ciascun gruppo di snapshot in modo che esegua l'eliminazione automatica delle relative immagini snapshot per mantenere il numero totale di immagini snapshot nel gruppo di snapshot pari o inferiore a un numero massimo di immagini. Quando il numero di immagini snapshot nel gruppo di snapshot è al limite massimo, il `autoDeleteLimit` il parametro elimina automaticamente le immagini snapshot ogni volta che viene creata una nuova immagine snapshot nel gruppo di snapshot. Il `autoDeleteLimit` il parametro elimina le immagini snapshot meno recenti nel gruppo di snapshot fino a quando non viene raggiunto il numero massimo di immagini definito con il parametro. L'eliminazione delle immagini Snapshot in questo modo libera la capacità del repository in modo che possa essere utilizzata per soddisfare i requisiti di copy-on-write per le immagini Snapshot rimanenti.



== Livello minimo del firmware

7.83
