---
permalink: commands-a-z/set-hostport.html 
sidebar: sidebar 
keywords: set, host, port 
summary: Il comando set hostPort modifica le proprietà di una porta host. 
---
= Impostare la porta host
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `set hostPort` il comando modifica le proprietà di una porta host.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Questo comando non funziona in un ambiente iSCSI, dove le porte host sono considerate iniziatori. Utilizzare invece il `set iscsiInitiator` comando. Vedere xref:set-iscsiinitiator.adoc[Impostare iSCSI Initiator].

====


== Sintassi

[listing, subs="+macros"]
----
set hostPort pass:quotes[[_portLabel_]] userLabel=pass:quotes[_newPortLabel_]
[host=pass:quotes[_hostName_]]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`hostPort`
 a| 
Il nome della porta host per la quale si desidera modificare il tipo di host o per la quale si desidera creare un nuovo nome. Racchiudere il nome della porta host tra parentesi quadre ([ ]). Se il nome della porta host contiene caratteri o numeri speciali, racchiudere il nome della porta host tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`userLabel`
 a| 
Il nuovo nome che si desidera assegnare alla porta host. Racchiudere il nuovo nome della porta host tra virgolette doppie (" ").



 a| 
`host`
 a| 
Il nome dell'host per cui si sta definendo una porta host HBA o HCA. Racchiudere il nome host tra virgolette doppie (" ").

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per l'etichetta utente. Le etichette dell'utente possono contenere un massimo di 30 caratteri.



== Livello minimo del firmware

6.10
