---
permalink: commands-a-z/set-cgsnapvolume.html 
sidebar: sidebar 
keywords: set, consistency, group, snapshot, volume 
summary: Il comando set cgSnapVolume crea un nome univoco per un volume snapshot di un gruppo di coerenza. 
---
= Imposta volume snapshot gruppo di coerenza - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set cgSnapVolume` il comando crea un nome univoco per un volume di snapshot di un gruppo di coerenza.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Sintassi

[source, cli, subs="+macros"]
----
set cgSnapVolume pass:quotes[[_cgSnapVolumeName_]]
userLabel=pass:quotes["_cgSnapVolumeName_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`cgSnapVolume`
 a| 
Il nome del volume del gruppo di coerenza che si desidera rinominare. Racchiudere il nome del volume snapshot del gruppo di coerenza tra parentesi quadre ([ ]).



 a| 
`userLabel`
 a| 
Il nuovo nome che si desidera assegnare al volume di snapshot nel gruppo di coerenza. Racchiudere il nome del nuovo volume snapshot tra virgolette doppie (" ").

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.



== Livello minimo del firmware

7.83
