---
permalink: commands-a-z/set-storagearray-syslog.html 
sidebar: sidebar 
keywords: update, storage, array, syslog, configuration 
summary: 'Il comando set StorageArray syslog consente di modificare l"indirizzo del server syslog, il protocollo o il numero di porta.' 
---
= Aggiornare la configurazione syslog dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set storageArray syslog` il comando consente di modificare l'indirizzo del server syslog, il protocollo o il numero di porta.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Sintassi

[source, cli]
----
set storageArray syslog id="<id>"
serverAddress="<address>"
port=<port> protocol=("udp" | "tcp" | "tls")
components=(componentName=("auditLog") ...)
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`serverAddress`
 a| 
Nome host o indirizzo IP del ricevitore syslog.



 a| 
`port`
 a| 
Numero di porta del ricevitore syslog.



 a| 
`protocol`
 a| 
Protocollo di trasmissione syslog. I valori accettabili includono UDP, TCP o TLS.



 a| 
`components`
 a| 
Elenco delle voci dei componenti che verranno registrate nel server syslog. Attualmente, sono supportati solo i registri di controllo.



 a| 
`componentName`
 a| 
Nome del componente; attualmente è supportato solo "AuditLog".

|===


=== Esempio

[listing]
----
SMcli -n Array1 -c "set storageArray syslog
id=\"331998fe-3154-4489-b773-b0bb60c6b48e\"
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e Server Address: 192.168.2.1
Port: 514 Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----


== Livello minimo del firmware

8.42
