---
permalink: commands-a-z/set-drive-nativestate.html 
sidebar: sidebar 
keywords: set, foreign, drive, native 
summary: 'Il comando set drive nativeState aggiunge le unità mancanti (estranee) al gruppo di volumi originale e le rende parte del gruppo di volumi nel nuovo array di storage.' 
---
= Impostare disco esterno su nativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set drive nativeState` il comando aggiunge le unità mancanti (esterne) al gruppo di volumi originale e le rende parte del gruppo di volumi nel nuovo array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Un disco viene considerato nativo quando fa parte di un gruppo di volumi in un array di storage. Un disco viene considerato estraneo quando non appartiene a un gruppo di volumi in un array di storage o quando non viene importato con i dischi di un gruppo di volumi che vengono trasferiti a un nuovo array di storage. Quest'ultimo errore crea un gruppo di volumi incompleto sul nuovo array di storage.

Utilizzare questa operazione solo per il ripristino di emergenza: Quando uno o più dischi devono essere modificati dallo stato di un disco esterno e riportati allo stato nativo all'interno del gruppo di volumi originale.

[NOTE]
====
*Possibile corruzione dei dati o perdita di dati* -- l'utilizzo di questo comando per motivi diversi da quanto indicato in precedenza potrebbe causare la perdita dei dati senza notifica.

====


== Sintassi

[source, cli, subs="+macros"]
----
set (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_)] | drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)] |
allDrives) nativeState
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`drive` oppure `drives`
 a| 
Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800, E5700, EF600 e EF300 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`allDrives`
 a| 
L'impostazione per selezionare tutte le unità.

|===


== Note

Il `drive` il parametro supporta sia i vassoi per dischi ad alta capacità che quelli a bassa capacità. Un vassoio per dischi ad alta capacità dispone di cassetti che trattengono le unità. I cassetti scorrono fuori dal vassoio dell'unità per consentire l'accesso alle unità. Un vassoio per unità a bassa capacità non dispone di cassetti. Per un vassoio dell'unità ad alta capacità, è necessario specificare l'identificativo (ID) del vassoio dell'unità, l'ID del cassetto e l'ID dello slot in cui si trova l'unità. Per un vassoio dell'unità a bassa capacità, è necessario specificare solo l'ID del vassoio dell'unità e l'ID dello slot in cui si trova un'unità. Per un vassoio dell'unità a bassa capacità, un metodo alternativo per identificare una posizione per un'unità consiste nel specificare l'ID del vassoio dell'unità, impostare l'ID del cassetto su `0`E specificare l'ID dello slot in cui si trova un'unità.



== Livello minimo del firmware

7.10

7.60 aggiunge `drawerID` input dell'utente.
