---
permalink: commands-a-z/set-drive-securityid.html 
sidebar: sidebar 
keywords: set, fips, drive, security, identifier 
summary: Il comando set drive SecurityID viene utilizzato per ripristinare le impostazioni originali del produttore di un disco FIPS. 
---
= Imposta l'identificatore di sicurezza dell'unità FIPS - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set drive securityID` Il comando viene utilizzato per ripristinare le impostazioni originali del produttore di un disco FIPS.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore della sicurezza.



== Contesto

[NOTE]
====
Questo comando ripristina un disco FIPS alle impostazioni originali del produttore e cancella tutti i dati del disco esistenti. Questa operazione è completamente irreversibile. Questo potrebbe essere necessario se il disco è bloccato a causa di un file della chiave di sicurezza non valido o mancante o di una password sconosciuta. Tutti i dati del disco esistenti verranno cancellati.

====
Per cancellare un disco FDE, utilizzare `start secureErase` comando.



== Sintassi

[source, cli, subs="+macros"]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`drive`
 a| 
Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`securityID`
 a| 
L'ID di sicurezza dell'unità da cancellare, in forma di stringa. Questa stringa può contenere un massimo di 32 caratteri. La forma dell'ID di sicurezza varia in base al produttore.

[NOTE]
====
Per trovare l'ID di sicurezza, rimuovere l'unità e leggere l'ID di sicurezza sull'etichetta del contenitore.

====
|===


== Note

Il `drive` il parametro supporta sia i vassoi per dischi ad alta capacità che quelli a bassa capacità. Un vassoio per dischi ad alta capacità dispone di cassetti che trattengono le unità. I cassetti scorrono fuori dal vassoio dell'unità per consentire l'accesso alle unità. Un vassoio per unità a bassa capacità non dispone di cassetti. Per un vassoio dell'unità ad alta capacità, è necessario specificare l'identificativo (ID) del vassoio dell'unità, l'ID del cassetto e l'ID dello slot in cui si trova l'unità. Per un vassoio dell'unità a bassa capacità, è necessario specificare solo l'ID del vassoio dell'unità e l'ID dello slot in cui si trova un'unità. Per un vassoio dell'unità a bassa capacità, un metodo alternativo per identificare una posizione per un'unità consiste nel specificare l'ID del vassoio dell'unità, impostare l'ID del cassetto su `0`E specificare l'ID dello slot in cui si trova un'unità.



== Esempio

[listing]
----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----


== Livello minimo del firmware

8.25
