---
permalink: commands-a-z/set-storagearray-icmppingresponse.html 
sidebar: sidebar 
keywords: set, storage, array, icmp, response 
summary: Il comando set StorageArray icmpPingResponse restituisce i valori predefiniti per le impostazioni negoziabili per sessioni e connessioni, che rappresentano il punto di partenza per lo storage array per le negoziazioni. 
---
= Imposta la risposta ICMP dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set storageArray icmpPingResponse` command restituisce i valori predefiniti per le impostazioni negoziabili per sessioni e connessioni, che rappresentano il punto di partenza per l'array di storage per le negoziazioni.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli]
----
set storageArray icmpPingResponse=(TRUE | FALSE)
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`icmpPingResponse`
 a| 
Questo parametro attiva o disattiva i messaggi Echo Request. Impostare il parametro su `TRUE` Per attivare i messaggi Echo Request. Impostare il parametro su `FALSE` Per disattivare i messaggi Echo Request.

|===


== Note

Il protocollo ICMP (Internet Control message Protocol) viene utilizzato dai sistemi operativi di una rete per inviare messaggi di errore, pacchetti di test e messaggi informativi relativi all'IP, ad esempio un servizio richiesto non disponibile o che non è stato possibile raggiungere un host o un router. Il comando di risposta ICMP invia messaggi ICMP Echo Request e riceve messaggi ICMP Echo Response per determinare se un host è raggiungibile e il tempo necessario per i pacchetti da e verso tale host.



== Livello minimo del firmware

7.10
