---
permalink: commands-a-z/set-iscsiinitiator.html 
sidebar: sidebar 
keywords: set, iscsi, initiator 
summary: Il comando set iscsiInitialator imposta gli attributi per un iniziatore iSCSI. 
---
= Impostare iSCSI Initiator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set iscsiInitiator` Command imposta gli attributi per un iniziatore iSCSI.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.

[NOTE]
====
Questo comando è obsoleto e viene sostituito da xref:set-initiator.adoc[Inizializzatore set] comando.

====


== Sintassi

[source, cli, subs="+macros"]
----
set iscsiInitiator (pass:quotes[["_initiatorUserLabel_"]] | <"_iscsiInitiatorName_">)
(userLabel=pass:quotes["_newName_"] |
host=pass:quotes["_newHostName_"] |
chapSecret=pass:quotes["_newSecurityKey_"])
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`initiatorUserLabel`
 a| 
L'etichetta utente iscsi Initiator dell'iSCSI Initiator per cui si desidera impostare gli attributi. Racchiudere l'etichetta utente di iSCSI Initiator tra virgolette doppie (" ") tra parentesi quadre ([ ]).

[NOTE]
====
Iniziare l'etichetta dell'utente iniziatore con il nome host a cui è connessa la porta host. Poiché su un host possono essere presenti più di un identificatore di porta host, utilizzare un suffisso univoco per l'ID di porta host. Se il nome host è `ICTM1590S02H1` l'etichetta initiator viene visualizzata come segue:

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`iscsiInitiatorName`
 a| 
Il nome dell'iniziatore per cui si desidera impostare gli attributi. Racchiudere il `iscsiInitiatorName` tra virgolette doppie (" ") all'interno delle parentesi angolari (< >).

[NOTE]
====
Il `iscsiInitiatorName` È il nome iSCSI qualificato (iqn). Un esempio:

====
[listing]
----
set iscsiInitiator <"iqn.2016-11.com.vmware.iscsi:ictm1509s02h1">
----


 a| 
`userLabel`
 a| 
La nuova etichetta utente che si desidera utilizzare per iSCSI Initiator. Racchiudere la nuova etichetta utente tra virgolette doppie (" ").

[NOTE]
====
Si consiglia di iniziare l'etichetta utente iniziatore con il nome host a cui è connessa la porta host. Poiché su un host possono essere presenti più di un identificatore di porta host, utilizzare un suffisso univoco per l'ID di porta host. Se il nome host è `ICTM1590S02H1` di seguito viene riportato un esempio dell'etichetta utente dell'iniziatore:

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`host`
 a| 
Il nome del nuovo host a cui è connessa la porta host. Racchiudere il nome host tra virgolette doppie (" "). Di seguito è riportato un esempio:

[listing]
----
["ICTM1590S02H2"]
----


 a| 
`chapSecret`
 a| 
La chiave di sicurezza che si desidera utilizzare per autenticare una connessione peer. Racchiudere la chiave di sicurezza tra virgolette doppie (" ").

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, trattini e caratteri di sottolineatura per i nomi. I nomi possono avere un massimo di 30 caratteri.

Challenge Handshake Authentication Protocol (CHAP) è un protocollo che autentica il peer di una connessione. Il CHAP si basa sui peer che condividono un _segreto_. Un segreto è una chiave di sicurezza simile a una password.

Utilizzare `chapSecret` parametro per impostare le chiavi di sicurezza per gli iniziatori che richiedono un'autenticazione reciproca. Il segreto CHAP deve essere compreso tra 12 e 57 caratteri. Questa tabella elenca i caratteri validi.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Spazio
 a| 
!
 a| 
"
 a| 
N.
 a| 
€
 a| 
%
 a| 
&
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
<
 a| 
=
 a| 
>
 a| 
?
 a| 
@
 a| 
R
 a| 
B
 a| 
C.



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
IO
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P.
 a| 
D
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V.
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[.



 a| 
.
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
r
 a| 
b
 a| 
c.
 a| 
d
 a| 
e
 a| 
f
 a| 
g



 a| 
h
 a| 
io
 a| 
j
 a| 
k
 a| 
l
 a| 
m
 a| 
n
 a| 
o
 a| 
p.
 a| 
d
 a| 
r
 a| 
s



 a| 
t
 a| 
u
 a| 
v.
 a| 
w
 a| 
x
 a| 
y
 a| 
z
 a| 
{
 a| 
|
 a| 
}
 a| 
~
 a| 

|===


== Livello minimo del firmware

7.10

8.41 questo comando è obsoleto.
