---
permalink: commands-a-z/set-snapvolume-increase-decreaserepositorycapacity.html 
sidebar: sidebar 
keywords: set, snapshot, volume, repository, capacity 
summary: Il comando Set SnapVolume Invit/DideceRepositoryCapacity aumenta o diminuisce la capacità di un volume di repository di un volume di snapshot. 
---
= Impostare la capacità del volume del repository del volume Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set snapVolume increase/decreaseRepositoryCapacity` il comando aumenta o diminuisce la capacità di un volume di repository di un volume di snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi per aumentare la capacità

[source, cli, subs="+macros"]
----
set snapVolume[“snapVolumeName”] increaseRepositoryCapacity
(repositoryVolumes="repos_xxxx" |
repositoryVolumes=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]] |
repositoryVolumes=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]])
----


== Sintassi per ridurre la capacità

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] decreaseRepositoryCapacity
count=pass:quotes[_numberOfVolumes_]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapVolume`
 a| 
Il nome del volume di snapshot per il quale si stanno impostando le proprietà. Racchiudere l'identificatore del volume snapshot tra virgolette doppie (" ") all'interno di parentesi quadre ([ ]).



 a| 
`repositoryVolume`
 a| 
Il nome del volume di repository per il quale si desidera aumentare la capacità. Un volume standard disponibile viene aggiunto al volume di repository per aumentare la capacità del volume di repository.

Sono disponibili due opzioni per definire il nome di un volume di repository:

* Utilizzare un volume repository esistente: Nome
* Creare un nuovo volume di repository quando si esegue questo comando


Il nome di un volume di repository esistente è composto da due parti:

* Il termine "repos"
* Identificatore numerico a quattro cifre assegnato al nome del volume del repository


Racchiudere il nome del volume di repository esistente tra virgolette doppie (" ").

Se si desidera creare un nuovo volume di repository quando si esegue questo comando, è necessario immettere il nome di un gruppo di volumi o di un pool di dischi in cui si desidera creare il volume di repository. In alternativa, è anche possibile definire la capacità del volume di repository. Se si desidera definire la capacità, è possibile utilizzare i seguenti valori:

* Un valore intero che rappresenta una percentuale della capacità del volume di base
* Un valore di frazione decimale che rappresenta una percentuale della capacità del volume di base
* Una dimensione specifica per il volume di repository. Le dimensioni sono definite in unità di `bytes`, `KB`, `MB`, `GB`, o. `TB`.


Se non si utilizza l'opzione di capacità, il software di gestione dello storage imposta la capacità sul 20% della capacità del volume di base.

Racchiudere il nome del nuovo volume di repository tra parentesi.



 a| 
`count`
 a| 
Il numero di volumi che si desidera rimuovere. USA valori interi.

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.

Un volume di repository di snapshot è un volume espandibile strutturato come un insieme concatenato di un massimo di 16 entità di volume standard. Inizialmente, un volume di repository espandibile ha un solo elemento. La capacità del volume di repository espandibile è esattamente quella del singolo elemento. È possibile aumentare la capacità di un volume di repository espandibile allegando volumi standard aggiuntivi. La capacità del volume del repository espandibile composito diventa quindi la somma delle capacità di tutti i volumi standard concatenati.

Un volume di repository di gruppi di snapshot deve soddisfare un requisito di capacità minimo che corrisponde alla somma dei seguenti requisiti:

* 32 MB per supportare un overhead fisso per il gruppo di snapshot e per l'elaborazione copy-on-write.
* Capacità per l'elaborazione del rollback, pari a 1/5000esimo della capacità del volume di base.


La capacità minima viene utilizzata dal firmware del controller e dal software di gestione dello storage.



== Livello minimo del firmware

7.83
