---
permalink: commands-a-z/set-storagearray-localusername.html 
sidebar: sidebar 
keywords: set, storage, array, local, user, password, symbol 
summary: Il comando set StorageArray localUsername e il comando set StorageArray symbol consentono di impostare una password locale per il nome utente o un simbolo per un ruolo specifico. 
---
= Impostare la password utente locale o la password del simbolo dello storage array
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `set storageArray localUsername` e il `set storageArray symbol` Comando consente di impostare una password per il nome utente locale o una password per il simbolo per un ruolo specifico.



== Array supportati

Questo comando si applica a un singolo array di storage E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Storage Admin, Support Admin, Security Admin o Storage Monitor.



== Sintassi

[listing, subs="+macros"]
----
set storageArray (localUsername=pass:quotes[{ _admin_ | _storage_ | _security_ | _support_ | _monitor_}]
| symbol [userRole={admin | monitor}])
password="string" adminPassword="string"
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`localUsername`
 a| 
Consente di specificare l'utente per la modifica della password. Le scelte valide sono: `admin`, `storage`, `support`, `monitor`, e. `security`.



 a| 
`symbol`
 a| 
Consente di modificare la password del simbolo. Le scelte valide sono: `admin` e. `monitor`.

[NOTE]
====
Questo è il comando replacement per il deprecato `set storageArray password` comando.

====


 a| 
`password`
 a| 
Consente di specificare la password per il ruolo.



 a| 
`adminPassword`
 a| 
Consente di specificare la password admin, necessaria per impostare una nuova password.

|===


== Esempi

[listing]
----

SMcli -n Array1 -c "set storageArray localUsername=storage password="newPassword" adminPassword="theAdminPassword";"
SMcli -n Array1 -c "set storageArray localUsername=admin password="newAdminPassword" adminPassword="theAdminPassword";"
SMcli -n Array1 -c "set storageArray symbol userRole=admin password="newSymbolPassword" adminPassword="theAdminPassword";"

SMcli completed successfully.
----


== Livello minimo del firmware

8.40 aggiunge il comando.
