---
permalink: commands-a-z/set-snmptrapdestination-trapreceiverip.html 
sidebar: sidebar 
keywords: update, snmp, trap, destination 
summary: 'Il comando set snmpTrapDestination trapReceiverIP attiva o disattiva l"invio di messaggi di errore di autenticazione per una destinazione di trap SNMP. L"errore si verifica quando l"agente SNMP ha ricevuto un messaggio da un gestore SNMP, ma il messaggio conteneva un nome di comunità o un nome utente non valido.' 
---
= Aggiorna la destinazione della trap SNMP - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `set snmpTrapDestination trapReceiverIP` Il comando attiva o disattiva l'invio di messaggi di errore di autenticazione per una destinazione trap SNMP. L'errore si verifica quando l'agente SNMP ha ricevuto un messaggio da un gestore SNMP, ma il messaggio conteneva un nome di comunità o un nome utente non valido.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di amministratore del supporto.



== Sintassi

[source, cli, subs="+macros"]
----
set snmpTrapDestination trapReceiverIP=ipAddress
(communityName=pass:quotes["_communityName_"] | (userName=pass:quotes["_userName_"] [engineId=(local | engineId)]))
[sendAuthenticationFailureTraps=(TRUE | FALSE)]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`trapReceiverIP`
 a| 
L'indirizzo IP del gestore SNMP a cui si desidera inviare i messaggi trap.



 a| 
`communityName`
 a| 
Il nome della community SNMP per la quale si desidera inviare messaggi trap.



 a| 
`userName`
 a| 
Il nome dell'utente SNMP per cui si desidera inviare messaggi trap.



 a| 
`engineId`
 a| 
L'ID motore dell'utente SNMP per cui si desidera inviare messaggi trap. L'ID motore è obbligatorio se sono presenti più utenti USM con lo stesso nome utente. Il valore può essere "[.code]``local``" Specificare l'agente SNMP locale è l'agente autorevole o una stringa di cifre esadecimali per specificare un ID del motore dell'agente SNMP remoto.



 a| 
`sendAuthenticationFailureTraps`
 a| 
Questo parametro attiva o disattiva l'invio di messaggi di errore di autenticazione a un gestore SNMP. Per inviare messaggi di errore di autenticazione, impostare il parametro su `TRUE`. Per impedire l'invio di messaggi di errore di autenticazione, impostare il parametro su `FALSE`. L'impostazione predefinita è `TRUE`.

|===


== Livello minimo del firmware

8.30
