---
permalink: commands-a-z/show-volumecopy-source-targetcandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, target, candidates 
summary: 'Il comando show VolumeCopy source targetCandidate restituisce informazioni sui volumi candidati che è possibile utilizzare come destinazione per un"operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.' 
---
= Mostra candidati di destinazione per la copia del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volumeCopy source targetCandidates` il comando restituisce informazioni sui volumi candidati che è possibile utilizzare come destinazione per un'operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.



== Sintassi

[source, cli, subs="+macros"]
----
show volumeCopy source pass:quotes[["_sourceName_"]] targetCandidates
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`source`
 a| 
Il nome del volume di origine per il quale si sta tentando di trovare un volume di destinazione candidato. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiudere il nome del volume tra virgolette doppie (" ") all'interno di parentesi quadre.

|===