---
permalink: commands-a-z/show-volume-actionprogress.html 
sidebar: sidebar 
keywords: show, volume, action, progress 
summary: 'Il comando show volume actionProgress restituisce informazioni sull"azione del volume e sulla quantità dell"operazione a esecuzione prolungata completata per un"operazione a esecuzione prolungata su un volume.' 
---
= Mostra l'avanzamento dell'azione del volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `show volume actionProgress` command restituisce informazioni sull'azione del volume e sulla quantità dell'operazione a esecuzione prolungata completata per un'operazione a esecuzione prolungata su un volume.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Contesto

[NOTE]
====
Con la versione del firmware 7.77, il `show volume actionProgress` comando obsoleto. Sostituire questo comando con `show storageArray longRunningOperations`.

====
La quantità di operazioni a lungo termine viene indicata come percentuale (ad esempio, 25 significa che il 25% dell'operazione a lungo termine è completata).



== Sintassi

[listing, subs="+macros"]
----
show volume pass:quotes[[_volumeName_]] actionProgress
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volume`
 a| 
Il nome di un volume per il quale si desidera recuperare informazioni su un'operazione a esecuzione prolungata. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.

|===


== Livello minimo del firmware

5.43
