---
permalink: commands-a-z/show-snapimage.html 
sidebar: sidebar 
keywords: show, snapshot, image 
summary: Il comando show SnapImage restituisce informazioni sulle immagini snapshot create in precedenza da un utente. 
---
= Mostra immagine istantanea - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show snapImage` il comando restituisce informazioni sulle immagini snapshot create in precedenza da un utente.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi per la visualizzazione di un'immagine snapshot specifica

[source, cli, subs="+macros"]
----
show (allSnapImages | snapImage pass:quotes[["_snapImageName_"]] |
snapImages pass:quotes[["_snapImageName1_" ... "_snapImageNamen_"]])
[summary]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allSnapImages`
 a| 
Il parametro per restituire informazioni su tutte le immagini snapshot nell'array di storage.



 a| 
`snapImage`
 a| 
Il nome di un'immagine snapshot per la quale si desidera recuperare le informazioni. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` -- utilizzare questa opzione per visualizzare l'ultima immagine istantanea creata nel gruppo di snapshot.
* `OLDEST` -- utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ") tra parentesi quadre ([ ]).



 a| 
`snapImages`
 a| 
I nomi di diverse immagini snapshot per cui si desidera recuperare le informazioni. Inserire i nomi delle immagini snapshot utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Racchiudere ciascuno dei nomi tra virgolette doppie (" ").
* Separare ciascuno dei nomi con uno spazio.




 a| 
`summary`
 a| 
Questo parametro restituisce un elenco conciso di informazioni sulle immagini snapshot.

|===


== Note

Il nome di un'immagine istantanea ha due parti separate da due punti (:):

* L'identificatore del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera visualizzare l'immagine snapshot 12345 in un gruppo di snapshot con il nome snapGroup1, utilizzare questo comando:

[listing]
----
show snapImage ["snapGroup1:12345"];
----
Per visualizzare l'immagine snapshot più recente in un gruppo di snapshot con il nome snapGroup1, utilizzare questo comando:

[listing]
----
show snapImage ["snapGroup1:newest"];
----
Per visualizzare le immagini snapshot in diversi gruppi di coerenza snapshot con i nomi snapGroup1, snapGroup2 e snapGroup3, utilizzare questo comando:

[listing]
----
show snapImages ["snapGroup1:12345 snapGroup2:newest snapGroup3:oldest"];
----


== Livello minimo del firmware

7.83
