---
permalink: commands-a-z/show-snmpsystemvariables.html 
sidebar: sidebar 
keywords: show, snmp, mib ii, system, group, variables 
summary: 'Il comando show snmpSystemVariables restituisce informazioni sulle variabili di sistema SNMP (Simple Network Management Protocol). Le variabili di sistema vengono mantenute in un database Management Information base II (MIB-II).' 
---
= Mostra le variabili del gruppo di sistema SNMP MIB II
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show snmpSystemVariables` Il comando restituisce informazioni sulle variabili di sistema SNMP (Simple Network Management Protocol). Le variabili di sistema vengono mantenute in un database Management Information base II (MIB-II).



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di amministratore del supporto o di Storage Monitor.



== Sintassi

[source, cli]
----
show snmpSystemVariables
----


== Parametri

Nessuno.



== Note

Questo comando restituisce informazioni sulle variabili di sistema SNMP simili a questo esempio.

[listing]
----
SYSTEM VARIABLES
    Sys Name: NONE
    Sys Contact: NONE
    Sys Location: NONE
----


== Livello minimo del firmware

8.30
