---
permalink: commands-a-z/show-alldrives.html 
sidebar: sidebar 
keywords: show, drive 
summary: 'Il comando show allDrives restituisce informazioni sui dischi nell"array di storage.' 
---
= Mostra unità - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show allDrives` il comando restituisce informazioni sui dischi nell'array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Per ogni disco dell'array di storage, questo comando restituisce le seguenti informazioni:

* Il numero totale di dischi
* Il tipo di disco (SAS o NVMe4K)
* Informazioni sul disco di base:
+
** La posizione del vassoio e dello slot
** Lo stato
** La capacità
** La velocità di trasferimento dei dati
** L'ID del prodotto
** Il livello del firmware


* Informazioni sull'usura delle unità SSD (queste informazioni non vengono visualizzate se l'array non contiene unità SSD):
+
** Il conteggio medio di cancellazione.
** I blocchi di riserva rimanenti.
** La percentuale di resistenza utilizzata (novità nella versione 11.41). La durata percentuale utilizzata è la quantità di dati scritti sulle unità SSD fino ad oggi divisa per il limite teorico di scrittura totale per le unità.


* Informazioni sul canale del disco:
+
** La posizione del vassoio e dello slot
** Il canale preferito
** Il canale ridondante


* Copertura hot spare
* Dettagli per ciascun disco
+
[NOTE]
====
Le informazioni sulla data di produzione non sono disponibili per i dischi NVMe.

====




== Sintassi

[source, cli, subs="+macros"]
----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]))
summary
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allDrives`
 a| 
L'impostazione per restituire informazioni su tutti i dischi dell'array di storage.



 a| 
`driveMediaType`
 a| 
Il tipo di disco per il quale si desidera recuperare le informazioni. I seguenti valori sono tipi validi di supporti su disco:

* `HDD` -- utilizzare questa opzione se si dispone di dischi rigidi nel vassoio dell'unità
* `SSD` -- utilizzare questa opzione se si dispone di dischi a stato solido nel vassoio dell'unità
* `unknown` -- utilizzare questa opzione se non si è sicuri dei tipi di supporti presenti nel vassoio dell'unità
* `allMedia` -- utilizzare questa opzione se si desidera utilizzare tutti i tipi di supporti presenti nel vassoio dell'unità




 a| 
`driveType`
 a| 
Il tipo di disco per il quale si desidera recuperare le informazioni. Non è possibile combinare tipi di unità.

I tipi di dischi validi sono:

* `SAS`
* `NVMe4K`


Se non si specifica un tipo di disco, il comando passa automaticamente a qualsiasi tipo.



 a| 
`drive` oppure `drives`
 a| 
Per i vassoi ad alta capacità, specificare il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot per l'unità. Per i vassoi delle unità a bassa capacità, specificare il valore dell'ID del vassoio e il valore dell'ID dello slot per l'unità. I valori dell'ID vassoio sono `0` a. `99`. I valori dell'ID cassetto sono `1` a. `5`.

Tutti i valori massimi di ID slot sono 24. I valori ID slot iniziano con 0 o 1, a seconda del modello di vassoio. I cassetti per dischi compatibili con i controller E2800 e E5700 hanno numeri ID slot a partire da 0. I vassoi per dischi compatibili con i controller E2700 e E5600 hanno numeri ID slot a partire da 1.

Racchiudere il valore dell'ID vassoio, il valore dell'ID cassetto e il valore dell'ID slot tra parentesi quadre ([ ]).



 a| 
`summary`
 a| 
L'impostazione per restituire lo stato, la capacità, la velocità di trasferimento dei dati, l'ID del prodotto e la versione del firmware per i dischi specificati.

|===


== Note

Per determinare le informazioni relative al tipo e alla posizione di tutte le unità nell'array di storage, utilizzare `allDrives` parametro.

Per determinare le informazioni relative alle unità SAS nell'array di storage, utilizzare `driveType` parametro.

Per determinare il tipo di disco in una posizione specifica, utilizzare `drive` E inserire l'ID vassoio e l'ID slot per l'unità.

Il `drive` il parametro supporta sia i vassoi per dischi ad alta capacità che quelli a bassa capacità. Un vassoio per dischi ad alta capacità dispone di cassetti che trattengono le unità. I cassetti scorrono fuori dal vassoio dell'unità per consentire l'accesso alle unità. Un vassoio per unità a bassa capacità non dispone di cassetti. Per un vassoio dell'unità ad alta capacità, è necessario specificare l'identificativo (ID) del vassoio dell'unità, l'ID del cassetto e l'ID dello slot in cui si trova l'unità. Per un vassoio dell'unità a bassa capacità, è necessario specificare solo l'ID del vassoio dell'unità e l'ID dello slot in cui si trova un'unità. Per un vassoio dell'unità a bassa capacità, un metodo alternativo per identificare una posizione per un'unità consiste nel specificare l'ID del vassoio dell'unità, impostare l'ID del cassetto su `0`E specificare l'ID dello slot in cui si trova un'unità.



== Livello minimo del firmware

5.43

7.60 aggiunge `drawerID` input dell'utente e il `driveMediaType` parametro.

8.41 aggiunge informazioni sulla durata dell'usura, sotto forma di percentuale di durata utilizzata, per i dischi SSD in un sistema E2800, E5700 o EF570.
