---
permalink: commands-a-z/show-replaceabledrives.html 
sidebar: sidebar 
keywords: show, replaceable, drives 
summary: Il comando show replaceableDrives mostra tutte le unità sostituibili in un array di storage. 
---
= Mostra unità sostituibili - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show replaceableDrives` il comando mostra tutte le unità sostituibili in un array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Per ogni disco sostituibile nell'array di storage, questo comando restituisce le seguenti informazioni:

* La posizione del vassoio e dello slot
* Il nome del gruppo di volumi a cui appartiene l'unità
* Il World Wide Name (WWN)
* Lo stato del disco




== Sintassi

[source, cli]
----
show replaceableDrives
----


== Output di esempio

[listing]
----
Replaceable drive at Tray 0, Slot 3
                Volume group: 2
                World-wide name: 5000c50028785aff0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 23
                Volume group: 2
                World-wide name: 5000c500095d46df0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 24
                Volume group: 2
                World-wide name: 5000c500287854d70000000000000000
                Status: Removed
----


== Livello minimo del firmware

7.10
