---
permalink: commands-a-z/show-volumegroup-importdependencies.html 
sidebar: sidebar 
keywords: show, volume, group, import, dependencies 
summary: 'Il comando show VolumeGroup importDependencies (Mostra dipendenze VolumeGroup) mostra un elenco di dipendenze per i dischi di un gruppo di volumi che si desidera spostare da un array di storage a un secondo array di storage.' 
---
= Mostra le dipendenze di importazione dei gruppi di volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volumeGroup importDependencies` il comando mostra un elenco di dipendenze per i dischi di un gruppo di volumi che si desidera spostare da un array di storage a un secondo array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]] importDependencies
[cancelImport=(TRUE | FALSE)]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi per il quale si desidera visualizzare le dipendenze di importazione. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).



 a| 
`cancelImport`
 a| 
L'impostazione per eseguire nuovamente lo spin dei dischi dopo la lettura delle dipendenze del gruppo di volumi. Per spegnere i dischi, impostare questo parametro su `TRUE`. Per consentire ai dischi di rimanere in funzione, impostare questo parametro su `FALSE`.

|===


== Note

Questo comando restituisce le dipendenze di un gruppo di volumi specifico, che deve trovarsi in uno stato esportato o forzato. Se si decide di mantenere le dipendenze elencate, il `cancelImport` il parametro può essere applicato per far tornare indietro le unità.

È necessario eseguire `show volumeGroup importDependencies` prima di eseguire il comando `start volumeGroup import` comando.



== Livello minimo del firmware

7.10
