---
permalink: commands-a-z/show-storagearray-iscsinegotiationdefaults.html 
sidebar: sidebar 
keywords: show, storage, array, negotiation, defaults 
summary: Il comando show StorageArray iscsiNegotiationDefaults restituisce informazioni sulle impostazioni del livello di connessione che sono soggette alla negoziazione initiator-target. 
---
= Mostra i valori predefiniti di negoziazione dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show storageArray iscsiNegotiationDefaults` il comando restituisce informazioni sulle impostazioni a livello di connessione che sono soggette alla negoziazione initiator-target.



[[supported-arrays]]
== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Storage Monitor.



[[syntax]]
== Sintassi

[source, cli]
----
show storageArray iscsiNegotiationDefaults
----


[[parameters]]
== Parametri

Nessuno.



[[notes]]
== Note

Le informazioni restituite includono le impostazioni predefinite del vassoio del controller (ovvero quelle che costituiscono il punto di partenza per la negoziazione) e le impostazioni attive correnti.



[[minimum-firmware-level]]
== Livello minimo del firmware

7.10
