---
permalink: commands-a-z/show-volume-summary.html 
sidebar: sidebar 
keywords: show, volume 
summary: Il comando show volume summary restituisce informazioni su un volume. 
---
= Mostra volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volume summary` il comando restituisce informazioni su un volume.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.



== Contesto

Per i volumi in un array di storage, questo comando restituisce le seguenti informazioni:

* Il numero di volumi
* Il nome
* Lo stato
* La capacità
* Il livello RAID
* Il gruppo di volumi in cui si trova il volume
* Dettagli:
+
** L'ID del volume
** L'ID del sottosistema
** Il tipo di disco (SAS)
** Protezione contro la perdita dei vassoi
** Il proprietario preferito
** Il proprietario corrente
** La dimensione del segmento
** La priorità di modifica
** Stato della cache di lettura (abilitato o disabilitato)
** Stato della cache di scrittura (abilitato o disabilitato)
** Cache di scrittura senza stato delle batterie (attivata o disattivata)
** Cache di scrittura con stato mirror (abilitato o disabilitato)
** La cache di scrittura di tipo Flush dopo il tempo
** L'impostazione di prefetch di lettura della cache (VERO o FALSO)
** Lo stato di abilitazione della scansione dei supporti in background (attivato o disattivato)
** Scansione dei supporti con stato di controllo della ridondanza (attivato o disattivato)


* I volumi di repository mirror




== Sintassi

[source, cli, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) summary
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allVolumes`
 a| 
Questo parametro restituisce le statistiche delle performance relative a tutti i volumi nell'array di storage.



 a| 
`volume`
 a| 
Il nome di un volume per il quale si desidera recuperare le informazioni. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`volumes`
 a| 
I nomi di diversi volumi per i quali si desidera recuperare le informazioni. Inserire i nomi dei volumi utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Separare ciascuno dei nomi con uno spazio.


Se i nomi dei volumi contengono caratteri o numeri speciali, immettere i nomi utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Racchiudere ciascuno dei nomi tra virgolette doppie (" ").
* Separare ciascuno dei nomi con uno spazio.




 a| 
`summary`
 a| 
L'impostazione per restituire un elenco conciso di informazioni sui volumi.

|===