---
permalink: commands-a-z/show-storagearray-dbmdatabase.html 
sidebar: sidebar 
keywords: show, storage, array, dbm, database 
summary: Il comando show StorageArray dbmDatabase recupera e mostra i metadati per le posizioni di backup integrate di uno storage array. Quando sono presenti più posizioni di backup, vengono visualizzati i metadati per ciascuna posizione. 
---
= Mostra database DBM array storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `show storageArray dbmDatabase` il comando recupera e mostra i metadati per le posizioni di backup integrate di un array di storage. Quando sono presenti più posizioni di backup, vengono visualizzati i metadati per ciascuna posizione.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Sintassi

[listing]
----
show storageArray dbmDatabase
----


== Parametri

Nessuno.



== Note

Questo comando restituisce le informazioni del database di configurazione in un formato simile a questo esempio.

`Configuration Database MetadataLast Host Backup: <date stamp>`

[cols="7*"]
|===
| CTL | POSIZIONE | REVISIONE | ID | NUMERO GEN | STATO | MODALITÀ DI ACCESSO 


 a| 
R
 a| 
Cache
 a| 
X.A.
 a| 
999999
 a| 
999999
 a| 
R/W
 a| 
Ottimale



 a| 
B
 a| 
Cache
 a| 
X.A.
 a| 
999999
 a| 
999999
 a| 
R/W
 a| 
Ottimale



 a| 
N/A.
 a| 
Disco
 a| 
X.A.
 a| 
999999
 a| 
999999
 a| 
R/W
 a| 
Ottimale

|===


== Livello minimo del firmware

7.83
