---
permalink: commands-a-z/show-volumecopy-source-targetcandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, target, candidates 
summary: 'Il comando show VolumeCopy source targetCandidate restituisce informazioni sui volumi candidati che è possibile utilizzare come destinazione per un"operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.' 
---
= Mostra i candidati target per la copia del volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volumeCopy source targetCandidates` il comando restituisce informazioni sui volumi candidati che è possibile utilizzare come destinazione per un'operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Sintassi

[source, cli, subs="+macros"]
----
show volumeCopy source pass:quotes[["_sourceName_"]] targetCandidates
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`source`
 a| 
Il nome del volume di origine per il quale si sta tentando di trovare un volume di destinazione candidato. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiudere il nome del volume tra virgolette doppie (" ") all'interno di parentesi quadre.

|===