---
permalink: commands-a-z/show-alldrives-downloadprogress.html 
sidebar: sidebar 
keywords: show, drive, download, progress 
summary: Il comando show allDrives downloadProgress restituisce lo stato dei download del firmware per i dischi a cui si rivolge il comando di download del firmware del disco o il comando di download del drivefirmware StorageArray. 
---
= Mostra avanzamento download unità - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show allDrives downloadProgress` il comando restituisce lo stato dei download del firmware per le unità di destinazione `download drive firmware` o il `download storageArray driveFirmware` comando.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli]
----
show allDrives downloadProgress
----


== Parametri

Nessuno.



== Note

Una volta completati tutti i download del firmware, questo comando restituisce uno stato valido. Se il download del firmware non riesce, questo comando mostra lo stato del download del firmware di ciascun disco di destinazione. Questo comando restituisce gli stati mostrati in questa tabella.

[cols="2*"]
|===
| Stato | Definizione 


 a| 
`Successful`
 a| 
I download sono stati completati senza errori.



 a| 
`Not Attempted`
 a| 
I download non sono stati avviati.



 a| 
`Partial Download`
 a| 
I download sono in corso.



 a| 
`Failed`
 a| 
I download sono stati completati con errori.

|===


== Livello minimo del firmware

6.10
