---
permalink: commands-a-z/show-volumecopy-sourcecandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, source, candidates 
summary: 'Il comando show VolumeCopy sourceCandidate restituisce informazioni sui volumi candidati che è possibile utilizzare come origine per un"operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.' 
---
= Mostra i candidati per la copia del volume originale - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volumeCopy sourceCandidates` il comando restituisce informazioni sui volumi candidati che è possibile utilizzare come origine per un'operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Sintassi

[source, cli]
----
show volumeCopy sourceCandidates
----


== Parametri

Nessuno.



== Note

Questo comando restituisce le informazioni di origine della copia del volume come illustrato in questo esempio.

[listing]
----
Volume Name: finance
   Capacity: 4.0 GB
   Volume Group: 1
Volume Name: engineering
   Capacity: 4.0 GB
   Volume Group: 2
----