---
permalink: commands-a-z/show-volume-reservations.html 
sidebar: sidebar 
keywords: show, volume, reservations 
summary: Il comando show volume reservations restituisce informazioni sui volumi con riserve persistenti. 
---
= Mostra prenotazioni volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volume reservations` il comando restituisce informazioni sui volumi con riserve persistenti.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.



== Sintassi

[source, cli, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) reservations
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`allVolumes`
 a| 
Il parametro per restituire le statistiche delle performance relative a tutti i volumi nell'array di storage.



 a| 
`volume`
 a| 
Il nome di un volume per il quale si desidera recuperare le informazioni. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`volumes`
 a| 
I nomi di diversi volumi per i quali si desidera recuperare le informazioni. Inserire i nomi dei volumi utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Separare ciascuno dei nomi con uno spazio.


Se i nomi dei volumi contengono caratteri o numeri speciali, immettere i nomi utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Racchiudere ciascuno dei nomi tra virgolette doppie (" ").
* Separare ciascuno dei nomi con uno spazio.


|===


== Livello minimo del firmware

5.40
