---
permalink: commands-a-z/show-volumegroup-exportdependencies.html 
sidebar: sidebar 
keywords: show, volume, group, export, dependencies 
summary: Il comando show VolumeGroup exportDependencies mostra un elenco di dipendenze per i dischi di un gruppo di volumi che si desidera spostare da un array di storage a un secondo array di storage. 
---
= Mostra le dipendenze di esportazione del gruppo di volumi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show volumeGroup exportDependencies` il comando mostra un elenco di dipendenze per i dischi di un gruppo di volumi che si desidera spostare da un array di storage a un secondo array di storage.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]] exportDependencies
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi per il quale si desidera visualizzare le dipendenze di esportazione. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).

|===


== Note

Questo comando consente di eseguire lo spin up dei dischi di un gruppo di volumi, di leggere il DACstore e di visualizzare un elenco delle dipendenze di importazione per il gruppo di volumi. Il gruppo di volumi deve essere in uno stato di esportazione o forzato.



== Livello minimo del firmware

7.10
