---
permalink: commands-a-z/show-allhostports.html 
sidebar: sidebar 
keywords: show, host, ports 
summary: Il comando show allHostPorts restituisce informazioni sulle porte host configurate. 
---
= Mostra porte host - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show allHostPorts` il comando restituisce informazioni sulle porte host configurate.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Per tutte le porte host collegate a un array di storage, questo comando restituisce le seguenti informazioni:

* Identificativo della porta host
* Il nome della porta host
* Il tipo di host




== Sintassi

[source, cli]
----
show allHostPorts
----


== Parametri

Nessuno.



== Note

Questo comando restituisce informazioni sulla porta host HBA simili a questo esempio.

[listing]
----
HOST PORT IDENTIFIER     HOST PORT NAME  HOST TYPE
12:34:56:54:33:22:22:22  Jupiter1        Solaris
12:34:56:78:98:98:88:88  Pluto1          Windows 2000/Server 2003 Clustered
54:32:12:34:34:55:65:66  Undefined       Undefined
----


== Livello minimo del firmware

5.40
