---
permalink: commands-a-z/show-storagearray-unconfiguredinitiators.html 
sidebar: sidebar 
keywords: show, unconfigured, initiators 
summary: 'Il comando show StorageArray unconfiguredInitialators restituisce un elenco di iniziatori rilevati dall"array di storage ma non ancora configurati nella topologia dell"array di storage.' 
---
= Mostra iniziatori non configurati - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show storageArray unconfiguredInitiators` command restituisce un elenco di iniziatori rilevati dall'array di storage ma non ancora configurati nella topologia dell'array di storage.



== Array supportati

Questo comando si applica a un singolo array di storage E4000, E2800, E5700, EF600 o EF300. Non funziona sugli storage array E2700 o E5600.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.

Questo comando sostituisce link:show-storagearray-unconfigurediscsiinitiators.html["Mostra StorageArray unconfiguredIscsiInitialators"] comando.



== Sintassi

[source, cli]
----
show storageArray unconfiguredInitiators
----


== Parametri

Nessuno.



== Livello minimo del firmware

8.50
