---
permalink: commands-a-z/show-storagearray-iscsinegotiationdefaults.html 
sidebar: sidebar 
keywords: show, storage, array, negotiation, defaults 
summary: Il comando show StorageArray iscsiNegotiationDefaults restituisce informazioni sulle impostazioni del livello di connessione che sono soggette alla negoziazione initiator-target. 
---
= Mostra le impostazioni predefinite di negoziazione degli array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `show storageArray iscsiNegotiationDefaults` il comando restituisce informazioni sulle impostazioni a livello di connessione che sono soggette alla negoziazione initiator-target.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Sintassi

[listing]
----
show storageArray iscsiNegotiationDefaults
----


== Parametri

Nessuno.



== Note

Le informazioni restituite includono le impostazioni predefinite del vassoio del controller (ovvero quelle che costituiscono il punto di partenza per la negoziazione) e le impostazioni attive correnti.



== Livello minimo del firmware

7.10
