---
permalink: commands-a-z/show-storagearray-unconfigurediscsiinitiators.html 
sidebar: sidebar 
keywords: show, storage, array, unconfigured, iscsi, initiators 
summary: 'Il comando show StorageArray unconfiguredIscsiInitialators restituisce un elenco di iniziatori rilevati dall"array di storage ma non ancora configurati nella topologia dell"array di storage.' 
---
= Mostra gli iniziatori iSCSI non configurati dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show storageArray unconfiguredIscsiInitiators` command restituisce un elenco di iniziatori rilevati dall'array di storage ma non ancora configurati nella topologia dell'array di storage.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Storage Monitor.

Questo comando è obsoleto. Il comando che lo sostituisce è link:show-storagearray-unconfiguredinitiators.html["Mostra StorageArray unconfiguredInitialators"].



== Sintassi

[source, cli]
----
show storageArray unconfiguredIscsiInitiators
----


== Parametri

Nessuno.



== Livello minimo del firmware

7.10

8.50 ha obsoleto questo comando.
