---
permalink: commands-a-z/show-storagearray-powerinfo.html 
sidebar: sidebar 
keywords: show, storage, array, power, information 
summary: 'Il comando show StorageArray powerInfo restituisce informazioni sulla quantità di energia consumata dall"intero array di storage e da ciascun tray dell"array di storage.' 
---
= Mostra informazioni sull'alimentazione dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show storageArray powerInfo` il comando restituisce informazioni sulla quantità di energia consumata dall'intero array di storage e da ciascun tray dell'array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.



== Sintassi

[source, cli]
----
show storageArray powerInfo
----


== Parametri

Nessuno.



== Note

Questo comando restituisce informazioni sul consumo di energia simili a questo esempio.

[listing]
----
total power drawn: 310 watts
number of trays: 1
tray power input details:
   tray id  power supply serial number  input power
   0        0                           160 watts
   0        1                           150 watts
----


== Livello minimo del firmware

8.10
