---
permalink: commands-a-z/show-syncmirror-synchronizationprogress.html 
sidebar: sidebar 
keywords: show, synchronous, mirror, volume, synchronization, progress 
summary: 'Il comando show SyncMirror SynchronizationProgress restituisce l"avanzamento della sincronizzazione dei dati tra il volume primario e il volume secondario in una configurazione di mirroring sincrono.' 
---
= Mostra l'avanzamento della sincronizzazione del volume di mirroring sincrono
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show syncMirror synchronizationProgress` Il comando restituisce l'avanzamento della sincronizzazione dei dati tra il volume primario e il volume secondario in una configurazione di mirroring sincrono.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800 e E5700, a condizione che siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800 o E5700, è necessario disporre del ruolo di amministratore dello storage o di Storage Monitor.



== Contesto

Questo comando mostra l'avanzamento come percentuale di sincronizzazione dei dati completata.

[NOTE]
====
Nelle versioni precedenti di questo comando, l'identificatore di funzione era `remoteMirror`. Questo identificatore di funzione non è più valido e viene sostituito da `*syncMirror*`.

====


== Sintassi

[source, cli, subs="+macros"]
----
show syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1_... _volumeNameN_]]) synchronizationProgress
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volume`
 a| 
Il nome del volume primario della coppia remota mirrorata per la quale si desidera controllare l'avanzamento della sincronizzazione. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiudere il nome del volume tra virgolette doppie (" ") all'interno di parentesi quadre.



 a| 
`volumes`
 a| 
I nomi del volume primario della coppia remota mirrorata per la quale si desidera controllare l'avanzamento della sincronizzazione. Inserire i nomi dei volumi utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Separare ciascuno dei nomi con uno spazio.


Se i nomi dei volumi hanno caratteri speciali o sono costituiti solo da numeri, immettere i nomi utilizzando le seguenti regole:

* Racchiudere tutti i nomi tra parentesi quadre ([ ]).
* Racchiudere ciascuno dei nomi tra virgolette doppie (" ").
* Separare ciascuno dei nomi con uno spazio.


|===


== Livello minimo del firmware

5.40
