---
permalink: commands-a-z/show-storagearray-odxsetting.html 
sidebar: sidebar 
keywords: show, storage, array, odx, set 
summary: 'Il comando show StorageArray odxsetting restituisce le impostazioni correnti per Offloaded Data Transfer (ODX) e VMware vStorage API Array Architecture (VAAI) sullo storage array.' 
---
= Mostra l'impostazione ODX dell'array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `show storageArray odxsetting` Il comando restituisce le impostazioni correnti per Offloaded Data Transfer (ODX) e VMware vStorage API Array Architecture (VAAI) sullo storage array.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, è necessario disporre del ruolo Storage Admin o Storage Monitor.



== Contesto

Le impostazioni di questo comando possono essere le seguenti:

* True -- ODX e VAAI sono attivati.
* Falso -- ODX e VAAI sono disattivati.
* Incoerente - i controller non hanno le stesse impostazioni.
* Sconosciuto -- Impossibile determinare l'impostazione per ODX o VAAI.




== Sintassi

[source, cli]
----
show storageArray odxsetting
----


== Parametri

Nessuno.



== Note

Questo comando restituisce le informazioni ODX e VAAI simili a questo esempio.

[listing]
----
Windows ODX Setting Status
odxEnabled  True | False | Inconsistent | Unknown
vaaiEnabled True | False | Inconsistent | Unknown
----


== Livello minimo del firmware

8.20
