---
permalink: commands-a-z/smcli-enable-disable-autosupportondemand.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, ondemand, feature, emw, management, domain, level, smcli 
summary: Il comando SMcli enable disable autoSupportOnDemand attiva o disattiva la funzionalità AutoSupport OnDemand. Questa funzionalità permette al supporto tecnico di coordinare la trasmissione dei dati AutoSupport e di richiedere la ritrasmissione dei dati di supporto mancanti. 
---
= Abilitare o disabilitare la funzionalità AutoSupport OnDemand a livello di dominio di gestione EMW (solo SMcli) - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `SMcli enable|disable autoSupportOnDemand` Il comando attiva o disattiva la funzione AutoSupport su richiesta. Questa funzione consente al supporto tecnico di coordinare la trasmissione dei dati AutoSupport e di richiedere la ritrasmissione dei dati di supporto mancanti.



[[supported-arrays]]
== Array supportati

Questo comando si applica a tutti gli storage array E2700 ed E5600 nel dominio di gestione contemporaneamente. Non si applica agli storage array E4000, E2800 o E5700.



[[context]]
== Contesto

[NOTE]
====
Questo comando è un comando SMcli, non un comando script. Eseguire questo comando da una riga di comando. Non è possibile eseguire questo comando dall'editor di script nel software di gestione dello storage.

====
Prima di attivare questa funzione, è necessario attivare la funzionalità AutoSupport nel dominio di gestione. Dopo aver attivato questa funzione, è possibile attivare la funzione di diagnostica remota AutoSupport (se si desidera). Le funzioni di diagnostica remota di AutoSupport sono attivate, per impostazione predefinita, quando la funzione AutoSupport su richiesta è attivata.



[[syntax]]
== Sintassi

[source, cli]
----
SMcli enable|disable autoSupportOnDemand
----


[[parameters]]
== Parametri

Nessuno.



[[verification]]
== Verifica

Utilizzare `SMcli -autoSupportConfig show` per verificare se la funzione è stata attivata. Le due righe iniziali dell'output visualizzato mostrano lo stato di abilitazione della funzione AutoSupport, seguita dalla funzione AutoSupport on Demand:

[listing]
----
The AutoSupport feature is activated on this storage management
station.
The AutoSupport OnDemand feature is activated on this storage
management station.
----


[[minimum-firmware-level]]
== Livello minimo del firmware

8.25
