---
permalink: commands-a-z/smcli-autosupportconfig-test.html 
sidebar: sidebar 
keywords: test, autosupport, configuration 
summary: Utilizzare il comando SMcli -autoSupportConfig test per verificare la configurazione AutoSupport inviando un messaggio di test. Questo comando opera sul dominio di gestione. Il software di gestione dello storage sceglie un array con supporto automatico nel dominio di gestione per i dati di esempio da includere nel messaggio di test. 
---
= Verificare la configurazione di AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilizzare `SMcli -autoSupportConfig test` Comando per verificare la configurazione AutoSupport inviando un messaggio di test. Questo comando opera sul dominio di gestione. Il software di gestione dello storage sceglie un array con supporto automatico nel dominio di gestione per i dati di esempio da includere nel messaggio di test.



== Array supportati

Questo comando si applica a tutti gli storage array E2700 ed E5600 nel dominio di gestione contemporaneamente. Non si applica agli storage array E2800 o E5700.



== Contesto

[NOTE]
====
Questo comando è un comando SMcli, non un comando script. Eseguire questo comando da una riga di comando. Non è possibile eseguire questo comando dall'editor di script nel software di gestione dello storage.

====
[NOTE]
====
Il monitor persistente deve essere in esecuzione sulla stazione di gestione per inviare messaggi AutoSupport pianificati o attivati da eventi. Avviare il servizio prima di utilizzare questo comando.

====


== Sintassi

[listing]
----
SMcli -autoSupportConfig test reply-toEmail<address>
----


== Parametri

La seguente tabella elenca i parametri per l'invio di un messaggio di test AutoSupport.

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`test`
 a| 
Parametro richiesto per il comando. Non richiede valore.



 a| 
`reply-toEmail`
 a| 
Consente all'utente di specificare l'indirizzo e-mail di risposta per i messaggi AutoSupport di tipo SMTP.

|===


== Livello minimo del firmware

8.25



== Esempio di test con l'erogazione HTTP/HTTPS

Di seguito sono riportati alcuni esempi dell'utilizzo di questo comando quando si utilizza un tipo di recapito HTTP o HTTPS, in cui non si specifica un indirizzo e-mail per il recapito.

[listing]
----
SMcli -autoSupportConfig test
The sample AutoSupport message was successfully sent to the ASUP gateway.

SMcli completed successfully.
----


== Esempio di test mediante la distribuzione SMTP

Di seguito sono riportati alcuni esempi dell'utilizzo di questo comando. Quando si utilizza un metodo di consegna SMTP, è possibile utilizzare `reply-toEmail` parametro per specificare l'indirizzo di destinazione.

[listing]
----
SMcli -autoSupportConfig test reply-toEmail:user@netapp.com
The sample AutoSupport message was successfully sent to the ASUP gateway.

An email has been sent to 'user@netapp.com', please check the mailbox
for delivery confirmation.

SMcli completed successfully.
----