---
permalink: commands-a-z/start-drivechannel-locate.html 
sidebar: sidebar 
keywords: start, drive, channel, locate 
summary: Il comando START DriveChannel Locate identifica i vassoi delle unità collegati a un canale specifico accendendo gli indicatori luminosi del vassoio delle unità collegato al canale delle unità. 
---
= Avvia la localizzazione del canale di unità - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start driveChannel locate` il comando identifica i vassoi delle unità collegati a un canale specifico accendendo gli indicatori luminosi del vassoio delle unità collegato al canale delle unità.



[[supported-arrays]]
== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



[[context]]
== Contesto

Utilizzare `stop driveChannel locate` comando per spegnere gli indicatori luminosi sul vassoio dell'unità



[[syntax]]
== Sintassi

[source, cli]
----
start driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)] locate
----


[[parameter]]
== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`driveChannel`
 a| 
Il numero identificativo del canale del disco che si desidera individuare. I valori validi per il numero identificativo del canale del disco sono `1`, `2`, `3`, `4`, `5`, `6`, `7`, o. `8`. Racchiudere il numero identificativo del canale dell'unità tra parentesi quadre ([ ]).

|===


[[minimum-firmware-level]]
== Livello minimo del firmware

6.10

7.15 aggiunge un aggiornamento all'identificatore del canale del disco.
