---
permalink: commands-a-z/start-diskpool-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, disk pool, resource, provision 
summary: 'Il comando start diskPool resourceProvisioning abilita il provisioning delle risorse su un determinato pool di dischi e avvia un"operazione asincrona di abilitazione del provisioning delle risorse su ciascun volume del pool di dischi. Il provisioning delle risorse richiede che tutte le unità del pool di dischi supportino la funzionalità DULBE di NVMe.' 
---
= Avvia il provisioning delle risorse del pool di dischi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start diskPool resourceProvisioning` il comando abilita il provisioning delle risorse su un determinato pool di dischi e avvia un'operazione asincrona di abilitazione del provisioning delle risorse su ciascun volume del pool di dischi. Il provisioning delle risorse richiede che tutte le unità del pool di dischi supportino la funzionalità DULBE di NVMe.



[[supported-arrays]]
== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi gli array EF600, EF300, EF50 e EF80, purché tutti i pacchetti SMcli siano installati.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage EF600, EF300, EF50 e EF80, devi avere il ruolo Storage Admin.



[[context]]
== Contesto

Per disattivare il provisioning delle risorse su un pool di dischi, utilizzare il comando di provisioning completo con l'opzione per disattivare il provisioning delle risorse. Un pool di dischi viene fornito in base alle risorse quando viene creato se tutti i dischi sono compatibili con DULBE e gli array di storage `resourceProvisionedVolumes` l'impostazione è `true`.



[[syntax]]
== Sintassi

[source, cli, subs="+macros"]
----
start diskPoolpass:quotes[[_diskPoolName_]] resourceProvisioning
----


[[parameters]]
== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`diskPoolName`
 a| 
Il pool di dischi che si desidera attivare la funzione di provisioning delle risorse. Racchiudere il nome del pool di dischi tra parentesi quadre ([ ]).

|===


[[minimum-firmware-level]]
== Livello minimo del firmware

11.73
