---
permalink: commands-a-z/start-storagearray-controllerhealthimage-controller.html 
sidebar: sidebar 
keywords: start, storage, array, controller, health, image 
summary: 'Il comando start StorageArray controllerHealthImage controller produce un"immagine dello stato di salute del controller dell"array di storage sugli array di storage che supportano la funzionalità dell"immagine dello stato di salute del controller.' 
---
= Avviare l'immagine dello stato del controller dell'array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start storageArray controllerHealthImage controller` il comando produce un'immagine dello stato di salute del controller dell'array di storage sugli array di storage che supportano la funzionalità dell'immagine dello stato di salute del controller.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Con la versione del firmware 8.20 di `coreDump` il parametro viene sostituito con `controllerHealthImage` parametro.

====
[NOTE]
====
Utilizzare questo comando solo sotto la direzione del supporto tecnico.

====
Se lo storage array non supporta la funzione di immagine dello stato del controller, il comando restituisce un errore.



== Sintassi

[source, cli]
----
start storageArray controllerHealthImage controller [(a|b)]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`controller`
 a| 
Questo parametro specifica il controller da cui produrre l'immagine dello stato del controller. Gli identificatori del controller validi sono `a` oppure `b`, dove `a` È il controller nello slot A, e. `b` Il controller si trova nello slot B. Racchiudere l'identificatore del controller tra parentesi quadre ([ ]). Se non si specifica un controller, il software di gestione dello storage restituisce un errore di sintassi.

|===


== Note

Questo comando forza il controller selezionato a scaricare i dati principali nella cache. Utilizzare `save storageArray controllerHealthImage` comando per salvare una copia dei dati della cache in un file host.



== Livello minimo del firmware

7.83

8.20 sostituisce `coreDump` con il `controllerHealthImage` parametro.
