---
permalink: commands-a-z/start-volume-initialization.html 
sidebar: sidebar 
keywords: start, volume, initialization 
summary: Il comando start volume initialize avvia la formattazione di un volume in un array di storage. 
---
= Avviare l'inizializzazione del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start volume initialize` il comando avvia la formattazione di un volume in un array di storage.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
La formattazione di un volume avvia un'operazione a esecuzione prolungata che non è possibile interrompere.

====


== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volume`
 a| 
Il nome di un volume che si desidera formattare. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.

|===


== Livello minimo del firmware

6.10
