---
permalink: commands-a-z/start-volumegroup-export.html 
sidebar: sidebar 
keywords: start, volume, group, export 
summary: Il comando di esportazione start VolumeGroup sposta un gruppo di volumi in uno stato esportato. 
---
= Avviare l'esportazione dei gruppi di volumi
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `start volumeGroup export` Il comando sposta un gruppo di volumi in uno stato esportato.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Quindi, è possibile rimuovere le unità che compongono il gruppo di volumi e reinstallare le unità in un array di storage diverso.

[CAUTION]
====
Non eseguire queste operazioni senza aver prima eseguito le operazioni elencate nella xref:../get-started/learn-about-volume-group-migration.html[Scopri di più sulla migrazione dei gruppi di volumi.]

====
[NOTE]
====
All'interno del gruppo di volumi, non è possibile spostare i volumi associati alle funzionalità da uno storage array a un altro storage array.

====


== Sintassi

[listing, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] export
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi che si desidera esportare. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).

|===


== Note

Una volta eseguito correttamente questo comando, è possibile eseguire `start volumeGroup import` Comando per terminare lo spostamento del gruppo di volumi in uno stato completo, rendendo il gruppo di volumi disponibile per il nuovo array di storage.

Se questo comando non riesce a causa di problemi hardware che hanno impedito il completamento dell'esportazione, utilizzare `set volumeGroup forceState` comando. Il `set volumeGroup forceState` consente di utilizzare il comando `start volumeGroup import` per importare un gruppo di volumi.

Una volta che il gruppo di volumi si trova in uno stato esportato o forzato, è possibile rimuovere le unità che compongono il gruppo di volumi dall'array di storage. È possibile reinstallare le unità in un array di storage diverso.



== Livello minimo del firmware

7.10
