---
permalink: commands-a-z/start-snapimage-rollback.html 
sidebar: sidebar 
keywords: start, snapshot, image, rollback 
summary: 'Il comando start SnapImage rollback avvia un"operazione di rollback per una serie di immagini snapshot.' 
---
= Avviare il rollback dell'immagine snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `start snapImage rollback` avvia un'operazione di rollback per un set di immagini snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Il contenuto del volume di base cambia immediatamente in modo da corrispondere al contenuto point-in-time del volume dell'immagine snapshot selezionato. Il volume di base diventa immediatamente disponibile per le richieste di lettura/scrittura dopo il completamento dell'operazione di rollback. Per interrompere un'operazione di rollback dell'immagine snapshot, utilizzare `stop rollback snapImage` comando.

Il volume del repository associato all'immagine snapshot continua a tenere traccia di eventuali nuove modifiche tra il volume di base e il volume dell'immagine snapshot che si verificano dopo il completamento dell'operazione di rollback.

[NOTE]
====
Non è possibile utilizzare questo comando per le immagini snapshot coinvolte nella copia del volume online.

====


== Sintassi

[listing, subs="+macros"]
----
pass:quotes[start snapImage ["_snapImageName_"]] rollback
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapImage`
 a| 
Il nome dell'immagine istantanea. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` -- utilizzare questa opzione per visualizzare l'ultima immagine istantanea creata nel gruppo di snapshot.
* `OLDEST` -- utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ") tra parentesi quadre ([ ]).

|===


== Note

Il nome di un'immagine istantanea ha due parti separate da due punti (:):

* L'identificatore del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera avviare un'operazione di rollback per l'immagine snapshot 12345 in un gruppo di snapshot con il nome SnapGroup1, utilizzare il seguente comando:

[listing]
----
start snapImage ["snapGroup1:12345"] rollback;
----
Per avviare un'operazione di rollback per l'immagine snapshot più recente in un gruppo di snapshot con il nome snapGroup1, utilizzare questo comando:

[listing]
----
start snapImage ["snapGroup1:newest"]rollback;
----


== Livello minimo del firmware

7.83
