---
permalink: commands-a-z/start-drivechannel-locate.html 
sidebar: sidebar 
keywords: start, drive, channel, locate 
summary: Il comando START DriveChannel Locate identifica i vassoi delle unità collegati a un canale specifico accendendo gli indicatori luminosi del vassoio delle unità collegato al canale delle unità. 
---
= Avvia la localizzazione del canale di unità - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start driveChannel locate` il comando identifica i vassoi delle unità collegati a un canale specifico accendendo gli indicatori luminosi del vassoio delle unità collegato al canale delle unità.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Utilizzare `stop driveChannel locate` comando per spegnere gli indicatori luminosi sul vassoio dell'unità



== Sintassi

[source, cli]
----
start driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)] locate
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`driveChannel`
 a| 
Il numero identificativo del canale del disco che si desidera individuare. I valori validi per il numero identificativo del canale del disco sono `1`, `2`, `3`, `4`, `5`, `6`, `7`, o. `8`. Racchiudere il numero identificativo del canale dell'unità tra parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.10

7.15 aggiunge un aggiornamento all'identificatore del canale del disco.
