---
permalink: commands-a-z/start-asyncmirrorgroup-synchronize.html 
sidebar: sidebar 
keywords: start, asynchronous, mirror, synchronization 
summary: Il comando start asyncMirrorGroup synchronous Mirroring viene avviato. 
---
= Avvia la sincronizzazione del mirroring asincrono - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start asyncMirrorGroup synchronize` Il comando avvia la sincronizzazione del mirroring asincrono.



[[supported-arrays]]
== Array supportati

Questo comando si applica a qualsiasi array di storage, inclusi E4000, E2700, E5600, E2800, E5700, EF600 ed EF300, a condizione che tutti i pacchetti SMcli siano installati.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600 o EF300, devi avere il ruolo Storage Admin.



[[syntax]]
== Sintassi

[source, cli, subs="+macros"]
----
start asyncMirrorGroup pass:quotes[["_asyncMirrorGroupName_"]] synchronize [deleteRecoveryPointIfNecessary]
----


[[parameter]]
== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`asyncMirrorGroup`
 a| 
Il nome del gruppo di mirror asincrono per il quale si desidera avviare la sincronizzazione. Racchiudere il nome del gruppo mirror asincrono tra virgolette doppie (" ") tra parentesi quadre ([" "]).



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
Il parametro per eliminare il punto di ripristino se i dati di sincronizzazione ripristinabili hanno superato la soglia di tempo per il ripristino. L'età dei punti di ripristino viene misurata a partire dal momento in cui i dati sono stati congelati sull'array di storage primario.

|===


[[minimum-firmware-level]]
== Livello minimo del firmware

7.84

8.10 aggiunge `deleteRecoveryPointIfNecessary` parametro.

11.80 aggiunge il supporto degli array EF600 e EF300
