---
permalink: commands-a-z/start-cgsnapimage-rollback.html 
sidebar: sidebar 
keywords: start, consistency, group, snapshot, rollback 
summary: 'Il comando start cgSnapImage rollback avvia un"operazione di rollback ai volumi della base membro in un gruppo di coerenza snapshot.' 
---
= Avvia il rollback dello snapshot del gruppo di coerenza - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start cgSnapImage rollback` il comando avvia un'operazione di rollback ai volumi della base membro in un gruppo di coerenza snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Il contenuto dei volumi di base cambia immediatamente in modo da corrispondere al contenuto point-in-time del volume snapshot del gruppo di coerenza. I volumi di base diventano immediatamente disponibili per le richieste di lettura/scrittura dopo il completamento dell'operazione di rollback.

Il volume del repository associato al volume snapshot del gruppo di coerenza continua a tenere traccia di eventuali nuove modifiche tra il volume di base e il volume snapshot del gruppo di coerenza che si verificano dopo il completamento dell'operazione di rollback.

Per interrompere un'operazione di rollback ai volumi di base dei membri, utilizzare `stop cgSnapImage rollback` comando.



== Sintassi

[source, cli, subs="+macros"]
----
start cgSnapImage pass:quotes[["_snapCGID:imageID_"]] rollback
memberVolumeSet pass:quotes[("_memberVolumeName1_" ... "_memberVolumeNameN_")]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`cgSnapImage`
 a| 
Il nome dell'immagine snapshot del gruppo di coerenza per cui si desidera avviare un'operazione di rollback. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot.


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` -- utilizzare questa opzione per visualizzare l'ultima immagine istantanea creata nel gruppo di snapshot.
* `OLDEST` -- utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ") tra parentesi quadre ([ ]).



 a| 
`memberVolumeSet`
 a| 
Il nome di uno o più volumi di base membri in un gruppo di coerenza che si desidera eseguire il rollback. Racchiudere il nome di ogni volume di base membro tra virgolette doppie (" ") tra parentesi.

È possibile immettere più nomi di volume. Racchiudere tutti i nomi dei volumi in una serie di parentesi quadre ([ ]). Racchiudere il nome di ciascun volume tra virgolette doppie (" "). Separare il nome di ciascun volume con uno spazio.

Quando il `memberVolumeSet` parametro non utilizzato il processo di rollback si applica a tutti i volumi membri del gruppo di coerenza.

|===


== Note

Il nome di un'immagine istantanea ha due parti separate da due punti (:):

* L'identificatore del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera avviare un'operazione di rollback per l'immagine snapshot più recente in un intero gruppo di coerenza con il nome CG1, utilizzare questo comando:

[listing]
----
start cgSnapImage ["CG1:newest"] rollback;
----
Per avviare un'operazione di rollback per l'immagine snapshot 12345 per i membri del volume base memVol1, memVol2 e memVol3 in un gruppo di coerenza con il nome CG2, utilizzare questo comando:

[listing]
----
start cgSnapImage ["CG2:12345"] rollback memberVolumeset=("memVol1 memVol2 memVol3");
----


== Livello minimo del firmware

7.83
