---
permalink: commands-a-z/start-syncmirror-primary-synchronize.html 
sidebar: sidebar 
keywords: start, synchronous, mirror, synchronization 
summary: Il comando start SyncMirror primary synchronize avvia la sincronizzazione del mirroring sincrono. 
---
= Avviare la sincronizzazione del mirroring sincrono
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `start syncMirror primary synchronize` il comando avvia la sincronizzazione del mirroring sincrono.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E2700, E5600, E2800 e E5700, Finché tutti i pacchetti SMcli sono installati.



== Ruoli

Per eseguire questo comando su uno storage array E2800 o E5700, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Nelle versioni precedenti di questo comando, l'identificatore di funzione era `remoteMirror`. Questo identificatore di funzione non è più valido e viene sostituito da `syncMirror`.

====


== Sintassi

[listing, subs="+macros"]
----
pass:quotes[start syncMirror primary ["_volumeName_"]] synchronize
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`primary`
 a| 
Il nome del volume primario per il quale si desidera avviare la sincronizzazione. Racchiudere il nome del volume primario tra virgolette doppie (" ") all'interno di parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.10
