---
permalink: commands-a-z/start-tray-locate.html 
sidebar: sidebar 
keywords: start, tray, locate 
summary: Il comando START tray Locate individua un vassoio accendendo la spia. 
---
= Localizzazione del vassoio di avvio - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start tray locate` il comando individua un vassoio accendendo l'indicatore luminoso.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Contesto

Utilizzare `stop tray locate` comando per spegnere l'indicatore luminoso del vassoio



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[start tray [_trayID_]] locate
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`tray`
 a| 
Il vassoio che si desidera individuare. I valori dell'ID vassoio sono `0` a. `99`. Racchiudere il valore dell'ID vassoio tra parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.10
