---
permalink: commands-a-z/start-volume-initialization.html 
sidebar: sidebar 
keywords: start, volume, initialization 
summary: Il comando start volume initialize avvia la formattazione di un volume in un array di storage. 
---
= Inizializzazione del volume di avvio - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start volume initialize` il comando avvia la formattazione di un volume in un array di storage.



[[supported-arrays]]
== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



[[roles]]
== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



[[context]]
== Contesto

[NOTE]
====
La formattazione di un volume avvia un'operazione a esecuzione prolungata che non è possibile interrompere.

====


[[syntax]]
== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
----


[[parameter]]
== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volume`
 a| 
Il nome di un volume che si desidera formattare. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.

|===


[[minimum-firmware-level]]
== Livello minimo del firmware

6.10
