---
permalink: commands-a-z/start-volumegroup-locate.html 
sidebar: sidebar 
keywords: start, volume, group, locate 
summary: Il comando START VolumeGroup Locate identifica i dischi raggruppati in modo logico per formare il gruppo di volumi specificato facendo lampeggiare gli indicatori luminosi sui dischi. 
---
= Avvia la localizzazione del gruppo di volumi - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `start volumeGroup locate` il comando identifica le unità raggruppate in modo logico per formare il gruppo di volumi specificato facendo lampeggiare le spie delle unità.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Utilizzare `stop volumeGroup locate` comando per spegnere gli indicatori luminosi dei dischi.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] locate
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`volumeGroup`
 a| 
Il nome del gruppo di volumi per il quale si desidera individuare le unità appartenenti a tale gruppo di volumi. Racchiudere il nome del gruppo di volumi tra parentesi quadre ([ ]).

|===


== Livello minimo del firmware

6.16
