---
permalink: commands-a-z/stop-snapimage-rollback.html 
sidebar: sidebar 
keywords: stop, snapshot, image, rollback 
summary: 'Il comando stop SnapImage rollback (Interrompi rollback SnapImage) interrompe un"operazione di rollback dell"immagine snapshot avviata dal comando start SnapImage rollback (Avvia rollback SnapImage).' 
---
= Interrompere il rollback dell'immagine snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `stop snapImage rollback` il comando interrompe un'operazione di rollback dell'immagine snapshot avviata da `start snapImage rollback` comando.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
L'annullamento di un'operazione di rollback dell'immagine snapshot lascia il volume di base in uno stato indeterminato con dati potenzialmente non validi o incoerenti. Il volume dell'immagine snapshot correlato viene disattivato e non può essere utilizzato.

====


== Sintassi

[listing, subs="+macros"]
----
pass:quotes[stop snapImage [_snapCGID:imageID_] rollback]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapImage`
 a| 
Il nome dell'immagine snapshot per cui si desidera interrompere un'operazione di rollback. Il nome di un'immagine istantanea è composto da due parti:

* Il nome del gruppo di snapshot
* Un identificatore per l'immagine snapshot nel gruppo di snapshot


L'identificatore dell'immagine snapshot può essere uno dei seguenti:

* Un valore intero che rappresenta il numero di sequenza dello snapshot nel gruppo di snapshot.
* `NEWEST` -- utilizzare questa opzione per visualizzare l'ultima immagine istantanea creata nel gruppo di snapshot.
* `OLDEST` -- utilizzare questa opzione per visualizzare la prima immagine istantanea creata nel gruppo di snapshot.


Racchiudere il nome dell'immagine istantanea tra virgolette doppie (" ") tra parentesi quadre ([ ]).

|===


== Note

Il nome di un'immagine istantanea ha due parti separate da due punti (:):

* L'identificatore del gruppo di snapshot
* L'identificatore dell'immagine istantanea


Ad esempio, se si desidera interrompere un'operazione di rollback per l'immagine snapshot 12345 in un gruppo di snapshot che ha il nome snapGroup1, utilizzare questo comando:

[listing]
----
stop snapImage ["snapGroup1:12345"] rollback;
----
Per interrompere un'operazione di rollback per l'immagine snapshot più recente in un gruppo di snapshot con il nome snapGroup1, utilizzare questo comando:

[listing]
----
stop snapImage ["snapGroup1:newest"] rollback;
----


== Livello minimo del firmware

7.83
