---
permalink: commands-a-z/stop-snapvolume.html 
sidebar: sidebar 
keywords: stop, snapshot, volume 
summary: 'Il comando stop snapVolume interrompe l"operazione di un volume snapshot.' 
---
= Arresta il volume snapshot - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `stop snapVolume` il comando interrompe l'operazione di un volume snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[stop snapVolume ["_snapVolumeName_"]]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapVolume`
 a| 
Il nome del volume di snapshot che si desidera interrompere. Racchiudere il nome del volume snapshot tra virgolette doppie (" ") tra parentesi quadre ([ ]).

|===


== Note

È possibile utilizzare qualsiasi combinazione di caratteri alfanumerici, caratteri di sottolineatura (_), trattini (-) e cancelletto ( n.) per i nomi. I nomi possono avere un massimo di 30 caratteri.



== Livello minimo del firmware

7.83
