---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: Il comando stop StorageArray driveFirmwareDownload interrompe il download del firmware sui dischi di uno storage array avviato con il comando download StorageArray drivefirmware. 
---
= Interrompere il download del firmware del disco array di storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `stop storageArray driveFirmwareDownload` il comando interrompe il download del firmware sui dischi di uno storage array avviato con `download storageArray driveFirmware` comando.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Questo comando non interrompe il download del firmware già in corso su un disco. Questo comando interrompe tutti i download del firmware sui dischi in attesa del download.



== Sintassi

[listing]
----
stop storageArray driveFirmwareDownload
----


== Parametri

Nessuno.



== Livello minimo del firmware

6.10
