---
permalink: commands-a-z/stop-consistencygroup-pendingsnapimagecreation.html 
sidebar: sidebar 
keywords: stop, snapshot, images, consistency, group 
summary: Il comando stop consistencyGroup pendingSnapImageCreation arresta tutte le immagini snapshot in sospeso che devono essere create in un gruppo di coerenza snapshot. 
---
= Arresta le immagini snapshot in sospeso sul gruppo di coerenza - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `stop consistencyGroup pendingSnapImageCreation` il comando interrompe tutte le immagini snapshot in sospeso che devono essere create in un gruppo di coerenza snapshot.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Contesto

Se il gruppo di coerenza snapshot non dispone di immagini snapshot in sospeso, il software di gestione dello storage visualizza un messaggio di errore e non esegue il comando.



== Sintassi

[source, cli, subs="+macros"]
----
stop consistencyGroup pass:quotes[[_consistencyGroupName_]]pendingSnapImageCreation
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`consistencyGroupName`
 a| 
Il nome del gruppo di coerenza per il quale si desidera interrompere qualsiasi operazione di snapshot in sospeso. Racchiudere il nome del gruppo di coerenza tra parentesi quadre ([ ]). Se il nome del gruppo di coerenza contiene caratteri speciali o numeri, è necessario racchiudere il nome del gruppo di coerenza tra virgolette doppie (" ") tra parentesi quadre.

|===


== Livello minimo del firmware

7.83
