---
permalink: commands-a-z/stop-cgsnapvolume.html 
sidebar: sidebar 
keywords: stop, consistency, group, snapshot, volume 
summary: 'Il comando stop cgSnapVolume interrompe l"operazione di copia su scrittura per la creazione di un volume snapshot di un gruppo di coerenza.' 
---
= Arrestare il volume snapshot del gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `stop cgSnapVolume` il comando interrompe l'operazione copy-on-write per la creazione di un volume snapshot di un gruppo di coerenza.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Per riavviare l'operazione copy-on-write, utilizzare `resume cgSnapVolume` comando.

[NOTE]
====
Questo comando non elimina un volume snapshot di un gruppo di coerenza. Per eliminare un volume snapshot di un gruppo di coerenza, utilizzare `delete cgSnapVolume` comando.

====


== Sintassi

[listing, subs="+macros"]
----
pass:quotes[stop cgSnapVolume [_snapVolumeName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`cgSnapVolume`
 a| 
Il nome del volume snapshot del gruppo di coerenza che si desidera interrompere la creazione. Racchiudere il nome del volume tra parentesi quadre ([ ]). Se il nome del volume contiene caratteri speciali o numeri, è necessario racchiuderlo tra virgolette doppie (" ") all'interno di parentesi quadre.

|===


== Livello minimo del firmware

7.83
