---
permalink: commands-a-z/stop-volumecopy-target-source.html 
sidebar: sidebar 
keywords: stop, volume, copy 
summary: 'Il comando STOP VolumeCopy target source interrompe un"operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.' 
---
= Interrompi copia volume - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `stop volumeCopy target source` il comando interrompe un'operazione di copia del volume. Questo comando è valido per le coppie di copie di volumi snapshot.



== Array supportati

Questo comando si applica a qualsiasi array di storage individuale, inclusi E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 e EF80, a condizione che tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E4000, E2800, E5700, EF600, EF300, EF50 o EF80, devi avere il ruolo Storage Admin.



== Sintassi

[source, cli, subs="+macros"]
----
pass:quotes[stop volumeCopy target [_targetName_]] source pass:quotes[[_sourceName_]]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`target`
 a| 
Il nome del volume di destinazione per il quale si desidera interrompere un'operazione di copia del volume. Racchiudere il nome del volume di destinazione tra parentesi quadre ([ ]). Se il nome del volume di destinazione contiene caratteri speciali o numeri, è necessario racchiudere il nome del volume di destinazione tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`source`
 a| 
Il nome del volume di origine per il quale si desidera interrompere un'operazione di copia del volume. Racchiudere il nome del volume di origine tra parentesi quadre ([ ]). Se il nome del volume di origine contiene caratteri speciali o numeri, è necessario racchiudere il nome del volume di origine tra virgolette doppie (" ") tra parentesi quadre.

|===