---
permalink: commands-a-z/stop-asyncmirrorgroup-rolechange.html 
sidebar: sidebar 
keywords: cancel, asynchronous, mirror, group, role, reversal 
summary: 'Il comando stop asyncMirrorGroup rolechange annulla un"operazione di inversione del ruolo in sospeso tra gruppi di mirror asincroni.' 
---
= Annulla l'inversione del ruolo del gruppo mirror asincrono
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `stop asyncMirrorGroup rolechange` il comando annulla un'operazione di inversione del ruolo in sospeso tra gruppi di mirror asincroni.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Sintassi

[listing, subs="+macros"]
----
pass:quotes[stop asyncMirrorGroup [_asyncMirrorGroupName_]] rolechange
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`asyncMirrorGroup`
 a| 
Il nome del gruppo di mirror asincrono per il quale si desidera annullare l'operazione di inversione del ruolo in sospeso. Racchiudere il nome del gruppo mirror asincrono tra parentesi quadre ([ ]). Se il nome del gruppo mirror asincrono contiene caratteri speciali o è composto solo da numeri, è necessario racchiudere il nome tra virgolette doppie (" ") tra parentesi quadre.

|===


== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
