---
permalink: commands-a-z/stop-drivechannel-faultdiagnostics.html 
sidebar: sidebar 
keywords: stop, drive, channel, fault, isolation, diagnostics 
summary: Il comando STOP DriveChannel faultDiagnostics arresta la diagnostica di isolamento degli errori del canale di trasmissione, che interrompe il comando di diagnostica di isolamento degli errori del canale di avvio prima del completamento. 
---
= Arrestare la diagnostica di isolamento degli errori del canale di trasmissione
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `stop driveChannel faultDiagnostics` il comando interrompe la diagnostica di isolamento degli errori del canale di guida, che arresta `start drive channel fault isolation diagnostics` prima del completamento.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

[NOTE]
====
Con la versione del firmware 8.10, il `stop driveChannel faultDiagnostics` comando obsoleto.

====


== Sintassi

[listing]
----
stop driveChannel faultDiagnostics
----


== Parametri

Nessuno.



== Note

Utilizzare `start driveChannel faultDiagnostics` e il `save driveChannel faultDiagnostics` con il `stop driveChannel faultDiagnostics` comando. Questi comandi sono necessari per avviare il test diagnostico e salvare i risultati del test diagnostico in un file.

È anche possibile arrestare `start driveChannel faultDiagnostics` premere in qualsiasi momento `Ctrl+C`.



== Livello minimo del firmware

7.15
