---
permalink: commands-a-z/stop-pendingsnapimagecreation.html 
sidebar: sidebar 
keywords: stop, snapshot, group, snapshot, images 
summary: Il comando stop pendingSnapImageCreation annulla tutte le immagini snapshot in sospeso che devono essere create in un gruppo di coerenza snapshot o snapshot. 
---
= Interrompere le immagini snapshot in sospeso del gruppo di snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `stop pendingSnapImageCreation` il comando annulla tutte le immagini snapshot in sospeso che devono essere create in un gruppo di coerenza snapshot o snapshot.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo di amministratore dello storage.



== Contesto

Se il gruppo di snapshot non dispone di immagini snapshot in sospeso, il firmware visualizza un messaggio di errore e non esegue il comando. È possibile eseguire questo comando su un gruppo di snapshot o su un gruppo di coerenza di snapshot.



== Sintassi

[listing, subs="+macros"]
----
stop (snapGroup pass:quotes[[_snapGroupName_]] |
consistencyGroup pass:quotes[[_snapConsistencyGroupName_]])
pendingSnapImageCreation
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`snapGroup`
 a| 
Il nome del gruppo di snapshot per cui si desidera interrompere le immagini snapshot in sospeso. Racchiudere il nome del gruppo di snapshot tra parentesi quadre ([ ]). Se il nome del gruppo di snapshot ha caratteri speciali o numeri, è necessario racchiudere il nome del gruppo di snapshot tra virgolette doppie (" ") tra parentesi quadre.



 a| 
`consistencyGroup`
 a| 
Il nome del gruppo di coerenza snapshot per il quale si desidera interrompere le immagini snapshot in sospeso. Racchiudere il nome del gruppo di coerenza snapshot tra parentesi quadre ([ ]). Se il nome del gruppo di coerenza snapshot contiene caratteri speciali o numeri, è necessario racchiudere il nome del gruppo di snapshot tra virgolette doppie (" ") tra parentesi quadre.

|===


== Livello minimo del firmware

7.83
