---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: Il comando stop StorageArray driveFirmwareDownload interrompe il download del firmware sui dischi di uno storage array avviato con il comando download StorageArray drivefirmware. 
---
= Interrompere il download del firmware dell'unità array di archiviazione - CLI SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `stop storageArray driveFirmwareDownload` il comando interrompe il download del firmware sui dischi di uno storage array avviato con `download storageArray driveFirmware` comando.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi gli array E4000, E2700, E5600, E2800, E5700, EF600 e EF300, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su uno storage array E4000, E2800, E5700, EF600 o EF300, è necessario avere il ruolo di amministratore dello storage.



== Contesto

Questo comando non interrompe il download del firmware già in corso su un disco. Questo comando interrompe tutti i download del firmware sui dischi in attesa del download.



== Sintassi

[source, cli]
----
stop storageArray driveFirmwareDownload
----


== Parametri

Nessuno.



== Livello minimo del firmware

6.10
