---
permalink: commands-a-z/suspend-ssdcache.html 
sidebar: sidebar 
keywords: suspend, ssd cache 
summary: Il comando suspend ssdCache interrompe temporaneamente il caching per tutti i volumi che utilizzano la cache SSD. 
---
= Sospendere la cache SSD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `suspend ssdCache` Il comando interrompe temporaneamente il caching per tutti i volumi che utilizzano la cache SSD.



== Array supportati

Questo comando si applica a qualsiasi singolo storage array, inclusi E2700, E5600, E2800, E5700, Array EF600 e EF300, purché tutti i pacchetti SMcli siano installati.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Support Admin.



== Contesto

Durante l'interruzione del caching, le letture degli host vengono gestite dai volumi di base invece che dalla cache SSD.



== Sintassi

[listing, subs="+macros"]
----

pass:quotes[suspend ssdCache [_ssdCacheName_]]
----


== Parametro

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`ssdCache`
 a| 
Il nome della cache SSD che si desidera sospendere. Racchiudere il nome della cache SSD tra parentesi quadre ([ ]). Se il nome della cache SSD contiene caratteri speciali o numeri, è necessario racchiudere il nome della cache SSD tra virgolette doppie (" ") tra parentesi quadre.

|===


== Note

Per riavviare il caching, utilizzare `resume ssdCache` comando.



== Livello minimo del firmware

7.84

11.80 aggiunge il supporto degli array EF600 e EF300
