---
permalink: commands-a-z/validate-storagearray-securitykey.html 
sidebar: sidebar 
keywords: validate, storage array, security key 
summary: Il comando validate StorageArray securityKey convalida la chiave di sicurezza per uno storage array dotato di dischi con funzionalità di sicurezza per garantire che il file della chiave di sicurezza di backup non sia corrotto. 
---
= Convalidare la chiave di sicurezza dello storage array
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Il `validate storageArray securityKey` il comando convalida la chiave di sicurezza per un array di storage dotato di dischi con funzionalità di sicurezza per garantire che il file della chiave di sicurezza di backup non sia corrotto.



== Array supportati

Se è attivata la gestione delle chiavi esterne, questo comando si applica solo agli array E2800 ed E5700. Se è attivata la gestione delle chiavi interne, il comando si applica a qualsiasi singolo array di storage, purché siano installati tutti i pacchetti SMcli.



== Ruoli

Per eseguire questo comando su un array di storage E2800, E5700, EF600 o EF300, è necessario disporre del ruolo Security Admin.



== Contesto

La convalida della chiave di sicurezza utilizza la passphrase utilizzata per generare il file per decrittare la chiave e abbinarla al valore mantenuto nella memoria del controller (per le chiavi interne) o sul server esterno (per le chiavi esterne).

[NOTE]
====
Questo comando si applica alla gestione delle chiavi sia interna che esterna.

====


== Sintassi

[listing, subs="+macros"]
----

pass:quotes[validate storageArray securityKey file="_fileName_" passPhrase="_passPhraseString_"]
----


== Parametri

[cols="2*"]
|===
| Parametro | Descrizione 


 a| 
`file`
 a| 
Il percorso del file e il nome del file che ha la chiave di sicurezza. Racchiudere il percorso del file e il nome del file tra virgolette doppie (" "). Ad esempio:

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
Il nome del file deve avere un'estensione di `.slk`.

====


 a| 
`passPhrase`
 a| 
Stringa di caratteri che crittografa la chiave di protezione in modo da potervi memorizzare in un file esterno. Racchiudere la passphrase tra virgolette doppie (" ").

|===


== Livello minimo del firmware

7.70
